### PR TITLE
New KYC `pending` status

### LINKED ISSUE #2751: Crypto-to-fiat: Provide additional KYC status after Persona flow has been completed
## Specification

At the moment, the KYC status changes to `incomplete` as soon as the user begins the Persona flow. The next time it changes is when Bridge is notified by Persona regarding the verification outcome, meaning there's no way for the UI to tell if the KYC form is incomplete or whether it is just awaiting an update from Persona.

This issue is to add additional KYC status (`submitted` maybe?) that would sit in between `incomplete` and the possible outcome statuses:
image

### PR DESCRIPTION
**Pull request by jakubcolony**
## Description

Please refer to issue for context.

This PR improves the UX around the KYC verification by adding an intermediate status between the user completing the KYC flow and Bridge receiving a response. It cleans up some types and todos and introduces a GQL enum for the statuses.

**Important**: You will need to add a new variable to `.env.secrets.local`: `PERSONA_ENVIRONMENT_ID`, and run `npm run prepare`. 

## Testing

When Persona notifies of the flow being complete, a flag is set on the user profile which then overrides the status in the lambda handler. 

To avoid having to complete the entire KYC flow, you can apply the following patch to mimic the behaviour when you cancel the KYC flow as well. Save it in a file called `diff` and run `git apply diff` in the CDapp directory:

```
diff --git a/src/components/frame/v5/pages/UserCryptoToFiatPage/partials/Verification/Verification.tsx b/src/components/frame/v5/pages/UserCryptoToFiatPage/partials/Verification/Verification.tsx
index 99cbfe44e..b013548fc 100644
--- a/src/components/frame/v5/pages/UserCryptoToFiatPage/partials/Verification/Verification.tsx
+++ b/src/components/frame/v5/pages/UserCryptoToFiatPage/partials/Verification/Verification.tsx
@@ -53,6 +53,18 @@ const Verification: FC<CryptoToFiatPageComponentProps> = ({
           },
         });
 
+        refetchStatus();
+      },
+      async onCancel() {
+        await updateProfile({
+          variables: {
+            input: {
+              id: user?.walletAddress ?? '',
+              hasCompletedKYCFlow: true,
+            },
+          },
+        });
+
         refetchStatus();
       },
     });

```

In `amplify/backend/function/bridgeXYZMutation/src/index.js` replace `apiKey` with sandbox API key (ping me if you don't have it) and start the KYC verification. When you get to the KYC modal close it at any point. The status should refresh. In sandbox, the KYC is automatically approved however in production the lambda handler would return `pending` until KYC is processed.

Resolves #2751

### CODE REVIEW

**Review by Nortsova — APPROVED** [review]
Thanks @jakubcolony for this fix ✨

I can confirm that after filling KYC form status changes to "Approved"
Jul-24-2024 16-17-03

Also I can confirm that `hasCompletedKYCFlow` became **true**
image

**Review by mmioana — APPROVED** [review]
Awesome work on this one @jakubcolony 🚀 

I could see the status update when closing the Persona flow

https://github.com/user-attachments/assets/37903ccc-9786-4254-85f7-a42afbf4a715

The update is present also on the user profile
Screenshot 2024-07-25 at 08 06 25

And many thanks for adding also the 'Pending' state copy and badge theme ❤️ 
Screenshot 2024-07-25 at 08 07 11

**Review by rdig — APPROVED** [review]
Tested and seems to be working as you described in your steps

Screenshot from 2024-07-26 00-33-15
Screenshot from 2024-07-26 00-33-42
Screenshot from 2024-07-26 00-33-50

I do want to point out that the loader state _(when initially loading the offramp tab)_ is off centered

Screenshot from 2024-07-26 00-27-37

I'd also want to add two more pieces of information to your testing steps:
- make sure you enable your feature flags, otherwise the offramp tab won't load. I used the `useFeatureFlag` hook
- Make sure you set your `PERSONA_ENVIRONMENT_ID` inside your env secrets file, and then run `npm run prepare`

**Review by Nortsova — APPROVED** [review]
Thanks for updates ✨

**Comment by jakubcolony** [comment]
@rdig thanks for your review

> I'd also want to add two more pieces of information to your testing steps:
> - make sure you enable your feature flags, otherwise the offramp tab won't load. I used the useFeatureFlag hook

It looks like something got messed up in PostHog, the flag should've been enabled for all users in local dev without checking wallet address.

> - Make sure you set your PERSONA_ENVIRONMENT_ID inside your env secrets file, and then run npm run prepare

That should've already been in the instructions, 3 paragraph from the top

**Pull request merged**
