### PR TITLE
fix: field label error color

### LINKED ISSUE #1735: Actions: Styling of error states
**Teamwork task:** [Actions: Styling of error states](https://tw.auroracreation.com/#/tasks/15750753)

## Description

The field label of the error state doesn't match Figma designs and should be color-negative-400 to match the icon and input field. The scope of this PR is to fix this across all action types to ensure alignment with Figma and consistency in the UI. 

**How it currently shows:**
image

**Figma:**
image

## Figma links

Example of error states: https://www.figma.com/file/5V8pr7iMwXsT9L3VAZsmUt/Colony-v5?type=design&node-id=10070-268264&mode=design&t=vUqwuYYcWBGj21pv-4

### PR DESCRIPTION
**Pull request by mksawic**
## Description

https://tw.auroracreation.com/app/tasks/15750753

**Changes** 🏗

* Change color for field label on error

Resolves #1735

### CODE REVIEW

**Review by iamsamgibbs — APPROVED** [review]
Looks good to me! Tested and fixes the issue.

Screenshot 2024-01-29 at 10 04 22

Although I wonder if there is a better variable name we can use than `iconClassNames` as it now affects more than the icon and only changes the text colour depending on whether there is an error or not.

**Review by warrencolliver — APPROVED** [review]
Everything looks good to me. However Sam has raised a good point with the naming.

**Review by melyndav — APPROVED** [review]
Thanks for picking up my issue @mksawic! Approved from my side.

**Review by iamsamgibbs — APPROVED** [review]
Looks good to me! Thanks for the change!

**Review by warrencolliver — APPROVED** [review]
good work

**Pull request merged**
