### PR TITLE
[New Nav]: Update member routes

### LINKED ISSUE #3136: [New Navigation] Member pages routing updates
## Description

This issue aims to update Members-related routes.

## Acceptance Criteria

* [ ] `/{colonyName}/members/contributors` should now be `/{colonyName}/members`
* [ ] `/{colonyName}/members` should now be `/{colonyName}/members/followers`

### PR DESCRIPTION
**Pull request by rumzledz**
## Description

This PR is for updating the Members routing:

The Members Route Item on the Colony Sidebar will now take you to the `/members` route , which is now set to be the default active tab when you land on the Members page
image

Clicking the Followers tab in the Members page will now take you to the `/members/followers` route
image

## Testing

> [!NOTE]
> Currently, when you're switching to the Followers tab, the Sidebar Route Item for Members is not highlighted. I spoke to product and this is all right because there is a future plan to remove this tab.

1. On the Sidebar, click Members
2. Verify that you are taken to `/members`
3. Verify that the tab information such as the title and description have been updated to match the [Figma designs](https://www.figma.com/design/uKxVl441Wnn02SNiOA24De/Navigation?node-id=3501-74605&t=drc1CLP31Z3NPV9S-4)

image

4. Verify that the Browser tab title has the correct copy i.e. "Members | ..."
5. In the Members page, click the "Followers" tab
6. Verify that you are taken to `members/followers` 
7. Verify that the tab information such as the title and description have been updated to match the [Figma designs](https://www.figma.com/design/uKxVl441Wnn02SNiOA24De/Navigation?node-id=3501-74682&t=drc1CLP31Z3NPV9S-4)

image

8. Verify that the Browser tab title has the correct copy i.e. "Followers | ..."

Resolves #3136

### CODE REVIEW

**Review by mmioana — APPROVED** [review]
Smashed another one @rumzledz 🙌 

https://github.com/user-attachments/assets/84d0e278-1846-4426-b4fb-3af727097477

However, I noticed there is a small delay in the active tab changing from the `Contributors` to `All members` tab, which is caused by the default value given to the `activeTab` state in `src/components/frame/v5/pages/MembersPage/MembersPage.tsx`

I guess a solution would be to make use of the following check for the default value for the `activeTab` state to prevent this delay

```
  let defaultActiveTab = 0;

  if (pathname === resolvedMembersPath.pathname) {
    defaultActiveTab = 1
  } else if (pathname === resolvedContributorsPath.pathname) {
    defaultActiveTab = 0;
  }

  const [activeTab, setActiveTab] = useState(defaultActiveTab);
```

Nonetheless, feel free to tackle this issue if and as you consider fit 👍

**Comment by rumzledz** [comment]
> I'm not sure if it is intended or not for menu items to stay highlighted whilst you navigate around their "children", worth checking with product, but if so there are a few other places where this is missing

Okay @iamsamgibbs I'll speak to @arrenv about that but maybe I'll tackle that in a different PR since it's out of scope

> However, I noticed there is a small delay in the active tab changing from the Contributors to All members tab, which is caused by the default value given to the activeTab state in src/components/frame/v5/pages/MembersPage/MembersPage.tsx

@mmioana I mean... it's out of scope and I didn't even work on tab logic 😂 But sure! Happy to deal with this in a separate PR so everyone's happy 🫶

**Comment by rumzledz** [comment]
> However, I noticed there is a small delay in the active tab changing from the Contributors to All members tab, which is caused by the default value given to the activeTab state in src/components/frame/v5/pages/MembersPage/MembersPage.tsx

By the way this is a `master` bug so i'll raise an issue but will fix it on `master` @mmioana 👌

**Comment by rumzledz** [comment]
Tiny update for you @mmioana: The button now takes you to the 1st tab on the Members page so that lag with the tab doesn't happen anymore. And in the future, these tabs will be removed apparently so no need to deal with the tab logic updates 👌

**Review by bassgeta — CHANGES_REQUESTED** [review]
Yup, changes seem sensible and I'm sorry you've had to shoulder the burden of the tabs tech debt here :D
Clicking on the `Members` button takes me to the members page
image
Followers does nothing but it navigates to the sidebar and changes the URL:
image

Although (man I'm sorry to notice this), the `Members` tab title is still `Contributors`
image
and the `Followers` tab is `Members`
image

do we wanna do something about it here or we merge this and change it on a separate issue?

**Comment by rumzledz** [comment]
@bassgeta good spot! this is a result of ad-hoc changes over a call 😂 It's just a small 2-minute scope creep, will update!
image

Not sure what you mean by this though - will message you for clarity!
image

**Comment by arrenv** [comment]
I take full responsibility.

**Review by iamsamgibbs — CHANGES_REQUESTED** [review]
I'm experiencing the same issue as Kerry with the tab titles being incorrect.

Everything else looks good though!

Screenshot 2024-09-25 at 08 44 04
Screenshot 2024-09-25 at 08 44 20

**Comment by rumzledz** [comment]
I've just pushed a fix for the tab titles so they now say "Members | ..." & "Followers | ..." @iamsamgibbs @bassgeta thank you!

**Comment by rumzledz** [comment]
> I take full responsibility.

Hahaha it's not a biggie @arrenv , just tiny copy changes is all!

**Review by iamsamgibbs — APPROVED** [review]
🎉  Correct titles are showing now!

Screenshot 2024-09-25 at 09 43 35
Screenshot 2024-09-25 at 09 43 39

**Pull request merged**
