### PR TITLE
Fix: DonutChart tooltip displaying at wrong position

### LINKED ISSUE #1604: [Donut chart]: Hovered segment tooltip initially displays at the wrong coordinates
When hovering on a chart segment,  the tooltip appears somewhere else for a brief moment before jumping to its correct position:

https://github.com/JoinColony/colonyCDapp/assets/112586815/d5192d73-bc58-4f10-8c88-9147bcde3006

Screenshot 2023-12-20 at 21 27 42

_Originally posted by @jakubcolony in https://github.com/JoinColony/colonyCDapp/pull/1566#pullrequestreview-1791697151_
 
 If you check `DonutChart/hooks.tsx` in the function `handleMouseOver` the tooltip width fallback to 0 causes the tooltip to be displayed to the right initially.
 I've tried not setting styles until we have the tooltipRef, but then I get vertical issues instead of horizontal ones :facepalm:

### PR DESCRIPTION
**Pull request by jakubcolony**
## Description

This PR fixes an issue with `DonutChart` tooltip initial positioning:

https://github.com/JoinColony/colonyCDapp/assets/112586815/c7523ebe-9d6e-40c8-ba5f-034cd75ae90f

It utilises `flushSync` to ensure DOM gets updated before we attempt to calculate the tooltip position.

`DonutChart` has been moved to `shared` folder.

Resolves #1604

### CODE REVIEW

**Review by bassgeta — APPROVED** [review]

**Review by ArmandoGraterol — CHANGES_REQUESTED** [review]
The tooltip is not jumping around however my screen is 😂 

[Screenity video - Jan 15, 2024, 5-04-08 PM.webm](https://github.com/JoinColony/colonyCDapp/assets/18473896/5e50346f-6c01-4d3a-8357-3db11d611f55)

The screen shakes a little when I hover over the segments, this MIGHT be specific to my screen size tho.

**Comment by bassgeta** [comment]
> The tooltip is not jumping around however my screen is 😂
> Screenity.video.-.Jan.15.2024.5-04-08.PM.webm
> 
> The screen shakes a little when I hover over the segments, this MIGHT be specific to my screen size tho.

I double checked, it didn't happen for me in Firefox, but the shaking happens in Brave so it's a Chromium bug, which we most likely need to resolve :sweat_smile:

**Review by melyndav — CHANGES_REQUESTED** [review]
Hey @jakubcolony!

I noticed the same screenshaking as Armando when hovering over the component.

Also, I'm not seeing all the other teams show up and when I hover over the small portion of the chart you can't see the colour inside the chart.

image

Even with small percentages, we should make it at least visible in the chart.

**Review by melyndav — CHANGES_REQUESTED** [review]
Hey @jakubcolony I'm still getting the screen shake on hover for this one.

**Review by ArmandoGraterol — APPROVED** [review]
For me it's not jumping around anymore. Good job!

**Review by iamsamgibbs — APPROVED** [review]
Tested and cannot recreate screen shake issue.

**Review by bassgeta — APPROVED** [review]
tested on firefox and brave, no more jumpy bois, gj!

**Comment by melyndav** [comment]
Hey @jakubcolony! Rechecked and this is good to go! Thanks for working on this one. 👍

**Review by melyndav — APPROVED** [review]

**Pull request merged**
