### PR TITLE
Remove ability to deprecate one tx payment

### PR DESCRIPTION
**Pull request by willm30**
## Description

This PR prevents you from being able to deprecate the One Tx Payment extension.

### CODE REVIEW

**Review by ArmandoGraterol — COMMENTED** [review]
If the contracts allow it, shouldn't we also allow it?

**Review by jakubcolony — APPROVED** [review]
Don't know an answer to Armando's question but the change looks & works good

**Comment by willm30** [comment]
@jakubcolony I was actually going to ask you... this was from a note you'd made in the notion qa doc. I.e. you said we should not be able to deprecate the extn. Any chance you remember the rationale?

**Comment by jakubcolony** [comment]
@willm30 This was based on the current Dapp behaviour

**Comment by willm30** [comment]
@ArmandoGraterol Thoughts? In the dapp you can't deprecate OneTxPayment extn.

**Comment by jakubcolony** [comment]
@willm30 I came across this in #950 again and realised there's a `uninstallable` property on the extension config in `~constants/extensions`. I think we can close this PR.

**Pull request closed without merging**
