### PR TITLE
fix: correct activity feed share link

### PR DESCRIPTION
**Pull request by KornelKwiatkowski**
Teamwork: https://tw.auroracreation.com/app/tasks/15750743

## Description

Corrected Activity feed share link

Resolves: #1737

### CODE REVIEW

**Review by arrenv — APPROVED** [review]
Welcome back @KornelKwiatkowski this fixes the URL for me, thank you!

**Review by melyndav — APPROVED** [review]
Great to have you back @KornelKwiatkowski. This one is approved! 👍

**Review by iamsamgibbs — APPROVED** [review]
Tested and looks good to me! :)

**Review by warrencolliver — APPROVED** [review]
Looks good!

**Pull request merged**
