### PR TITLE
Crypto to fiat: Connect drains history table with data from Bridge

### LINKED ISSUE #2572: Motions gas estimation refactor
## Specification

As discussed in the call, the current mechanism of estimating gas required for finalizing motion at its creation is a bit flaky and can lead to issues with certain gas-heavy transactions.

Previously, we could not rely on estimating gas at the time of finalization due to the fact that `finalizeMotion` will succeed even if the underlying transaction fails, as long as one week has elapsed since motion becoming finalizable. This changed with Alex introducing `finalizeMotionWithoutFailure` method that will never succeed unless the underlying transaction does too.

- Refactor `finalizeMotion` saga to estimate gas for `finalizeMotionWithoutFailure` call and proceed with that call if estimation succeeds. If estimation fails, we can assume the underlying transaction will fail. If it's been more than a week, saga should call `finalizeMotion` instead. This will release stakes and rewards, but action will not execute. 
- Remove motions gas estimation from block-ingestor and schema.

### LINKED ISSUE #2752: Crypto to fiat: Connect drains history table with data from Bridge
## Specification

Both the UI and the lambda handler for drain history have been implemented but they are not yet integrated together. The lambda handler needs to be adjusted to Bridge API (e.g. remove `Idempotency-Key` from the GET requests) and then wired in the table in the crypto-to-fiat tab.

Testing might be tricky and the easiest solution will probably pointing directly at Bridge prod, please get in touch when you get that far and we'll organise something.

### PR DESCRIPTION
**Pull request by jakubcolony**
## Description

This PR adjusts the drains history lambda handler for production API and wires the returned data with the table in the crypto-to-fiat tab.

I've also attempted to split the now massive `schema.graphql` into multiple files, with `bridge.graphql` containing Bridge API-related types.

https://github.com/user-attachments/assets/e10d0d8a-c0b3-4d1f-a41d-a7c872bf0a8d

## Testing

Testing is pretty difficult unless you're connected to prod API and have a history of transfers.

You can validate the UI adhering to designs on `master` where mock data is shown in the table. On this branch, you can test the loading and empty states.

I also presented the prod API response shown in the table above.

Resolves #2752

### CODE REVIEW

**Review by rdig — DISMISSED** [review]
Nicely done! I've tested this with production keys/urls as well as my KYC'd account which has drain history.

After connecting my wallet address to the bridge API and fetching my KYC status, the transfer history shows up as expected.

Screenshot from 2024-07-30 23-23-12

**Review by bassgeta — DISMISSED** [review]
I haven't managed to test it with actual data since I don't have any bridge drains on my profile, but the code changes look sensible, the code runs, so I am willing to take your word on it :D
Let's get this merged :tada:

**Review by rumzledz — DISMISSED** [review]
Unfortunately I don't have any production data to test this with. Nothing stands out after looking at the changes. If I understand correctly, the liquidation address PR relies on this so I'm approving this to unblock your other PR ✅

**Review by rumzledz — APPROVED** [review]

**Review by bassgeta — APPROVED** [review]
Still looking good after the rebase, reapproving!

**Review by rdig — APPROVED** [review]
Re-approving due to rebase

**Pull request merged**
