### PR TITLE
Port Safe Control feature

### PR DESCRIPTION
**Pull request by ArmandoGraterol**
This is the feature branch for the Safe Control feature.

Issues related to this feature can be found here: https://github.com/orgs/JoinColony/projects/25

## Resources
- Docs [here](https://docs.colony.io/use/managing-funds/gnosis-safe-control/)
- Flow chart [here](https://lucid.app/lucidspark/43230a2b-4fa9-46de-bcd9-be8cd4031276/edit?viewport_loc=-600%2C-1075%2C9000%2C4438%2C0_0&invitationId=inv_bc948a06-9365-4966-bfcf-c4c73d62b430)
- Figma [here](https://www.figma.com/file/LlVmeMQxHVA04evfrgZyuN/Safe-Control?node-id=115%3A7477&mode=dev)

## Safes for testing
- If you want to be co-owner of any of these safes in order to execute transactions/snoop around/debug, please notify me.
- Otherwise, you can easily create your own safe via https://app.safe.global/welcome

### Ethereum

**Safe**: `0x3F107AFF0342Cfb5519A68B3241565F6FC9BAC1e` (It should have some funds and 1 NFT)
**Module**: `0x8dfABd117Db8BC64829Ce7C595F20998b054cDC2`

### Binance Smart Chain

**Safe**: `0xe759f388c97674D5B8a60406b254aB59f194163d`
**Module**: `0xCC199aCAb2B38C6DC5f7304B29BDEb3a83E7d212`

## Testing
1. Checkout this branch
2. A new amplify function and package have been added so run `npm i`.
3. `npm run dev` as usual. The difference is that now a `safe` docker container should be created and be up once the dev env is completely set up.
4. Once the safe docker container is successfully up, it will print out in the console the values you need for the .env file (Check the `.env.example` for a reference of what env vars are needed.)
5. That's it! After running `npm run webpack` as usual, you should be able to add and remove safes, and send cross-chain safe transactions through the UAC (Advanced > Safe Control).

Clarifications:
- Once you create and send transactions, the `safe` docker container will print a message out in the console notifying you that it saw a message pass through the bridge. (In the case of motions, this message will appear AFTER a successful motion has been finalized.)
- All the transactions should appear as `Completed` immediately after making them because all of the transactions are executed automatically when they are sent in the case of the dev env. (Not the case with the QA/Prod env, in there the user needs to manually execute the transactions in the other chain.)
- You need `Root` permission to add, remove, and make safe transactions.
- You can create motions for the `Control Safe` transactions, but not for adding or removing safes.

### CODE REVIEW

**Comment by willm30** [comment]
@ArmandoGraterol Can you add some instructions to the pr description for how to test this feature, and anything in particular to look out for?

**Comment by ArmandoGraterol** [comment]
@willm30 Hey! Sure, I've included some info that we had on the project page and added testing instructions. Fortunately for us, we no longer need to do that whole bunch of stuff you mention, now docker does it for you.

**Comment by willm30** [comment]
Been clicking around the UI, just like I remembered it! Good work, I know it's a big effort. 

I noticed a couple of things that I've mentioned to @ArmandoGraterol re the form validation (hex length and total funds), but aside from that happy to give the green light once we can verify the transactions actually get executed on the foreign chain, which I expect we'll do on QA.

**Review by rdig — APPROVED** [review]
Nicely done @ArmandoGraterol

**Pull request merged**
