### PR TITLE
Token Activation Modal pending transaction button state

### LINKED ISSUE #1548: Slow transaction trigger and gas limit issue when Activating tokens
## Steps to reproduce
- On production, try to activate some tokens.
- Enter an amount and click the 'Activate tokens' button.
- The button will remain in a clickable state, until the spending cap in Metamask window is loaded.
 - Clicking the button over and over again will cause a too many requests issue.
- Once the it appears, continue with activating tokens.
- It will fail due to a gas limit issue.

## Expected behaviour
- The 'Activate tokens' button should disable and show a loading state on click.
- Activation tokens should not fail due to gas limit issues.
- This issue should fail more gracefully, so, that you can try again when staking.

## Actual behaviour
- The 'Activate tokens' button is continuously clickable despite already being triggered.
- Activating tokens in production is failing due to a gas limit issue.
- When staking on a motion, this error also occurs, which results in the staking button being stuck.

image

### PR DESCRIPTION
**Pull request by rdig**
This PR fixes part of the related issue, which is to add a loading state to the button that generates, and sends out, the required transactions to activate the user's tokens.

Screenshot from 2024-01-19 01-16-59

Screenshot from 2024-01-19 01-18-31

**Note** that I've used the same pattern for the button loading state as the one found in the Motions flow: https://github.com/JoinColony/colonyCDapp/blob/3d7878984fbe2c60f672b74d1d952ba2311f66c1/src/components/v5/common/ActionSidebar/partials/Motions/steps/FinalizeStep/FinalizeStep.tsx#L142-L157

The second part of this issue cannot be fixed by the client, since it requires a contract upgrade _(In order to have the Token Authority allow users to activate tokens, while the token is still locked)_. For a quick "fix" for existing colonies, unlocking the token allows users to activate their tokens as expected.

Note however that the above contract fix still requires #1741 to be merged before we can attempt new contract deployments.

Resolves #1548

### CODE REVIEW

**Review by iamsamgibbs — APPROVED** [review]
Looks good to me!

**Comment by jakubcolony** [comment]
@rdig could you rebase to include Chris's fix?

**Comment by rdig** [comment]
Done

**Review by jakubcolony — APPROVED** [review]
LGTM

**Review by arrenv — APPROVED** [review]
Looks good to me, thank you @rdig!

**Pull request merged**
