### PR TITLE
User Hub - Stakes tab

### LINKED ISSUE #1229: User Hub - Stakes tab
This issue is to wire the Stakes tab with data:
image

### PR DESCRIPTION
**Pull request by jakubcolony**
## Description

This PR adds stakes data to User Hub Stakes tab:
image

The UI required a new data model, `UserStakes`, that will hold information about any stake being made for a motion (or an expenditure in the future). A stake can be in one of 4 states:
- Staking - the underlying motion is currently in progress
- Finalizable - the underlying motion is in "Finalizable" state
- Claimable - the underlying motion is "Finalized" or "Failed"
- Claimed - the stake has been claimed

The tricky part is where we need to filter by the status as this requires us to fetch the underlying motion state for every stake. The current solution is `useNetworkMotionStates` query that calls the voting reputation contract directly (much faster than the existing `fetchMotionState` but we need to keep both for now). If performance turns out to be an issue, there are other avenues we can explore.

## Testing

Create a bunch of motions, stake them and progress through different states. The stakes data should show the correct amount and status at all times.

Until the token activation is wired, you can use the old popover which I temporarily placed next to the New Action button:
image

Resolves #1229

### CODE REVIEW

**Review by ArmandoGraterol — COMMENTED** [review]
I'm getting this error whenever I stake a motion. I was able to stake but then the voting wouldn't work and the stakes wouldn't show in the user hub:
```
amplify   | Duplicate definition of ExpenditurePayoutSet (ExpenditurePayoutSet(uint256,uint256,address,uint256), ExpenditurePayoutSet(address,uint256,uint256,address,uint256))
amplify   | Duplicate definition of TokenUnlocked (TokenUnlocked(), TokenUnlocked(address))
amplify   | Error while executing Local DynamoDB
amplify   | {
amplify   |     "version": "2018-05-29",
amplify   |     "operation": "Query",
amplify   |     "limit": 10000,
amplify   |     "query": {
amplify   |         "expression": "#userAddress = :userAddress",
amplify   |         "expressionNames": {
amplify   |             "#userAddress": "userAddress"
amplify   |         },
amplify   |         "expressionValues": {
amplify   |             ":userAddress": {
amplify   |                 "S": "0xb77D57F4959eAfA0339424b83FcFaf9c15407461"
amplify   |             }
amplify   |         }
amplify   |     },
amplify   |     "index": "byUserAndColony",
amplify   |     "scanIndexForward": true,
amplify   |     "filter": {
amplify   |         "expression": "#colonyAddress = :colonyAddress_eq",
amplify   |         "expressionNames": {
amplify   |             "#colonyAddress": "colonyAddress"
amplify   |         },
amplify   |         "expressionValues": {
amplify   |             ":colonyAddress_eq": {
amplify   |                 "S": "0xdacd6A03Fe0e163454D71747F22A03503AA01F33"
amplify   |             }
amplify   |         }
amplify   |     }
amplify   | }
amplify   | ValidationException: Filter Expression can only contain non-primary key attributes: Primary key attribute: colonyAddress
amplify   |     at Request.extractError (/snapshot/repo/build/node_modules/aws-sdk/lib/protocol/json.js:52:27)
amplify   |     at Request.callListeners (/snapshot/repo/build/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
amplify   |     at Request.emit (/snapshot/repo/build/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
amplify   |     at Request.emit (/snapshot/repo/build/node_modules/aws-sdk/lib/request.js:686:14)
amplify   |     at Request.transition (/snapshot/repo/build/node_modules/aws-sdk/lib/request.js:22:10)
amplify   |     at AcceptorStateMachine.runTo (/snapshot/repo/build/node_modules/aws-sdk/lib/state_machine.js:14:12)
amplify   |     at /snapshot/repo/build/node_modules/aws-sdk/lib/state_machine.js:26:10
amplify   |     at Request.<anonymous> (/snapshot/repo/build/node_modules/aws-sdk/lib/request.js:38:9)
amplify   |     at Request.<anonymous> (/snapshot/repo/build/node_modules/aws-sdk/lib/request.js:688:12)
amplify   |     at Request.callListeners (/snapshot/repo/build/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
amplify   |     at Request.emit (/snapshot/repo/build/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
amplify   |     at Request.emit (/snapshot/repo/build/node_modules/aws-sdk/lib/request.js:686:14)
amplify   |     at Request.transition (/snapshot/repo/build/node_modules/aws-sdk/lib/request.js:22:10)
amplify   |     at AcceptorStateMachine.runTo (/snapshot/repo/build/node_modules/aws-sdk/lib/state_machine.js:14:12)
amplify   |     at /snapshot/repo/build/node_modules/aws-sdk/lib/state_machine.js:26:10
amplify   |     at Request.<anonymous> (/snapshot/repo/build/node_modules/aws-sdk/lib/request.js:38:9)
amplify   |     at Request.<anonymous> (/snapshot/repo/build/node_modules/aws-sdk/lib/request.js:688:12)
amplify   |     at Request.callListeners (/snapshot/repo/build/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
amplify   |     at callNextListener (/snapshot/repo/build/node_modules/aws-sdk/lib/sequential_executor.js:96:12)
amplify   |     at IncomingMessage.onEnd (/snapshot/repo/build/node_modules/aws-sdk/lib/event_listeners.js:380:13)
amplify   |     at IncomingMessage.emit (events.js:412:35)
amplify   |     at IncomingMessage.emit (domain.js:475:12)
amplify   |     at endReadableNT (internal/streams/readable.js:1333:12)
amplify   |     at processTicksAndRejections (internal/process/task_queues.js:82:21) {
amplify   |   code: 'ValidationException',
amplify   |   time: 2023-11-09T19:53:11.657Z,
amplify   |   requestId: 'd51a086f-e572-426f-9b22-69f7d2679e43',
amplify   |   statusCode: 400,
amplify   |   retryable: false,
amplify   |   retryDelay: 26.121112361914378
amplify   | }
amplify   | Error while executing Local DynamoDB
amplify   | {
amplify   |     "version": "2018-05-29",
amplify   | 
amplify   |     "operation": "Query",
amplify   |     "limit": 10000,
amplify   |     "query": {
amplify   |         "expression": "#userAddress = :userAddress",
amplify   |         "expressionNames": {
amplify   |             "#userAddress": "userAddress"
amplify   |         },
amplify   |         "expressionValues": {
amplify   |             ":userAddress": {
amplify   |                 "S": "0xb77D57F4959eAfA0339424b83FcFaf9c15407461"
amplify   |             }
amplify   |         }
amplify   |     },
amplify   |     "index": "byUserAndColony",
amplify   |     "scanIndexForward": true,
amplify   |     "filter": {
amplify   |         "expression": "#colonyAddress = :colonyAddress_eq",
amplify   |         "expressionNames": {
amplify   |             "#colonyAddress": "colonyAddress"
amplify   |         },
amplify   |         "expressionValues": {
amplify   |             ":colonyAddress_eq": {
amplify   |                 "S": "0xdacd6A03Fe0e163454D71747F22A03503AA01F33"
amplify   |             }
amplify   |         }
amplify   |     }
amplify   | }
amplify   | ValidationException: Filter Expression can only contain non-primary key attributes: Primary key attribute: colonyAddress
amplify   |     at Request.extractError (/snapshot/repo/build/node_modules/aws-sdk/lib/protocol/json.js:52:27)
amplify   |     at Request.callListeners (/snapshot/repo/build/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
amplify   |     at Request.emit (/snapshot/repo/build/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
amplify   |     at Request.emit (/snapshot/repo/build/node_modules/aws-sdk/lib/request.js:686:14)
amplify   |     at Request.transition (/snapshot/repo/build/node_modules/aws-sdk/lib/request.js:22:10)
amplify   |     at AcceptorStateMachine.runTo (/snapshot/repo/build/node_modules/aws-sdk/lib/state_machine.js:14:12)
amplify   |     at /snapshot/repo/build/node_modules/aws-sdk/lib/state_machine.js:26:10
amplify   |     at Request.<anonymous> (/snapshot/repo/build/node_modules/aws-sdk/lib/request.js:38:9)
amplify   |     at Request.<anonymous> (/snapshot/repo/build/node_modules/aws-sdk/lib/request.js:688:12)
amplify   |     at Request.callListeners (/snapshot/repo/build/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
amplify   |     at Request.emit (/snapshot/repo/build/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
amplify   |     at Request.emit (/snapshot/repo/build/node_modules/aws-sdk/lib/request.js:686:14)
amplify   |     at Request.transition (/snapshot/repo/build/node_modules/aws-sdk/lib/request.js:22:10)
amplify   |     at AcceptorStateMachine.runTo (/snapshot/repo/build/node_modules/aws-sdk/lib/state_machine.js:14:12)
amplify   |     at /snapshot/repo/build/node_modules/aws-sdk/lib/state_machine.js:26:10
amplify   |     at Request.<anonymous> (/snapshot/repo/build/node_modules/aws-sdk/lib/request.js:38:9)
amplify   |     at Request.<anonymous> (/snapshot/repo/build/node_modules/aws-sdk/lib/request.js:688:12)
amplify   |     at Request.callListeners (/snapshot/repo/build/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
amplify   |     at callNextListener (/snapshot/repo/build/node_modules/aws-
amplify   | sdk/lib/sequential_executor.js:96:12)
amplify   |     at IncomingMessage.onEnd (/snapshot/repo/build/node_modules/aws-sdk/lib/event_listeners.js:380:13)
amplify   |     at IncomingMessage.emit (events.js:412:35)
amplify   |     at IncomingMessage.emit (domain.js:475:12)
amplify   |     at endReadableNT (internal/streams/readable.js:1333:12)
amplify   |     at processTicksAndRejections (internal/process/task_queues.js:82:21) {
amplify   |   code: 'ValidationException',
amplify   |   time: 2023-11-09T19:53:11.684Z,
amplify   |   requestId: '0de2d6f1-cc38-4077-8ac4-b7fa4cf3ce34',
amplify   |   statusCode: 400,
amplify   |   retryable: false,
amplify   |   retryDelay: 30.522964868510517
amplify   | }
```

I haven't been able to test if this happens on `master` in case it's just my environment as I don't see a way of activating the tokens there.

**Review by ArmandoGraterol — APPROVED** [review]
LGTM 👌 
Screenshot 2023-11-13 at 13 49 08

**Review by rdig — CHANGES_REQUESTED** [review]
Code wise this is all good, however functionally it still doesn't behave as expected. 

- "Claimed" doesn't show up after claiming a motion
- Claim all doesn't clear the list of "Claimable" motions
Screenshot from 2023-11-14 18-16-11
- "Claim all stakes" button is not wired up (or does not trigger)

**Review by rdig — APPROVED** [review]
Everything now works as expected. Nice flawless work :100:

**Review by arrenv — COMMENTED** [review]
@jakubcolony Functionally it works great. Nice work!

So, this can be in a more complete, is it worth removing the placeholder data, and pulling in the action titles?

**Review by ArmandoGraterol — APPROVED** [review]

**Pull request merged**
