### PR TITLE
fix: team purpose field text alignment

### PR DESCRIPTION
**Pull request by joanna-pagepro**
## Description

The team purpose field looked different in the edit and completed state. The text was aligned differently in both cases. Right now it should be top-aligned all the time.

## Testing

* Step 1. Create a `Create new team` action and add a text to the `team purpose` field that is longer than one line.
* Step 2. Submit the action and open the completed state.

## Diffs

**New stuff** ✨

* 

**Changes** 🏗

* `TeamPurpose` component with `subgrid`

**Deletions** ⚰️

* 

## TODO

Resolves https://github.com/JoinColony/colonyCDapp/issues/2285

### CODE REVIEW

**Review by melyndav — CHANGES_REQUESTED** [review]
Hey @joanna-pagepro - I tested this one out and in the completed state the team name is not returning a value and the purpose doesn't show at all.

image

**Review by ArmandoGraterol — COMMENTED** [review]
It is working for me thankfully 👌 
Screenshot 2024-05-06 at 16 58 34

**Review by ArmandoGraterol — APPROVED** [review]

**Comment by joanna-pagepro** [comment]
@melyndav can you share what data you entered in this form?

**Review by iamsamgibbs — APPROVED** [review]
Looks good to me! Team purpose alignment is correct on both 'new team' and 'edit team'.

Screenshot 2024-05-07 at 09 27 23

**Comment by melyndav** [comment]
> @melyndav can you share what data you entered in this form? If you don't add a team purpose text then it won't show later.

Hi Joanna, sorry I don't have the text saved anywhere. It was just a copy and paste. I will test this again and let you know if I can get the same error again.

**Review by melyndav — CHANGES_REQUESTED** [review]
I've tested this again and the data is now showing with no issues @joanna-pagepro. 

One minor fix is the padding between rows are not even anymore. They should match the other action types and be consistent. 

image

image

**Comment by joanna-pagepro** [comment]
@melyndav spacing updated. Is it ok now?

**Review by iamsamgibbs — APPROVED** [review]
Looks good!

Screenshot 2024-05-08 at 12 47 38

**Pull request merged**
