### PR TITLE
Motions UI fixes

### LINKED ISSUE #1479: Motions UI issues #3
## Description

When QA'ing motion flows, a number of UI issues have been identified that require fixing. These include: 

9. User-names should trigger a hover state & when selected, show the user pop-over in the staking information -
image

15. Top pill in the motion header is missing for passed and failed states.
image

Figma link passed: https://www.figma.com/file/5V8pr7iMwXsT9L3VAZsmUt/Colony-V5?type=design&node-id=3111-335567&mode=design&t=NYFSA78C4UJjlZY1-4

Figma link for failed: https://www.figma.com/file/5V8pr7iMwXsT9L3VAZsmUt/Colony-V5?type=design&node-id=14102-371050&mode=design&t=NYFSA78C4UJjlZY1-4

### PR DESCRIPTION
**Pull request by jakubcolony**
## Description

This PR fixes some outstanding issues with motions UI. I also got into refactoring mode (possibly a bit too much) so hovering around a nice 2/1 deletions/additions ratio.

## Testing

Please refer to the original issue. The refactoring bit is fairly well contained within the issue scope so you will also test it as you go through the issue.

## Diffs

**New stuff** ✨

* `MotionOutcomeBadge` component to display Passed/Failed states in the action sidebar header.

**Changes** 🏗

* Replaced super-complex `UserInfoSectionList` with a more concrete `StakesList` component, removed `useStakingInformation` hook.
* Moved `MotionBadge` to `Pills/MotionVoteBadge`, as it's a reusable component showing vote side.
* I made a small effort at clearing up the distinction between "network motion state" (number returned from the contracts) and "motion state" (extended version of motion state taking into consideration votes, stakes, etc.). This should be properly refactored at some point though.

Resolves #1479

### CODE REVIEW

**Review by rdig — CHANGES_REQUESTED** [review]
Code-wise nothing stands out. Nice work dealing with all the layers of abstraction :(

UI wise, I found some interactions, that I have some questions about.

### 1. The user popover initially looks cut, however you can scroll the height of it.
Screenshot from 2024-02-05 19-11-48

[Screencast from 2024-02-05 19-12-14.webm](https://github.com/JoinColony/colonyCDapp/assets/1193222/ecd4cd29-42f3-4b0b-8f3a-920fe4d8fc1f)

Although I'm not sure that case was covered in the designs, so maybe check with @melyndav 

### 2. The passed / failed pill is aligned to the right, while I saw the designs showing it aligned to the left

Screenshot from 2024-02-05 19-13-25

Wasn't it supposed to say `Support` / `Opposed` though ?

### 3. There's a loading state that always was showing next tot the "Reveal" step.

Screenshot from 2024-02-05 19-13-38

But that might just be me

### 4. On the "Reveal" step the user doesn't a have tooltip when you (try) to click on them

Screenshot from 2024-02-05 19-25-09
Screenshot from 2024-02-05 19-25-21

**Comment by jakubcolony** [comment]
Thanks for your reviews.

@rdig 

1) It's out of scope of this PR.

2) Figma shows the updated designs, great spot on the wrong side of the pill tho, that's fixed.

3) Another good catch, fixed.

4) Not specified by the issue but I agree it's the sensible thing to do so I implemented that as well.

@iamsamgibbs I checked `master` and the same issue as in your screenshot is present there, so it's not specific to this PR.

**Review by iamsamgibbs — APPROVED** [review]
Looks good to me! Points 2, 3 and 4 all resolved.

**Review by rdig — APPROVED** [review]
Tested and working as expected now. Nice work!

Screenshot from 2024-02-08 19-06-06
Screenshot from 2024-02-08 19-06-29

**Pull request merged**
