### PR TITLE
fix: changed failed finalize step content

### PR DESCRIPTION
**Pull request by CzarekDryl**
You should not be able to finalize a failed action.
You should be able to return stakes to users.

## Testing

- Ensure you have the Reputation extension installed with the testing configuration.
- Create an action using the Reputation decision method.
- Don't stake at all on the action.
- Allow the time to pass and the action to fail.

Resolves [https://github.com/JoinColony/colonyCDapp/issues/2165](https://github.com/JoinColony/colonyCDapp/issues/2165)

### CODE REVIEW

**Review by iamsamgibbs — CHANGES_REQUESTED** [review]
Good work on this ticket so far! It does resolve the issue you've described in the PR:

Screenshot 2024-04-15 at 16 29 27

But following the steps to reproduce in the original issue (#2172) (which includes staking both sides) I'm still experiencing the same issue:

Screenshot 2024-04-15 at 16 27 39

**Review by ArmandoGraterol — COMMENTED** [review]
Looking good! In my env, the case in the initial issue is not happening. I followed the steps however I was actually able to finalize and claim the stakes. The case in the PR's description is fixed for me too.

**Comment by CzarekDryl** [comment]
@iamsamgibbs @ArmandoGraterol My bad, I've linked wrong issue

**Review by iamsamgibbs — APPROVED** [review]
Ah okay! All good then in that case!

**Review by ArmandoGraterol — APPROVED** [review]
Looks good to me 👍 
Screenshot 2024-04-16 at 14 18 01

**Pull request merged**
