### PR TITLE
Fix[1875]: extension ui issues

### PR DESCRIPTION
**Pull request by KornelKwiatkowski**
## Description

Fixed issues with extension details UI:
- corrected color for "disabled" status
- changed columns gap

## Testing

The tests consist of checking whether the extension details section is compatible with Figma.

Instructions for testing this branch:

* Step 1. Go to extensions screen
* Step 2. Click "Manage" button for some extension 
* Step 3. Check if the "Extension details" section is compatible with Figma

## Diffs

**Changes** 🏗

Before:
image

After:
image

Resolves: https://github.com/JoinColony/colonyCDapp/issues/1869

### CODE REVIEW

**Review by melyndav — APPROVED** [review]

**Review by melyndav — CHANGES_REQUESTED** [review]
Hey @KornelKwiatkowski - thanks for picking up my issue.

Just noticed that with this pill change, it means when the deprecated pill is activated, there padding between the two pills. It's missing the 4px as per Figma.

Currently
image

Figma: 
image

Thanks!

**Review by iamsamgibbs — APPROVED** [review]
Looks good to me other than the issue Mel has already raised.

**Comment by KornelKwiatkowski** [comment]
@melyndav thanks for noticing that. It's fixed now :)

**Review by ArmandoGraterol — APPROVED** [review]
Good job 👍

**Review by melyndav — APPROVED** [review]
Perfect, thanks for fixing those two pills @KornelKwiatkowski!

**Pull request merged**
