### PR TITLE
Fix: disable multi-sig extension settings form if user is not owner

### LINKED ISSUE #2915: [Multi-sig] bug: users without Owner permissions can change multisig setup values and click Save settings
## Steps to reproduce

1. Assign `amy` `Admin` permissions (or none). 
2. Visit the multisig extension setup page
3. Observe that you can itneract with the form and click `Save settings`
image
4. The transaction fails, but the user shouldn't even be able to do this
image

## Expected behaviour

If a user doesn't have `Owner` permissions the form fields should be disabled and the `Save settings` button should either be disabled or not show up in the first place

## Actual behaviour

Users without permissions can interact with the page.

### PR DESCRIPTION
**Pull request by mmioana**
## Description

Users without Owner permissions shouldn't be able to change multi-sig extension settings

## Testing

Check multi-sig extension settings are disabled and Save settings button is not visible if user doesn't have owner permissions.

* Step 1. Install Multi-Sig extension as `leela`
* Step 2. Check 'Save settings' button is in place and settings options are enabled
* Step 3. Select `Fixed threshold` for Serenity and insert `3` approvals (please feel free to choose any other team but make sure to have at least one with a fixed threshold with a custom value)
Screenshot 2024-08-09 at 16 16 31
Screenshot 2024-08-09 at 16 16 40
* Step 4. In an incognito browser, connect as `amy`
* Step 5. Go to Admin > Extensions > Multi-sig Permissions > Extension settings tab
* Step 6. Check 'Save settings' button doesn't show up and all inputs are disabled
Screenshot 2024-08-09 at 16 17 01
Screenshot 2024-08-09 at 16 17 11
* Step 7. In the previous browser window connected as `leela` give `amy` Owner permissions (p.s. by the time I took the screenshot the data in the colony was lost)
Screenshot 2024-08-09 at 16 18 31
* Step 8. Refresh the incognito window and check if dear `amy` can now modify the extension settings
Screenshot 2024-08-09 at 16 19 02
* Step 9. After `amy` submits the new extension settings the transaction in the user hub should succeed
Screenshot 2024-08-09 at 16 40 50

**Changes** 🏗

* Multi-sig extension settings can be done only if user has Owner permissions

Resolves #2915

### CODE REVIEW

**Comment by mmioana** [comment]
Thank you @melyndav I'll update it asap 🙏 
Regarding the banner, that would actually be great!

**Comment by mmioana** [comment]
Okay, now the proper styling should be in place for the disabled state 🎉

**Comment by melyndav** [comment]
> Thank you @melyndav I'll update it asap 🙏 Regarding the banner, that would actually be great!

Thanks for updating the styling! :) I've created a sep issue for the banner with some design links #2922

**Review by iamsamgibbs — APPROVED** [review]
Nice job! All looking great now!

Screenshot 2024-08-12 at 16 02 47

**Review by Nortsova — APPROVED** [review]
Thanks @mmioana ! Great job! 👏

Can confirm that for Amy multi sig settings is disabled:
image
After giving an owner permission amy can change settings in MultiSig extension:
image
image

**Pull request merged**
