### PR TITLE
fix: spacings, skeleton overflow fix, actions table mobile styles

### PR DESCRIPTION
**Pull request by joanna-pagepro**
https://github.com/JoinColony/colonyCDapp/issues/1737
https://github.com/JoinColony/colonyCDapp/issues/1900
https://github.com/JoinColony/colonyCDapp/issues/1894

### CODE REVIEW

**Review by iamsamgibbs — CHANGES_REQUESTED** [review]
Great work @joanna-pagepro this is all looking very good. I've only noticed a couple of very minor things.

The activity feed on mobile, when an action is expanded, the gap between the text and the pills is too small.

Screenshot 2024-02-20 at 15 05 33

And on the dashboard on mobile, the gap between the icons and the first widget is too small (should be 36px)

Screenshot 2024-02-20 at 15 13 59

**Review by melyndav — CHANGES_REQUESTED** [review]
Hey @joanna-pagepro great work on a huge PR.

Some feedback:

### Activity feed:

1. The meatball menu should be blue when triggered in the open row.

image

2. Status is missing the sort arrow

image


3. There is some issues with the supported pill width

image

4. The skeleton on mobile is showing the blocks overlapping in the UI.

image

### Dashboard

5. The tablet size dashboard doesn't match the Figma design with the placement of the three left widgets, which causes the table to have issues.

image
 
 As per Figma at the 1024px breakpoint:
 
image

**Comment by joanna-pagepro** [comment]
@melyndav @iamsamgibbs please review again.
@melyndav sorting by status is not possible right now - https://github.com/JoinColony/colonyCDapp/pull/1384#issue-2006641308

**Review by iamsamgibbs — APPROVED** [review]
Thanks for the changes, this looks great. 👍

**Review by melyndav — APPROVED** [review]
Hey @joanna-pagepro appreciate all the updates and done so quickly, thank you! Everything looks good and I've noted to sort is outside scope, thanks!

**Pull request merged**
