### PR TITLE
fix: payment builder ui fixes part 1

### PR DESCRIPTION
**Pull request by CzarekDryl**
## Description

- Payment builder UI fixes, check issue for more details.

Resolves issues from 1 to 6 [https://github.com/JoinColony/colonyCDapp/issues/2255](https://github.com/JoinColony/colonyCDapp/issues/2255)

### CODE REVIEW

**Review by melyndav — CHANGES_REQUESTED** [review]
Hey @CzarekDryl appreciate you picking up this issue and making these fixes for the payment builder.

A couple of fixes needed.

1. The metadata in the default state still doesn't match the spec. It should read:
'Payment to multiple recipients by [username]'

Currently it's showing as this:
image

2. As requested in the original issue please r**emove** this tooltip, It's not correct and doesn't need to show. 

image

3. The CSV file is not renamed as requested in the original issue.

image

4. The error state is still not resolved as per the original issue
image

5. Metadata is still showing user icon
image

6. On the members  page, the user card widths have been impacted

image

 
 
 ** I will get you the correct pill styling for numver 7 from the origonal issue.

**Comment by CzarekDryl** [comment]
@melyndav 1. and 3. should be fixed. Adrian told us to split the main issue into several PRs for easier checking, this PR fixes bugs from 1 to 6.

**Review by melyndav — CHANGES_REQUESTED** [review]
Hey @CzarekDryl thanks, I noted the scope of the issue.

Everything looks good, just the only issue part of this PR scope is the validation keeps showing with browser styling and not the correct error styling.

image


Is there anything we can do for this? 

If I select the CTA with no entries, the correct validation shows. It just seems to be on the hours input:

image

**Comment by AdrianDudko** [comment]
Hey @melyndav 

The issue you are describing was already reported in [Point 11](https://github.com/JoinColony/colonyCDapp/issues/2255). of #2255 

@CzarekDryl will handle all remaining bugs in another PR. As he mentioned, this contains fixes for 1,2,3,4,5 and 6 of #2255 


> Hey @CzarekDryl thanks, I noted the scope of the issue.
> 
> Everything looks good, just the only issue part of this PR scope is the validation keeps showing with browser styling and not the correct error styling.
> 
> image
> Is there anything we can do for this?
> 
> If I select the CTA with no entries, the correct validation shows. It just seems to be on the hours input:
> 
> image

**Review by melyndav — APPROVED** [review]
Hey @CzarekDryl @AdrianDudko approving this one! It seems I couldn't read the numbers of my own issue and thought the hour validation was part of this issue, so I've removed my previous request. 😆

Also, number #11 is being noted here so it should be good to remove from part two of this issue if it's resolved by Joanna in this PR - https://github.com/JoinColony/colonyCDapp/pull/2435

**Pull request merged**
