### PR TITLE
feat: custom permissions tooltips

### PR DESCRIPTION
**Pull request by joanna-pagepro**
## Description

'Custom' permission option tooltips

## Testing

* Step 1. Open the action sidebar and select the `Manage permissions` action type
* Step 2. Select the `Custom` option in the `Permissions` field and check if all permission types have tooltips

## Diffs

**New stuff** ✨

* 

**Changes** 🏗

* `tooltipContent` field added to `CustomPermissionTableModel` interface and `Tooltip` component used in `useCustomPermissionsTableColumns` hook
* additionally - `withBorder={false}` set on `PermissionsTable` and the first column's size updated on mobile

**Deletions** ⚰️

* 

## TODO

- 

Resolves https://github.com/JoinColony/colonyCDapp/issues/2400

### CODE REVIEW

**Review by davecreaser — APPROVED** [review]
Screenshot 2024-06-07 at 18 00 54

All tooltips working as expected, and table still looks good on mobile. Good stuff!

**Review by iamsamgibbs — CHANGES_REQUESTED** [review]
Nice work on this!

Screenshot 2024-06-10 at 10 16 26

Only one small change, on mobile the point of the tooltip should be on the left as per the figma design:

Screenshot 2024-06-10 at 10 18 05

Screenshot 2024-06-10 at 10 18 27

Also, the tooltips aren't showing on the completed action, I think it would make sense for them to show there too.

Screenshot 2024-06-10 at 10 16 52

**Review by melyndav — CHANGES_REQUESTED** [review]
Hey @joanna-pagepro nice work on this. I have the same pick-ups as @iamsamgibbs for this.

**Comment by joanna-pagepro** [comment]
@melyndav @iamsamgibbs can you check if it's ok now?

**Review by iamsamgibbs — APPROVED** [review]
This looks good to me now, thanks for the changes!

Screenshot 2024-06-12 at 17 11 27

Screenshot 2024-06-12 at 17 12 02

**Review by rdig — APPROVED** [review]
Looks good from my end as well.

Here's some screenshots from testing this:

Screenshot from 2024-06-12 22-39-09
Screenshot from 2024-06-12 22-41-11

**Comment by rdig** [comment]
_PS: Ignore the artifacts on the first image, it's my rendering engine on the fritz_

**Review by melyndav — APPROVED** [review]
Nice work on wrapping this up @joanna-pagepro! Thanks for your work on this 🐰

**Pull request merged**
