### PR TITLE
Fix[15667228]: verified members table (fixes)

### PR DESCRIPTION
**Pull request by KornelKwiatkowski**
## Description

Task: https://tw.auroracreation.com/app/tasks/15667228

**Changes** 🏗

**Issues fixed in this PR:**
1. General users text should not show.
2. Permission pills having styling issues including wrong padding between icon and text and wrong colours used.
3. Down arrow on reputation column doesn't match Figma and doesn't work on first click.
4. Trash icons in far right column are wrong colour.
5. Usernames are not showing verified icons.
6. Usernames are not styled correctly to match Figma.
7. Empty space between the Members and the left side of the table should be removed.
8. Status pills have 8px padding and not 4px.

Before:

image

After:

image

### CODE REVIEW

**Review by jakubcolony — COMMENTED** [review]
Code looks good, but the user popover gets clipped by the navigation bar on the left sometimes:
image

**Review by rdig — DISMISSED** [review]

**Review by melyndav — CHANGES_REQUESTED** [review]
Hi @KornelKwiatkowski great start on this one.

A couple of changes needed:

1. Status pills are not correct. They have the wrong styling.
image

2. The star and trash icons are too big and don't account for the bounding box padding that's in Figma.
image

3. The row heights are not consistent with Figma. All tables across the site (outside of action tables) have a consistent row height.

image

3. For the reputation column width can we match figma for this?

image

4. Hover state is missing on trash icon.

**Review by arrenv — CHANGES_REQUESTED** [review]
Does this need to be rebased?

This has the menu back in:

image

It also has an issue in the action metadata with multiline:

image

**Comment by KornelKwiatkowski** [comment]
@melyndav thanks for the feedback. I fixed these issues :)

**Comment by KornelKwiatkowski** [comment]
Hi @arrenv, I have rebased this branch :)

**Review by melyndav — CHANGES_REQUESTED** [review]
Hey @KornelKwiatkowski great work on the updates. Just one more fix re: the icons. 

1. The star and trash icons are still to big. The figma sizes have a bounding box including in their sizing, and this is missing. So we need to adjust these icons size to match better with Figma. 

Figma:
image

2. Also just found an issue on the members page where it's showing double verified icons in your branch 
image

**Review by ArmandoGraterol — APPROVED** [review]
LGTM 👍

**Review by rdig — CHANGES_REQUESTED** [review]
Getting the same as Mel, the double verified icon. I've tested on `master` and it doesn't show up there, so it's definitely an issue on this branch specifically.

Screenshot from 2023-11-26 03-05-51

Screenshot from 2023-11-26 03-05-53
Screenshot from 2023-11-26 03-05-56

Other than that, all good.

**Comment by KornelKwiatkowski** [comment]
Hi @melyndav and @rdig.

_"1. The star and trash icons are still to big. The figma sizes have a bounding box including in their sizing, and this is missing. So we need to adjust these icons size to match better with Figma."_

I changed the icon implementation for this table. Now they are imported directly from the "phosphor-react" package. @arrenv asked to do this and now they should display fine :)

_"2. Also just found an issue on the members page where it's showing double verified icons in your branch"_

Nice pick up, fixed :)

**Review by melyndav — APPROVED** [review]
@KornelKwiatkowski I appreciate all your work on this PR. Thank you! :)

**Review by rdig — APPROVED** [review]
All good now.

However, be more descriptive with your commit messages. Your current pattern muddies the waters and makes it almost impossible to reason about the repo's history. Please improve this on future PRs/commits otherwise I'll be forced to stop approving them.

Screenshot from 2023-11-27 15-28-58

**Review by jakubcolony — APPROVED** [review]
LGTM 👍

**Review by arrenv — APPROVED** [review]
Looks like everything has been addressed, thanks @KornelKwiatkowski

**Review by TomaszChmielPagepro — APPROVED** [review]

**Pull request merged**
