### PR TITLE
fix: action header, buttons

### PR DESCRIPTION
**Pull request by CzarekDryl**
https://tw.auroracreation.com/app/tasks/15825815

## Description

- Fixed header and buttons in action sidebar on mobile
- draft agreement card line clamp

Resolves [https://github.com/JoinColony/colonyCDapp/issues/2027](https://github.com/JoinColony/colonyCDapp/issues/2027)

### CODE REVIEW

**Review by warrencolliver — APPROVED** [review]
All looks fine to me
Screenshot 2024-03-08 at 12 16 52

**Review by warrencolliver — CHANGES_REQUESTED** [review]
Just noticed these changes have changed the layout of the action type buttons on desktop (now on the left instead of the right)
Screenshot 2024-03-08 at 12 51 19

**Review by melyndav — CHANGES_REQUESTED** [review]
Hey @CzarekDryl thanks for picking up this issue quickly. I also see the issue @warrencolliver identified with the button placement, but the header looks to be correct now.

**Review by warrencolliver — APPROVED** [review]
The button position is now fixed - I can't see any other UI issues either. thanks for your work on this.

**Review by melyndav — APPROVED** [review]
Thanks @CzarekDryl looks better! Appreciate your work on this.

**Pull request merged**
