### PR TITLE
test: add e2e tests for 2nd step of create colony flow 

### PR DESCRIPTION
**Pull request by olgapod**
## Description

- Added e2e tests for the Create Colony flow / Details step
- Set up playwright eslint plugin

## Testing

**Prerequisites**: The test script simulates user interactions with the local instance of the web app, which means that the BE is expected to be set up and running. For now, backend services should be started manually and the initial test data should be seeded . Therefore, ensure that the development environment is properly set up by following the instructions in the README file

- Start your local dev environment  `npm run dev` 
- Seed the mock data `node scripts/create-data.js` 
- If it's the first time you run e2e tests on your machine - run `npm e2e:install` 

- run `npm run e2e` or `npm run e2e:ui`
- Ensure all tests pass

## Diffs

**New stuff** ✨

- playwright folder is added to the lint script
- added loading of the .env file into playwright environment

### CODE REVIEW

**Review by iamsamgibbs — APPROVED** [review]
Nice job! Tests are all passing for me.

Screenshot 2024-11-05 at 09 35 40

Screenshot 2024-11-05 at 09 38 43

**Review by rdig — APPROVED** [review]
All tests pass. Nicely done! 

However it seems to be quite slow to finish, but I'm guessing that because of all the timeouts.

I know they were needed to account for the various error everyone was seeing, but if we keep adding more tests this could spiral out of control.

Is there a way to cut down on the timeout, while still keeping the tests working ?

I'm thinking like shaving off one second here or there, rather than making any big or extreme changes in the timeouts

Screenshot from 2024-11-07 12-55-18

**Comment by olgapod** [comment]
> All tests pass. Nicely done!
> 
> However it seems to be quite slow to finish, but I'm guessing that because of all the timeouts.
> 
> I know they were needed to account for the various error everyone was seeing, but if we keep adding more tests this could spiral out of control.
> 
> Is there a way to cut down on the timeout, while still keeping the tests working ?
> 
> I'm thinking like shaving off one second here or there, rather than making any big or extreme changes in the timeouts
> 
> Screenshot from 2024-11-07 12-55-18


@rdig Yes sure there’s a way to speed up the tests: 1) run them against the  prod build 2) turn back on parallelisation

**Review by Nortsova — APPROVED** [review]
Nice work on this 👍 

image

It would be great to speed up the tests, I think we can create a separate issue for it 🙌

**Pull request merged**
