### PR TITLE
est: add e2e tests for final step of create colony flow 

### PR DESCRIPTION
**Pull request by olgapod**
## Description

- added e2e tests for the Create Colony flow
- enabled parallelization for tests of a single file
- use `fill` instead of `pressSequentially` to speed up the tests a bit

## Testing

**Prerequisites**: The test script simulates user interactions with the local instance of the web app, which means that the BE is expected to be set up and running. For now, backend services should be started manually and the initial test data should be seeded . Therefore, ensure that the development environment is properly set up by following the instructions in the README file

- Start your local dev environment  `npm run dev` 
- Seed the mock data `node scripts/create-data.js` 
- If it's the first time you run e2e tests on your machine - run `npm e2e:install` 

- run `npm run e2e` or `npm run e2e:ui`
- Ensure all tests pass (the 'should reject invalid colony name' test may intermittently fail due to the input validation issue described in #3565)

## Diffs

**New stuff** ✨

### CODE REVIEW

**Review by Nortsova — CHANGES_REQUESTED** [review]
Hey there! ✨ 

Nice work on this 👍 

However there is one test that failed:

image

I tested 10 times and 4 of them this test failed. 

Here is more info: 
image

image

I also checked our code base why it could happen and found this: 
image

It’s likely that the form was updated too quickly. If we can replicate it manually, then it’s a bug. :)

**Comment by olgapod** [comment]
> Hey there! ✨
> 
> Nice work on this 👍
> 
> However there is one test that failed:
> 
> image
> I tested 10 times and 4 of them this test failed.
> 
> Here is more info: image
> 
> image
> I also checked our code base why it could happen and found this: image
> 
> It’s likely that the form was updated too quickly. If we can replicate it manually, then it’s a bug. :)

it is actually expected the test to fail, as it's a bug that we have an issue for and that can be also reproduced manually https://github.com/JoinColony/colonyCDapp/issues/3565

**Review by iamsamgibbs — CHANGES_REQUESTED** [review]
Nice job! I am also having the same issue as @Nortsova but otherwise all testings are passing! (Am I remembering correctly that there was an issue raised recently with this? So maybe there is a legit issue here?)

Screenshot 2024-11-11 at 17 43 31

**Comment by iamsamgibbs** [comment]
Ah, literally as I was writing it up! I guess it is fine to approve this for now. It would be helpful to adjust the testing steps and mention if we are expecting a specific test to fail.

Also when this is merged, could you add a comment to that issue saying that the test should pass in order for that issue to be resolved.

**Review by Nortsova — APPROVED** [review]
Oh, okay! Great! Thank you for raising issue 🙌  I am approving in this case 🎉 

Great work 🦸‍♀️

**Pull request merged**
