### PR TITLE
fix: activity, balance, members table ui

### PR DESCRIPTION
**Pull request by CzarekDryl**
## Description
- Removed horizontal line on activity table on mobile
- Balance table issues on mobile

Resolves [https://github.com/JoinColony/colonyCDapp/issues/2134](https://github.com/JoinColony/colonyCDapp/issues/2134) and [https://github.com/JoinColony/colonyCDapp/issues/2135](https://github.com/JoinColony/colonyCDapp/issues/2135)

### CODE REVIEW

**Review by ArmandoGraterol — CHANGES_REQUESTED** [review]
The extra horizontal line is still on the activity feed of the homepage:

Screenshot 2024-04-09 at 14 57 04

Other than that, the rest of things in the issues seem to be fixed.

**Review by melyndav — CHANGES_REQUESTED** [review]
Same issue as @ArmandoGraterol raised, but everything else looks nice. Thanks for picking up the issues. 👍

**Comment by CzarekDryl** [comment]
@ArmandoGraterol @bassgeta @melyndav Fixed

**Review by ArmandoGraterol — APPROVED** [review]
Looking good to me now 🎉 

Screenshot 2024-04-10 at 14 57 00

**Review by bassgeta — APPROVED** [review]
LGTM :ship:

**Review by melyndav — APPROVED** [review]
Thanks for the fix on the dashboard @CzarekDryl, looks as it should now. Nice work!

**Pull request merged**
