### PR TITLE
Fix[15660303]: UserPopover - border

### PR DESCRIPTION
**Pull request by KornelKwiatkowski**
## Description

Task: https://tw.auroracreation.com/app/tasks/15660303

**Changes** 🏗

image

### CODE REVIEW

**Review by melyndav — CHANGES_REQUESTED** [review]
Hey @KornelKwiatkowski, thanks for your work on this PR so far.

The dropshadow is missing not just from this one but all of the popover variations.

**Comment by KornelKwiatkowski** [comment]
@melyndav fixed :)

**Review by rdig — APPROVED** [review]

**Review by TomaszChmielPagepro — APPROVED** [review]

**Review by rdig — CHANGES_REQUESTED** [review]
Top contributor background overlaps border

Screenshot from 2023-11-15 15-35-55
Screenshot from 2023-11-15 15-36-01
Screenshot from 2023-11-15 15-36-07

**Comment by KornelKwiatkowski** [comment]
Hi @rdig Are you sure you switched on this branch? I don't see the purple border that should appear for a member with status "top".

**Review by rdig — APPROVED** [review]
Yep, seems all good now

Screenshot from 2023-11-16 14-53-38

**Review by rdig — CHANGES_REQUESTED** [review]
Actually I was wrong with the initial approval.

Screenshot from 2023-11-16 14-53-38

- "About" section top margin is wrong
Screenshot from 2023-11-16 14-54-34

- Padding above "Team Breakdown" is too big
Screenshot from 2023-11-16 14-54-40

Also, please rebase this branch on the latest master, as it makes reviewing hard otherwise

**Comment by KornelKwiatkowski** [comment]
@rdig yup, you are right, but it's not related with this task :) And it's fixed here: https://github.com/JoinColony/colonyCDapp/pull/1326

**Review by melyndav — DISMISSED** [review]
Hey @KornelKwiatkowski I see three changes needed. Please let me know if any of these are not in the scope of the PR since it's hard to track what is included.

1. Padding above the 'about section' should be consistent with the padding from Figma.
2. The HR rule should not be full width.
3. The team pills - are these being updated as per Slack conversations with Adrian?

image

**Comment by KornelKwiatkowski** [comment]
@rdig You are right. The tasks were created in this order, and each task corresponds to one branch, so this is how it turned out. I admit that it could have been solved in one task :)

**Comment by KornelKwiatkowski** [comment]
Hi @melyndav 

_"1. Padding above the 'about section' should be consistent with the padding from Figma."_ - fixed here: https://github.com/JoinColony/colonyCDapp/pull/1326

_"2. The HR rule should not be full width."_ - fixed here: https://github.com/JoinColony/colonyCDapp/pull/1326

_"3. The team pills - are these being updated as per Slack conversations with Adrian?"_ - Adrian created a separated task for that: https://tw.auroracreation.com/app/tasks/15671662

**Comment by KornelKwiatkowski** [comment]
@melyndav I need you here :)

**Review by melyndav — APPROVED** [review]
Great work, approved. :)

**Pull request merged**
