### PR TITLE
fix: changed outcome pill colors

### PR DESCRIPTION
**Pull request by CzarekDryl**
## Description

- Changed colors of outcome pill

Resolves [https://github.com/JoinColony/colonyCDapp/issues/2056](https://github.com/JoinColony/colonyCDapp/issues/2056)

### CODE REVIEW

**Review by warrencolliver — APPROVED** [review]
Thanks for the change, can confirm the outcome pill now matches figma

**Review by melyndav — CHANGES_REQUESTED** [review]
Removing this comment as it was an issue with my dev. :)

**Comment by warrencolliver** [comment]
> Hey @CzarekDryl in the default state the colour is correct however, in the outcome state it's showing the wrong colour and outcome.
> 
> As you can see here, support won the vote but oppose is showing: image
> 
> And here the colour is red and showing oppose in the default state after voting: image

Just to add, this works for me
Screenshot 2024-03-18 at 15 55 26
Screenshot 2024-03-18 at 15 56 49

**Review by rdig — DISMISSED** [review]
Looks fine codewise

**Review by iamsamgibbs — DISMISSED** [review]
Looks good to me, not able to replicate the issue Mel is experiencing.

**Review by melyndav — COMMENTED** [review]
Hey @CzarekDryl looks like it's working fine now after re-testing this morning.

image


Are you able to resolve the hover state issues or is this out of scope?

**Comment by CzarekDryl** [comment]
@melyndav Sure, I will fix this in this PR

**Review by warrencolliver — APPROVED** [review]
Hover state for outcome pill looks good 
Screenshot 2024-03-19 at 12 02 19
Screenshot 2024-03-19 at 12 03 44

**Review by rdig — APPROVED** [review]
Re-approving so you can merge

**Review by melyndav — APPROVED** [review]
Thanks for that hover fix @CzarekDryl! Nice work on the PR. Approved 👍

**Review by rdig — APPROVED** [review]
Re-approving

**Review by melyndav — APPROVED** [review]
Reapproving @CzarekDryl 👍

**Pull request merged**
