### PR TITLE
fix: update get user query to be 'cache-first' to solve reloading issue

### LINKED ISSUE #2806: Activity feed loading on action panel opening
## Steps to reproduce

1. Ensure you have past activity in our colony.
2. Ensure your screen is wide enough to see the activity feed and open the action panel.
3. Open and close the action panel.
4. Note the activity feed and the skeleton loaders.

## Expected behaviour

* The already loaded activity feed items should not need to show the skeleton loaders every time you open the action panel.

## Actual behaviour

* The already loaded activity feed items show the skeleton loader whenever opening and closing the action panel.

activity-loading-action-panel

### PR DESCRIPTION
**Pull request by Nortsova**
## Description
Pairprogrammed it with @bassgeta. Thank you for your help :) 

### Before 
blick-before 

-------------- 

### Now
blick-now 

## Testing

1. Ensure you have past activity in our colony.
2. Ensure your screen is wide enough to see the activity feed and open the action panel.
3. Open and close the action panel.
4. Note the activity feed isn't blicking now.

Resolves #2806

### CODE REVIEW

**Comment by Nortsova** [comment]
This bug looks like a part of bigger issue: https://github.com/JoinColony/colonyCDapp/issues/3179

**Review by rdig — APPROVED** [review]
Nicely done! Tested and indeed it prevents the activity feed from re-rendering

Before:

https://github.com/user-attachments/assets/820d3b60-0dee-450f-b5cc-6456dd64007a

After:

https://github.com/user-attachments/assets/396fe0d4-cde9-4281-86a2-07952f2e7b5e

Also tested the "full page" activity feed:

https://github.com/user-attachments/assets/c4ffad68-d57a-4857-a3df-037bd73132cc

**Review by iamsamgibbs — APPROVED** [review]
Nice job, this is so much nicer now!

Dashboard:

https://github.com/user-attachments/assets/955e573c-7980-411d-acde-0c0e6e0f6620

Activity feed:

https://github.com/user-attachments/assets/23243dcc-2a67-4a87-80a0-998cae9b2e84

I did notice the motion timers get refreshed when opening the action sidebar, but this isn't a big deal:

https://github.com/user-attachments/assets/313089a9-5964-4e93-bd8a-e6fd86b6a3f5

**Review by bassgeta — APPROVED** [review]
So simple but so nice! I actually think it's how we should've written this hook in the first place since it's used in SO many places, poor network tab of our users, constantly spamming the BE :P 

https://github.com/user-attachments/assets/f289f5cd-89bf-4ebf-b436-f00ef5ba3f7d

**Pull request merged**
