### PR TITLE
fix: permissions type filtering, page layout

### PR DESCRIPTION
**Pull request by CzarekDryl**
## Description

- Added search by permission type to permissions filters
- Changed xl size so it starts at 1401

Resolves [https://github.com/JoinColony/colonyCDapp/issues/2051](https://github.com/JoinColony/colonyCDapp/issues/2051)

### CODE REVIEW

**Comment by rdig** [comment]
What's the issue that this PR is fixing ? 

As we have no reference on what we should look for when reviewing this PR

**Comment by CzarekDryl** [comment]
@rdig Issue added

**Review by melyndav — APPROVED** [review]
Hey @CzarekDryl from what I can see, both issues look to be resolved in this PR. Nice! 👍

**Review by warrencolliver — APPROVED** [review]
All looks good, and permissions filter search works fine
Screenshot 2024-03-15 at 12 06 47

**Pull request merged**
