### PR TITLE
Properly convert BigNumber values in Transaction params

### LINKED ISSUE #2976: Approving tokens for staking fails with non colony created tokens
## Steps to reproduce

1. Navigate to the Metacolony in production.
2. Open the UserHub.
3. In the Balance tab click the Activate button.
4. Try to activate some tokens.
5. Note the first transaction will fail.

Testing colony created native tokens is working fine.

It has worked for Shapeshift in the past with FOX, however, it is currently not working.

## Expected behaviour

* You should be able to approve and activate non colony created tokens in the Metacolony.

## Actual behaviour

* There is a transaction error when trying to approve and activate non colony created tokens for staking.

```
Send error: invalid BigNumber string (argument="value", value="[object Object]",
code=INVALID_ARGUMENT, version=bignumber/5.7.0)
```

image

### PR DESCRIPTION
**Pull request by rdig**
This PR fixes a very serious issue that was introduced by #2127, however a issue that is very hard to stop since it happens in a very specific, and hard to reproduce state.

The issue at hand was that BigNumber instances _(Class objects)_ now get saved in the database. Since GraphQL only supports [Scalar](https://graphql.org/learn/schema/#scalar-types) types, any object, or object like shape will get converted to a `string` via `JSON.stringify()`. This will make the object lose it's inherited props and values.

Upon fetching the transaction data back into the client, even though `JSON.parse()` was run on these values, it couldn't recreate the original BigNumbers Class instance, but rather an sparsely similar object.

Screenshot from 2024-08-22 15-55-01
Screenshot from 2024-08-22 15-55-55

Since there is a `.toString()` call on all standard Javascript objects, calling that actually works, however it justs returns the `string` `'[object Object]'`, where as `BigNumber` overwrites this method with a custom one, that will parse the instanced value and return a numeric value, in the form of a `string`

Screenshot from 2024-08-22 15-59-38

Due to this, in #2976 when a very specific set of circumstances would happen, Metatransactions enabled, contract being run was `TokenClient`, method called was `approve`, and the underlying token that the client instantiated was a version that supported only [`EIP2616`](https://eips.ethereum.org/EIPS/eip-2612) flavored Metatransactions, a BigNumber-like object would get `.toString()` called on it, setting in motion the effect I described above.

## Testing

Actual testing cannot be done locally, since we lack the specific legacy contracts, states and environment found in production, however, we can simulate that state easy enough.

First we're going to start by replicating the issue locally, then using the fix to ensure it properly works.

### Prerequisites 

1. Ensure your dev environment is running
2. Ensure you ran the `create-data` script
3. Ensure you've started your frontend
4. Ensure you connected your **Metamask** wallet _(don't worry about mismatched nonces, you will only sign with it)_
5. Ensure your Metamask wallet is connected to your local network
6. Enable metatransactions for your user _(`leela` assuming you connected the first dev wallet via Metamask)_

### Simulate the issue

7. Apply this patch by running: `git apply <filename>`
```diff
diff --git a/src/redux/sagas/transactions/getMetatransactionPromise.ts b/src/redux/sagas/transactions/getMetatransactionPromise.ts
index 66c0c20fd..70110a6aa 100644
--- a/src/redux/sagas/transactions/getMetatransactionPromise.ts
+++ b/src/redux/sagas/transactions/getMetatransactionPromise.ts
@@ -158,6 +158,9 @@ async function getMetatransactionPromise(
    * TokenClient.approve method, every other call needs to go through
    * vanilla metatransactions
    */
+
+  lightTokenClient.metatransactionVariation = MetatransactionFlavour.EIP2612;
+
   if (
     normalizedClient.clientType === ClientType.TokenClient &&
     lightTokenClient.metatransactionVariation ===
@@ -166,7 +169,7 @@ async function getMetatransactionPromise(
   ) {
     const tokenName = await normalizedClient.name();
     const [spender, amount] = params;
-    const deadline = Math.floor(Date.now() / 1000) + 3600;
+    const deadline = Math.floor(Date.now() / 1000) + 3600 * 24 * 365 * 2;
 
     try {
       const { r, s, v } = await signTypedData(
@@ -203,6 +206,7 @@ async function getMetatransactionPromise(
       throw new Error(error.message);
     }
   } else {
+    console.log({ normalizedParams });
     const encodedTransaction =
       await normalizedClient.interface.encodeFunctionData(
         normalizedMethodName,
diff --git a/src/state/transactionState.ts b/src/state/transactionState.ts
index aac68fbf4..81300667f 100644
--- a/src/state/transactionState.ts
+++ b/src/state/transactionState.ts
@@ -75,22 +75,6 @@ export const convertTransactionType = ({
     titleValues: group.titleValues ? JSON.parse(group.titleValues) : undefined,
   };
 
-  const convertedParams = JSON.parse(params ?? '[]').map((param) => {
-    // @NOTE Try to convert BigNumber params back to Ethers BigNumber
-    //
-    // When the transaction gets saved in the database, the BigNumber objects get stringified
-    // meaning it will loose its BigNumber properties and prototypes
-    // Converting it back will create an Object shaped like a BigNumber, but it won't have the prototype, hence
-    // it won't be a proper BigNumber object, and won't have the methods like add, sub, etc.
-    //
-    // Here we're trying to convert it back to a Ethers BigNumber object by "trying to be smart" and checking if
-    // the object has a "tyhpe" property, with the value "BigNumber" (which is what Ethers uses), as well as a "hex" property
-    if (param?.type === 'BigNumber' && param?.hex) {
-      return BigNumber.from(param);
-    }
-    return param;
-  });
-
   return {
     context: context as ClientTypeTokens | ExtendedClientType,
     createdAt: new Date(createdAt),
@@ -104,7 +88,7 @@ export const convertTransactionType = ({
     groupId,
     hash: hash || '0x0',
     methodContext: methodContext ?? undefined,
-    params: convertedParams,
+    params: JSON.parse(params ?? '[]'),
     title: title ? JSON.parse(title) : undefined,
     titleValues: titleValues ? JSON.parse(titleValues) : undefined,
     options: options ? JSON.parse(options) : undefined,
```
8. Using the User Hub, enable some tokens
Screenshot from 2024-08-22 16-06-07
Screenshot from 2024-08-22 16-06-18
Screenshot from 2024-08-22 16-11-28
- **Ensure** you get an error like this, meaning you successfully replicated the initial issue
Screenshot from 2024-08-22 16-11-39

### Test the fix

9. Restore changes to the `transactionState.ts` file only! by running `git restore src/state/transactionState.ts`. **Be careful not to restore the other file as well**. Doing so will leave you in a broken state, unable to sign transactions _(and you'll have to re-start the testing procedure)_
10. Using the User Hub, enable some tokens
Screenshot from 2024-08-22 16-06-07
Screenshot from 2024-08-22 16-06-18
Screenshot from 2024-08-22 16-11-28
- **Ensure** you don't get an error, meaning you've successfully approved your tokens, by using the correct `BigNumber` instance
Screenshot from 2024-08-22 16-18-48
11. By this stage you've tested everything and ensured it works. Make sure to clean up all other modified file(s) that were used to test this.

### Notes

Due to this being a timely matter, the current fix is already deployed in production via https://github.com/JoinColony/colonyCDapp/actions/runs/10508038523

Resolves #2976

### CODE REVIEW

**Review by mmioana — APPROVED** [review]
Really cool fix @rdig 🥇 

Tested following your provided steps and can confirm it works

Enabled metatransactions
Screenshot 2024-08-23 at 08 54 54

Applied the patches
Screenshot 2024-08-23 at 08 58 57
Screenshot 2024-08-23 at 09 00 16
Screenshot 2024-08-23 at 09 00 44

Failed activating the token
Screenshot 2024-08-23 at 09 01 10
Screenshot 2024-08-23 at 09 01 33
Screenshot 2024-08-23 at 09 02 08

Discarded the patch and managed to activate the token
Screenshot 2024-08-23 at 09 02 42
Screenshot 2024-08-23 at 09 03 01
Screenshot 2024-08-23 at 09 03 16
Screenshot 2024-08-23 at 09 03 26

The only thing I have noticed while testing this fix is the uncontrolled input error in the `Activate tokens for decision making` modal 😢 but maybe it makes sense to be tackled in a separate issue

Screenshot 2024-08-23 at 09 09 21

**Review by bassgeta — APPROVED** [review]
Tried out the testing steps, and it works as you've described it, nice find and nice fix!
Error while activating the tokens:
image
And after resetting that, I am able to activate the tokens :heavy_check_mark: 
image

**Review by rumzledz — APPROVED** [review]
All good on my end @rdig 💯 Although I did have to "unlock" the CREDS token first prior to activating some tokens, as prompted here:

image

| Before fix | After fix |
| ---- | ---- |
| 2976 fail | 2876 pass |

image

**Comment by rdig** [comment]
Good pickup @rumzledz I forgot to mention in my testing steps that your token needs to be unlocked.

**Pull request merged**
