### PR TITLE
fix: make colony switcher the same height as sidebar

### LINKED ISSUE #3469: Colony picker overlaps over header calamity banner
## Steps to reproduce

1. Ensure the calamity banner is showing, e.g. upgrade a colony.
2. Click on the colony picker.
3. Note the alignment of the colony picker popup.

## Expected behaviour

* The colony picker should be inline with the button.

## Actual behaviour

* The colony picker is sitting over the header calamity banner.

image

### LINKED ISSUE #3470: Colony picker height is cut off
## Steps to reproduce

1. Ensure you have more then 10 colonies joined.
2. Click on the colony picker.
3. Note the colony picker height.

## Expected behaviour

* The colony picker should dynamically fill to match the height of the menu based on number of colonies before requiring scroll.

## Actual behaviour

* The colony picker height is cut off halfway in the screen.

image

### PR DESCRIPTION
**Pull request by Nortsova**
## Description
Adjust the height of the Colony Switcher to match the sidebar.

image

## Testing
Step 1. Open Planet Express colony
Step 2. Press "Planet Express" to open Colony Switcher
Step 3. Verify that the Colony Switcher appears as expected 😄 :
image

Step 4. Apply the following .diff file:

> [!TIP]
> Save this code to a .diff file in the root directory, then apply it by running `git apply .diff` in the terminal.

```
diff --git a/src/components/frame/Extensions/layouts/ColonyLayout.tsx b/src/components/frame/Extensions/layouts/ColonyLayout.tsx
index 9dee9daf5..918523ca9 100644
--- a/src/components/frame/Extensions/layouts/ColonyLayout.tsx
+++ b/src/components/frame/Extensions/layouts/ColonyLayout.tsx
@@ -156,9 +156,7 @@ const ColonyLayout: FC<PropsWithChildren> = ({ children }) => {
     <>
       <PageLayout
         topContent={
-          canUpgrade ? (
-            <CalamityBanner items={calamityBannerItems} />
-          ) : undefined
+          true ? <CalamityBanner items={calamityBannerItems} /> : undefined
         }
         headerProps={{
           /** @TODO: Move this inside the Header component */
diff --git a/src/components/v5/shared/Navigation/ColonySwitcher/partials/JoinedColoniesList.tsx b/src/components/v5/shared/Navigation/ColonySwitcher/partials/JoinedColoniesList.tsx
index c2a0edaf0..dc273ca03 100644
--- a/src/components/v5/shared/Navigation/ColonySwitcher/partials/JoinedColoniesList.tsx
+++ b/src/components/v5/shared/Navigation/ColonySwitcher/partials/JoinedColoniesList.tsx
@@ -40,34 +40,49 @@ export const JoinedColoniesList = ({
 
   return hasJoinedColonies ? (
     <div className="flex flex-col gap-1.5 overflow-y-auto px-2 pt-2">
-      {joinedColonies.map(
-        ({ colonyAddress, metadata, name, nativeToken }, index) => {
-          const isActiveColony = colonyContext?.colony.name === name;
+      {[
+        ...joinedColonies,
+        ...joinedColonies,
+        ...joinedColonies,
+        ...joinedColonies,
+        ...joinedColonies,
+        ...joinedColonies,
+        ...joinedColonies,
+        ...joinedColonies,
+        ...joinedColonies,
+        ...joinedColonies,
+        ...joinedColonies,
+        ...joinedColonies,
+        ...joinedColonies,
+        ...joinedColonies,
+        ...joinedColonies,
+        ...joinedColonies,
+      ].map(({ colonyAddress, metadata, name, nativeToken }, index) => {
+        const isActiveColony = colonyContext?.colony.name === name;
 
-          return (
-            <Fragment key={colonyAddress}>
-              <JoinedColonyItem
-                colonyAddress={colonyAddress}
-                metadata={metadata}
-                name={name}
-                onClick={handleColonyClick}
-                tokenSymbol={nativeToken.symbol}
-                isActiveColony={isActiveColony}
-                enableMobileAndDesktopLayoutBreakpoints={
-                  enableMobileAndDesktopLayoutBreakpoints
-                }
+        return (
+          <Fragment key={colonyAddress}>
+            <JoinedColonyItem
+              colonyAddress={colonyAddress}
+              metadata={metadata}
+              name={name}
+              onClick={handleColonyClick}
+              tokenSymbol={nativeToken.symbol}
+              isActiveColony={isActiveColony}
+              enableMobileAndDesktopLayoutBreakpoints={
+                enableMobileAndDesktopLayoutBreakpoints
+              }
+            />
+            {index < joinedColonies.length * 16 - 1 && (
+              <hr
+                className={clsx('mx-4 border-gray-200 md:mx-2', {
+                  'sm:mx-2': enableMobileAndDesktopLayoutBreakpoints,
+                })}
               />
-              {index < joinedColonies.length - 1 && (
-                <hr
-                  className={clsx('mx-4 border-gray-200 md:mx-2', {
-                    'sm:mx-2': enableMobileAndDesktopLayoutBreakpoints,
-                  })}
-                />
-              )}
-            </Fragment>
-          );
-        },
-      )}
+            )}
+          </Fragment>
+        );
+      })}
     </div>
   ) : (
     <div className="p-6 md:px-4 md:pb-0 md:pt-4">

```

Step 5. Reopen the Colony Switcher.
Step 6.Verify the Colony Switcher alignment:
image

Step 7. Close the "A new version of the Colony Network is available!" notification.
Step 8. Verify that the tooltip height matches the sidebar:
image

> [!NOTE]  
> If the "new version" notification disappears due to localStorage settings, remove the "calamity-banner" entry from localStorage or clear the storage.  🙌 

Resolves #3469
Resolves #3470

### CODE REVIEW

**Review by iamsamgibbs — CHANGES_REQUESTED** [review]
Nice work on this!
 
Screenshot 2024-11-04 at 12 01 12

Still works when there are not enough colonies to fill the page:

Screenshot 2024-11-04 at 12 01 39

And when the banner is dismissed:

Screenshot 2024-11-04 at 12 04 22

The only issue I've noticed is when the page height is short and requires the navigation to scroll. The gap between the navigation and the colony switcher disappears. Then when you scroll the menu, the team switcher scrolls off the page.

https://github.com/user-attachments/assets/8bcb6436-c8d6-4135-ab3b-f557abf8bee2

This issue is occurring on master, so if you'd rather we made a new issue, I can switch this to an approval, but I imagine it would involve reworking the changes you've made here anyway, so if it's possible to fix as part of this PR that would be great!

**Comment by Nortsova** [comment]
Hey @iamsamgibbs, thank you for testing 🙌  
This tooltip is hardly customizable, so I ended up with styles 😄 

It should works now: 
tooltip-scroll

**Review by iamsamgibbs — APPROVED** [review]
Nice job fixing this up! It's working now in every test case I can think of.

Scrolled with banner:
Screenshot 2024-11-07 at 13 34 00

Screenshot 2024-11-07 at 13 29 24

Screenshot 2024-11-07 at 13 32 28

**Review by rumzledz — APPROVED** [review]
Awesome awesome awesome work on this @Nortsova! Looks like you really got to know the Colony Switcher component 😂 Really neat changes as well, I'm glad the required changes aren't too convoluted but I imagine the debugging process to be headache-inducing!

colony-switcher

**Review by bassgeta — APPROVED** [review]
Nice solution and great testing steps, thanks for the diff with a million colonies :D 
image

**Pull request merged**
