### PR TITLE
Refactor input width adjustment logic in

### PR DESCRIPTION
**Pull request by TomaszChmielPagepro**
image

https://tw.auroracreation.com/app/tasks/15639275

### CODE REVIEW

**Review by KornelKwiatkowski — DISMISSED** [review]

**Review by arrenv — CHANGES_REQUESTED** [review]
This is breaking changes that I added in this PR https://github.com/JoinColony/colonyCDapp/pull/1242:


This is what I see in this PR:

image

image


This is master:

image

**Comment by TomaszChmielPagepro** [comment]
@arrenv Should be good now

**Review by KornelKwiatkowski — DISMISSED** [review]

**Review by joanna-pagepro — DISMISSED** [review]

**Review by arrenv — CHANGES_REQUESTED** [review]
@TomaszChmielPagepro This still re-introduces a bug I resolved. When typing letters the input width breaks (see gif). I added string regex to the width calculation.

type-letter

**Review by ArmandoGraterol — COMMENTED** [review]
I've noticed a small detail and is that now the input looks like it jumps slightly back before going forward again? 

[3aa7d73a-e4bf-4f43-95d7-5c8ceae837b8.webm](https://github.com/JoinColony/colonyCDapp/assets/18473896/abd7d846-8577-474c-9db2-1862ffec10d4)

At least in comparison with master, it looks like it's doing that, on master the input doesn't seem to be jumping around the same way:

[c90426b5-4b50-427b-86c3-6d862d08e1a5.webm](https://github.com/JoinColony/colonyCDapp/assets/18473896/7e3713fd-7218-4de7-85a9-2f367a5e41db)

**Comment by TomaszChmielPagepro** [comment]
@arrenv @ArmandoGraterol I see it now, It's not noticeable for me on my machine, I will fix this

**Comment by TomaszChmielPagepro** [comment]
I have removed the state for input width and moved width adjustment to onChange, works fine on my side. Can you take a look? @arrenv @ArmandoGraterol 

https://github.com/JoinColony/colonyCDapp/assets/38806520/edcef2e4-5e41-41da-93fb-d7f67fb22e08

**Review by ArmandoGraterol — DISMISSED** [review]
Good one! The input is looking much better 👍  Less janky

**Review by arrenv — CHANGES_REQUESTED** [review]
@TomaszChmielPagepro I am now getting this width issue on the tables. This is on Advanced payment as default.


image

**Review by arrenv — APPROVED** [review]
Working great now, thanks for working through this one @TomaszChmielPagepro

**Review by KornelKwiatkowski — APPROVED** [review]

**Pull request merged**
