### PR TITLE
[Navigation] Fix: UI Page header adjustments

### LINKED ISSUE #3047: [New Navigation] PageHeader Component UI Adustments
## Issues

* [ ] Issue 1
Image

* [ ] Issue 2
Image

### PR DESCRIPTION
**Pull request by iamsamgibbs**
## Description

This PR makes two small fixes to the page header on mobile. The space between the colony logo and the menu icon has been increased. The width of the settings button has been increased to match the other icon buttons ~~(note: this does not match the figma design which has the borders on the inside of the component rather than the outside, so I have instead opted to make this consistent with the other two buttons as this would be a bigger change that needs a bit more thought)~~ I did a bit of digging found this was only an issue with these buttons, so have gone ahead and made the changes.

Before:
Screenshot 2024-09-11 at 09 51 03

After:

Screenshot 2024-09-12 at 14 30 15

Screenshot 2024-09-12 at 14 50 34

Screenshot 2024-09-12 at 14 30 30

## Testing

Does the spacing match the figma design.
Does the settings button match the other buttons.

## Diffs

**Changes** 🏗

* Increased spacing
* Increased width

Resolves #3047

### CODE REVIEW

**Review by mmioana — APPROVED** [review]
Nice and simple fixes @iamsamgibbs 💯 Great job!

Screenshot 2024-09-11 at 13 16 57
Screenshot 2024-09-11 at 13 17 10

**Review by rdig — APPROVED** [review]
Looks good here. Nice quick change!

Screenshot from 2024-09-12 13-24-51
Screenshot from 2024-09-12 13-25-05

**Review by rumzledz — APPROVED** [review]
Bish bash bosh! Yet another one finessed ✨ I can confirm that the 24px (gap-6) style has been applied and the buttons all look good now! Thanks for this @iamsamgibbs 

Screenshot 2024-09-13 at 01 13 06

**Comment by rdig** [comment]
> Bish bash bosh!

I only know of this expression from Counter Strike :)

**Pull request merged**
