### PR TITLE
Fix: Status of fund expenditure motion stake being always "Staking"

### PR DESCRIPTION
**Pull request by jakubcolony**
## Description

While reviewing #2772, I came across a bug where status of stakes made on fund expenditure motions (and any other expenditure related motions) would always get overwritten to `Staking`. This PR fixes the problem by checking the type of the stake when determining the status.

## Testing

To replicate the original issue:
- Checkout `feat/advanced-payments-ui`.
- Install voting reputation extension.
- Create an advanced payment. Fund it via a motion.
- Fully stake the motion. Run `npm run forward-time 1` to pass the staking period.
- Check the stake status in the user hub. It shows as `Staking` instead of `Finalizable`: 
image

On this branch, the status should show correctly:
image
Once you finalize the motion, the status should update to Claimable.

### CODE REVIEW

**Review by Nortsova — APPROVED** [review]
Hey @jakubcolony ! Thanks for this fix! ✨

I can confirm that the Finalizable and Claimable statuses are shown correctly.
image
image

**Comment by rdig** [comment]
Can you rebase this @jakubcolony when you get a chance ?

**Comment by jakubcolony** [comment]
@rdig rebase done

**Review by iamsamgibbs — APPROVED** [review]
Nice fix Jakub, was able to reproduce the issue on the advanced-payments-ui branch:

Screenshot 2024-08-06 at 10 20 11

And can see it is resolved here:

Screenshot 2024-08-06 at 10 20 40

**Review by mmioana — APPROVED** [review]
Nice work on this one @jakubcolony 🎉 Can confirm the right status is showing up with this PR

On `feat/advanced-payments-ui`
Screenshot 2024-08-14 at 11 37 04
Screenshot 2024-08-14 at 11 37 45

While on `fix/stake-status`
Screenshot 2024-08-14 at 11 38 08
Screenshot 2024-08-14 at 11 38 29

**Pull request merged**
