### PR TITLE
Fix[15661617]: add horizontal line to verified members table

### PR DESCRIPTION
**Pull request by KornelKwiatkowski**
## Description

Task: https://tw.auroracreation.com/app/tasks/15661617

**Changes** 🏗

before:

image

after:

image

### CODE REVIEW

**Review by rdig — DISMISSED** [review]

**Review by melyndav — CHANGES_REQUESTED** [review]
Hi @KornelKwiatkowski,

The HR is the wrong colour. Could you update this?

**Comment by KornelKwiatkowski** [comment]
@melyndav fixed :)

**Review by arrenv — APPROVED** [review]
Showing the correct color now. Thank you!

**Review by melyndav — APPROVED** [review]
@KornelKwiatkowski thanks for the update, this is approved.

**Pull request merged**
