### PR TITLE
Maintenance: Remove Colony Objective widget and remove functionality to manage Colony objectives

### LINKED ISSUE #2797: Remove 'Manage objective' from app
## Description

This issue involves the removal of the 'Manage objective' action and widgets from the app. The activity feed history should remain, and opening up the activity feed transactions should still open it up in the action panel, however, we should no longer show the widgets and also prevent the creation of new 'Manage objective' actions from the action panel.

## Background

The Manage objective feature was added as an initial trial to help with aligning a decentralised team to a common objective, while we still think this is a good idea and the feature will return in future, we feel it is not comprehensive enough at the moment to provide a lot of value and also does not align with our current focus.

Additionally, there is currently an issue in the Manage colony objective where if you use Reputation, the completed action screen shows up as Permissions was used, but the action itself does not get executed as it is still in fact created as a motion, just without the motion stages UI. So, instead of fixing this, we may as well just remove the feature for now.

## Design
- Figma design - [Dashboard without agreement widget](https://www.figma.com/design/gac6xVgGNCAge5Bia933dp/Dashboard?node-id=5477-11376&t=ogK9aglVyL4QYeCZ-4)

image

## Acceptance criteria
- The "Current Colony Objective" widget is removed from Dashboard/Home.
- The "Current Colony Objective" widget is removed from Colony details page.
- "Manage objective" option is removed from the action creator.
- Historic Manage objective actions in the activity feed are still visible and open the respective action.

### PR DESCRIPTION
**Pull request by rumzledz**
## Description

remove-col-objectives

## Testing

> [!IMPORTANT]
> Check out to another branch and create a Manage Objective action then come back to this branch once that's done.

### Testing steps
1. Please verify that you are no longer able to view the Colony Objectives widget from:
  - Dashboard: `/{colony}`
  - Colony Details page: `/{colonyName}/details`
2. Verify that the Manage Colony Objectives option is not present in the Action Sidebar's Action type field
3. Go to your Dashboard
4. Observe the Latest activity table
5. Verify that the copy for "Manage objective by {user}" is still in tact
6. Filter the activity table using the Colony Objective Action type
7. Verify that the Colony Objective Actions are correctly being filtered
8. Click this Colony Objective Action
9. Verify that the Completed Action form comes up and shows you the details for the Manage objective action
10. On the Completed Action form, verify that the copy for "Manage objective by {user}" is still in tact
11. Open the UserHub and go to the Transactions Tab
12. Verify that you can still see the Edit Colony Details and the copy is in tact
13. Click Edit Colony Details
14. Verify that the Completed Action form comes up and shows you the details for the Manage objective action

Resolves #2797

### CODE REVIEW

**Review by rdig — CHANGES_REQUESTED** [review]
Did a code review only, and seems all fine.

However this has yet to remove the `ColonyObjective` type, it's relationship to `ColonyMetadata`, as well as the graphql fragment.

I will do a functional review once those have been removed.

**Review by rdig — APPROVED** [review]
You are correct for leaving the Object data in, it was my oversight. Nicely done. 

I've tested the UI and everything seems to (not be) showing up, no errors in the console, so I consider this all good.

Screenshot from 2024-08-22 17-48-25
Screenshot from 2024-08-22 17-48-30
Screenshot from 2024-08-22 17-48-40
Screenshot from 2024-08-22 17-48-53
Screenshot from 2024-08-22 17-48-58
Screenshot from 2024-08-22 17-49-31
Screenshot from 2024-08-22 17-50-32

**Review by iamsamgibbs — APPROVED** [review]
Nice job, followed all the testing steps without issue!

Master:

Screenshot 2024-08-30 at 11 06 15

This branch:

Screenshot 2024-08-30 at 11 06 32

Master:

Screenshot 2024-08-30 at 11 09 03

This branch:

Screenshot 2024-08-30 at 11 06 52

No longer in the actions list:

Screenshot 2024-08-30 at 11 07 07

Activity feed:

Screenshot 2024-08-30 at 11 23 35

Transaction tab:

Screenshot 2024-08-30 at 11 23 59

Completed action:

Screenshot 2024-08-30 at 11 21 19

Good job!

**Review by davecreaser — APPROVED** [review]
Nice cleanup @rumzledz, waving goodbye to objectives 👋 

Tested via your steps and everything looks correct:
Screenshot 2024-09-02 at 13 41 09
Screenshot 2024-09-02 at 13 43 03
Screenshot 2024-09-02 at 13 43 15
Screenshot 2024-09-02 at 13 43 26
Screenshot 2024-09-02 at 13 43 45
Screenshot 2024-09-02 at 13 44 10
Screenshot 2024-09-02 at 13 44 36
Screenshot 2024-09-02 at 13 45 13

**Pull request merged**
