### PR TITLE
fix: add bottom paddings for 'filter & sort' modal

### LINKED ISSUE #2698: [Multi-sig] Mobile scrollable modals don't have bottom padding
## Steps to reproduce

1. Try to open a filter & sort modal
Screenshot 2024-07-12 at 08 21 10

Screenshot 2024-07-12 at 12 07 35

2. The content of the modal scrolls from the very bottom border of the modal

## Expected behaviour

* The modal should show a bottom padding when content is scrollable

## Actual behaviour

* The modal has no bottom padding when content is scrollable

## Suggestions 

* You can use the `withPaddingBottom` when instantiating a Modal component. However content must be updated to not have an extra bottom padding

### PR DESCRIPTION
**Pull request by Nortsova**
## Description
| Before | After |
| ----- | ----- |
|  image | image |

## Testing
Step 1. Set the screen size to mobile.
Step 2. Open Members or Contributors Page - http://localhost:9091/planex/members 
Step 3. Open filters modal
Step 4. Ensure that Modal has padding bottom
image

## NEW pages to check:
- http://localhost:9091/planex/activity (filter, search modal)
- http://localhost:9091/planex/permissions (filter, search modal)
- http://localhost:9091/planex/teams (filter, search modal)
- http://localhost:9091/planex/agreements (filter, search modal)
- http://localhost:9091/planex/balances (filter, search modal)
- http://localhost:9091/planex/incoming (filter, search modal)
- http://localhost:9091/planex/members (filter, search modal)
- http://localhost:9091/account/crypto-to-fiat (Verification Modal, Bank details Modal)

Resolves  #2698

### CODE REVIEW

**Review by rumzledz — CHANGES_REQUESTED** [review]
Hey @Nortsova I noticed that although this prop correctly sets the required bottom padding, it seems to be conflicting with another padding property being set inside the modal:

Bottom padding is sorted ✨  

Screenshot 2024-09-18 at 22 32 24

But the new padding introduced is being stacked on top of the internal padding within the modal which results in an extra space at the bottom:

Screenshot 2024-09-18 at 22 30 05

Might be a good opportunity to refactor the paddings we apply in our modals because we do have another prop called `withPadding`. Maybe these two props can be investigated and amended 🛠️

**Comment by Nortsova** [comment]
Hey @rumzledz 🙌! Thank you so much for your detailed review and for bringing your attention to these points! I really appreciate it. ✨

I’ve revisited the UI with our design system v3 -  https://www.figma.com/design/l1dOM5qiQYwF0ElvKDqqjg/Design-System---Colony-v3?node-id=1782-13151&node-type=frame&t=9Ba2SlHr50ZLzXrj-0  

And from what I can see, the **padding** seems to align perfectly:
image

Additionally, I checked the pixels and figma sizes:
Screen Shot 2024-09-19 at 11 02 39 AM
And it matches implemented sizes:
image

Could you kindly clarify what exactly appears off with the paddings from your end?

Regarding the refactoring, you're absolutely right - this component could benefit from improvements. However, refactoring at this point would likely lead to scope creep, as the Modal component is used in over 50 places We’d need to make sure none of those components break, which could take more time than the 4-hour estimate for this bugfix.

image

Would you like me to create a separate ticket for refactoring the Modal component?

**Comment by Nortsova** [comment]
I see what you mean about the bottom padding, and I’ve just updated it! Is there anything else that I missed? Thank you @rumzledz  🙌

image

**Review by rumzledz — DISMISSED** [review]
You nailed it @Nortsova ! Now it's looking much better! 💯 LGTM!

Screenshot 2024-09-19 at 10 59 48

**Review by iamsamgibbs — CHANGES_REQUESTED** [review]
🫠  What a mess of a component. We had a `withPaddingBottom` prop which I'm guessing adds a padding bottom to the ModalBase, but also a `withPadding` prop which adds padding bottom to this inner container.

This change does fix the original issue:

Screenshot 2024-09-19 at 11 58 53
Screenshot 2024-09-19 at 11 58 56

But it breaks the modal in a bunch of other places:
Screenshot 2024-09-19 at 11 57 51

Activity feed filter:
Screenshot 2024-09-19 at 12 00 24

Might need to do something funky like:

```
'pr-6': withPadding,
'pb-6': withPadding && !withPaddingBottom,
```

**Comment by Nortsova** [comment]
Thank you @iamsamgibbs ✨ I would say that Modal component definitely need to be refactored 🥲

image

**Review by iamsamgibbs — DISMISSED** [review]
Thanks @Nortsova ! This fixes the original issue:

Screenshot 2024-09-20 at 09 07 31

Screenshot 2024-09-20 at 09 07 36

And other modals are unaffected:
Screenshot 2024-09-20 at 09 07 03

If it doesn't increase the issue too much, could you check each of the other pages with filters and apply the same `withPaddingBottom` fix? It seems like pretty much all the filters have the same issue.

Activity feed filters:
Screenshot 2024-09-20 at 09 07 53

Agreements filters:
Screenshot 2024-09-20 at 09 08 31

Incoming funds (exaggerated example, but if a bunch of valid tokens were added the same behaviour would be seen)
Screenshot 2024-09-20 at 09 13 31

I've not checked all the filters, and some of the child pages have different filter content (balance / incoming funds for example) so I'm not sure if the fix would need to be applied in both those pages, or if they share the same component.

**Review by mmioana — COMMENTED** [review]
Nice and simple fix @Nortsova ✨ 

Could you please make the change also for the remaining filters in `Activity Feed`, `Incoming`, `Balances` and `Agreements`?

Can confirm your change didn't break the Member/Contributor cards

https://github.com/user-attachments/assets/aee209b2-bcc4-40c2-b2e9-11f3f7ab4fd5

@iamsamgibbs unfortunately i have added these 2 properties `withPadding` and `withPaddingBottom` when trying to fix the Member cards, but totally agree the Modal needs a big refactor 💅

**Review by iamsamgibbs — APPROVED** [review]
Nice job, thanks for fixing up all these modals!

Activity feed
activity feed

Members
members

Contributors
contributors

Permissions
permissions

Teams
teams

Balance
balance

Incoming funds
incoming funds

Agreements
agreements

Screenshot 2024-09-27 at 10 38 03
Screenshot 2024-09-27 at 10 38 08
Screenshot 2024-09-27 at 10 38 21
Screenshot 2024-09-27 at 10 38 32

**Review by mmioana — APPROVED** [review]
Thank you for your amazing effort on this one @Nortsova ❤️ 🎉 

Can confirm the change is applied to all `Filter & sort` mobile modals
Screenshot 2024-09-27 at 12 36 13
Screenshot 2024-09-27 at 12 36 27
Screenshot 2024-09-27 at 12 36 38
Screenshot 2024-09-27 at 12 36 53
Screenshot 2024-09-27 at 12 37 08
Screenshot 2024-09-27 at 12 37 26
Screenshot 2024-09-27 at 12 37 29

Other modals remain unaffected
Screenshot 2024-09-27 at 12 39 04
Screenshot 2024-09-27 at 12 39 34
Screenshot 2024-09-27 at 12 39 45

**Review by rdig — APPROVED** [review]
Nicely done! :100:

**Pull request merged**
