### PR TITLE
fix: edit exisitng team action

### PR DESCRIPTION
**Pull request by joanna-pagepro**
https://tw.auroracreation.com/app/tasks/15687547

Out of scope:
- title in preview mode - handled here: https://github.com/JoinColony/colonyCDapp/pull/1483
- team name length validation - handled within this task: https://tw.auroracreation.com/app/tasks/15687546

### CODE REVIEW

**Review by arrenv — CHANGES_REQUESTED** [review]
@joanna-pagepro In addition to Armando's feedback, can we have the "Select team" text changed to just "Team" in all cases. As it is more generic for the before and after case.

Design shows it here - https://www.figma.com/file/5V8pr7iMwXsT9L3VAZsmUt/Colony-V5?type=design&node-id=1418-101986&mode=design&t=5GwTw2iH8yso3Y49-4

**Review by ArmandoGraterol — CHANGES_REQUESTED** [review]
Nice work! The action sidepanel validation and summary seems to be working as expected. However, the motion sidepanel's summary is still showing a blank team:

FireShot Capture 252 - Transaction - 0x1d31aac6402502e87545ca9c4cf9c19e1e2bda2262d0cf9520b21_ - localhost

**Review by arrenv — DISMISSED** [review]
Looks great, thanks @joanna-pagepro. Approved.

**Review by melyndav — DISMISSED** [review]
Works as expected for me, nice!!

**Comment by joanna-pagepro** [comment]
@ArmandoGraterol thanks for reporting this. I was using the wrong value for this field. It was pointing to the Root team and the Root team was excluded from team select and that's why it was blank. I'm using `fromDomain?.nativeId` from `action` now. Let me know if it's ok now.

@arrenv @melyndav can you take a look again?

**Review by ArmandoGraterol — APPROVED** [review]
Looks great to me! Thank you Joanna

**Review by TomaszChmielPagepro — APPROVED** [review]

**Pull request merged**
