### PR TITLE
Feat[15668644]: redesign verified page

### PR DESCRIPTION
**Pull request by KornelKwiatkowski**
## Description

Task: https://tw.auroracreation.com/app/tasks/15668644

**Changes** 🏗

- removed side navigation <- UPDATE 17.11
- removed filer by teams from filter button
- changed Filter button -> All filters

before:

image

image

after:

image

image

### CODE REVIEW

**Review by krawczykkatarzyna — APPROVED** [review]

**Comment by KornelKwiatkowski** [comment]
Note from @melyndav:

image

image

**Review by rdig — APPROVED** [review]

**Comment by KornelKwiatkowski** [comment]
@melyndav from now, the filter button for this table is always shown

**Review by melyndav — CHANGES_REQUESTED** [review]
Hey @KornelKwiatkowski appreciate you adding the filter button back in. Are the checkboxes disabled? Can you remove this? I can hover but nothing can be checked. Thanks :)

**Review by ArmandoGraterol — DISMISSED** [review]
LGTM 👍 

I just noticed 1 small thing that might be out of scope of this PR:

[16702e95-625d-40e5-9eea-41c7251752d9.webm](https://github.com/JoinColony/colonyCDapp/assets/18473896/71b52f08-3416-4bf0-ae74-e877f31ade02)

If I click on a filter item and click over another one fast I can get all the menus to open at the same time.

**Comment by KornelKwiatkowski** [comment]
@melyndav sorry, I accidentally removed too much code. Now it should be ok.

**Comment by KornelKwiatkowski** [comment]
Hi @ArmandoGraterol 

It's interesting. I reproduced it. For me, these modals disappear faster, but I agree that this is a bug for which we can create a separate task. @AdrianDudko, could you take a look at this?

https://github.com/JoinColony/colonyCDapp/assets/90605528/5a60da12-2b89-4a31-ba02-9c9a75931ea2

**Review by melyndav — APPROVED** [review]
Thank you for fixing the removed code. This is approved @KornelKwiatkowski :)

**Review by arrenv — DISMISSED** [review]
Looks good, thank you!

**Comment by AdrianDudko** [comment]
> Hi @ArmandoGraterol
> 
> It's interesting. I reproduced it. For me, these modals disappear faster, but I agree that this is a bug for which we can create a separate task. @AdrianDudko, could you take a look at this?
> 
>  Screen.Recording.2023-11-22.at.09.40.48.mov


Hi @ArmandoGraterol, thanks for your help with reporting issues!  

I have created a separate task for the issue you reported at https://tw.auroracreation.com/#/tasks/15677481 to ensure it will be addressed.

**Review by CzarekDryl — APPROVED** [review]

**Review by krawczykkatarzyna — APPROVED** [review]

**Review by arrenv — APPROVED** [review]
Rebase looks good.

**Pull request merged**
