### PR TITLE
Feat: Send notifications on permissions actions

### LINKED ISSUE #3186: Notifications: Send notifications when an action is created using permissions
### Story

As a *user*, I want to *receive a notification when an action is created using permissions*, so that *I am kept informed as to what is happening in my colonies*

### Description

When an action is created using the permissions decision method, a notification should be sent. The recipients of this notification should be everybody who is in the colony who has notifications turned on, and does not have this colony muted, as well as a separate notification for anybody directly affected by this action.

Here is a list of the actions which should be handled by this ticket:
- Transfer funds
- Mint tokens
- Unlock a token
- Manage tokens
- Create new team
- Edit a team
- Manage reputation
- Manage verified members
- Manage permissions
- Edit Colony details
- Upgrade Colony version

And a list of those that are not handled in this ticket:
- Simple payment (handled in another, earlier ticket #3010)
- Advanced payment (will be handled in a ticket covering all expenditures later)
- Create agreement (will be handled in a ticket covering reputation voting later)

### This issue is complete when...

- [ ] Notifications are created when a transfer funds action is made with permissions
- [ ] Notifications are created when a mint tokens action is made with permissions
- [ ] Notifications are created when a mint tokens action is made with permissions
- [ ] Notifications are created when an unlock a token action is made with permissions
- [ ] Notifications are created when a manage tokens action is made with permissions
- [ ] Notifications are created when a create new team action is made with permissions
- [ ] Notifications are created when an edit a team action is made with permissions
- [ ] Notifications are created when a manage reputation action is made with permissions
- [ ] Notifications are created when a manage verified members action is made with permissions
- [ ] Notifications are created when a manage permissions action is made with permissions
- [ ] Notifications are created when an edit Colony details action is made with permissions
- [ ] Notifications are created when an upgrade Colony version action is made with permissions

### PR DESCRIPTION
**Pull request by davecreaser**
## Description

When an action is created using the permissions decision method, a notification should be sent. The recipients of this notification should be everybody who is in the colony who has notifications turned on, and does not have this colony muted, as well as a separate notification for anybody directly affected by this action.

Here is a list of the actions which should be handled by this ticket:

- Transfer funds
- Mint tokens
- Unlock a token
- Manage tokens
- Create new team
- Edit a team
- Manage reputation
- Manage verified members
- Manage permissions
- Edit Colony details
- Upgrade Colony version

And a list of those that are not handled in this ticket:

- Simple payment (handled in another, earlier ticket)
- Advanced payment (will be handled in a ticket covering all expenditures later)
- Create agreement (will be handled in a ticket covering reputation voting later)

As you can see, the code change here is simply a hash change, the real code changes are here: https://github.com/JoinColony/block-ingestor/pull/272

## Testing

Ensure that the following is added to your `.env.local.secrets` and run `npm run prepare`.

```
MAGICBELL_API_KEY=<ask me for this>
MAGICBELL_API_SECRET=<ask me for this>
MAGICBELL_DEV_KEY=
```

We need to go through each action and ensure that the correct notifications are sent. First though, log in as Leela, and any other user who you would like to use to test mentions with. This creates their notifications user in the db and will ensure that they receive notifications.

As Leela, go through the list and make an action for each, and then open the notifications tab inside the user hub to ensure that the notification arrived:

* Transfer funds:
1_transfer_funds_action
1_transfer_funds_notification

* Mint tokens:
2_mint_tokens_action
2_mint_tokens_notification

* Unlock tokens:
3_unlock_token_action
3_unlock_token_notification

* Manage tokens:
4_manage_tokens_action
4_manage_tokens_notification

* Create team:
5_create_team_action
5_create_team_notification

* Edit team:
6_edit_team_action
6_edit_team_notification

* Manage reputation (this one also sends a _mention_ notification, so whichever user you manage the reputation of should also have received a mention for this one):
7_manage_rep_award_action
7_manage_rep_award_notification
8_manage_rep_remove_action
8_manage_rep_remove_notification
Screenshot 2024-09-30 at 13 12 51
Screenshot 2024-09-30 at 13 13 25

* Manage permissions (also an action which triggers a mention):
9_manage_permissions_action
9_manage_permissions_notification
Screenshot 2024-09-30 at 13 15 27

* Edit colony:
10_edit_colony_action
10_edit_colony_notification

* Manage verified members (also an action which triggers a mention):
11_manage_verified_members_add_action
11_manage_verified_members_add_notification
12_manage_verified_members_remove_action
12_manage_verified_members_remove_notification

* Upgrade colony version (I have a separate problem running this locally so no screenshots yet, but I'm working on fixing that - it is unrelated to this PR). You can check out the bottom of this notion doc: `https://www.notion.so/colony/Deploying-older-contract-versions-ade18613d32f42ce87eedeca929bf2fc` to see how to run an old version of colony locally, so that you can create this action and test it if you wish.

## Diffs

**New stuff** ✨

* New block ingestor hash.

**Changes** 🏗

* Changes in the block ingestor, which fire notifications for each action completed using permissions.

Resolves #3186

### CODE REVIEW

**Comment by jakubcolony** [comment]
@davecreaser looks like this needs a rebase

**Comment by davecreaser** [comment]
> @davecreaser looks like this needs a rebase

Yep, thanks for the heads up! It's rebased now :)

**Review by bassgeta — APPROVED** [review]
Approving the hash change, LGTM :sunglasses: 
In all seriousness, the block-ingestor solution is super straight forward, you've just plugged it in on all actions and it just works, great stuff!
I wasn't able to check upgrading a colony, but all the others work flawlessly:
Create domain :heavy_check_mark: 
image
image
Edit colony details:
image
Edit domain:
image

Manage reputation: 
image
(the fact that the reputation numbers don't align already exists in the activity feed)

Manage permissions:
image

Minting tokens:
image

Moving funds: 
image

Simple payment already works :D

Adding verified members:
image

Removing:
image

Managing tokens:
image

And finally, unlocking a native token:
image


As I've messaged you on Discord, I've gotten some notifications multiple times, but it could be just my dev env or something we can tackle separately 

This one can be shipped :ship:

**Review by mmioana — APPROVED** [review]
Tested and `leela` got all the notifications

`Transfer funds`
Screenshot 2024-10-04 at 09 47 53
Screenshot 2024-10-04 at 09 48 06
`Mint tokens`
Screenshot 2024-10-04 at 09 48 44
Screenshot 2024-10-04 at 09 48 51
`Unlock token`
Screenshot 2024-10-04 at 09 49 57
Screenshot 2024-10-04 at 09 50 07
`Manage token`
Screenshot 2024-10-04 at 09 50 34
Screenshot 2024-10-04 at 09 50 48
`Create team`
Screenshot 2024-10-04 at 09 52 20
Screenshot 2024-10-04 at 09 52 25
`Edit team`
Screenshot 2024-10-04 at 09 52 54
Screenshot 2024-10-04 at 09 53 04
`Awarding reputation`
Screenshot 2024-10-04 at 09 53 52
Screenshot 2024-10-04 at 09 53 58
`Removing reputation`
Screenshot 2024-10-04 at 09 57 53
Screenshot 2024-10-04 at 09 58 01
`Manage permissions`
Screenshot 2024-10-04 at 09 58 48
Screenshot 2024-10-04 at 09 58 54
`Edit colony`
Screenshot 2024-10-04 at 10 01 59
Screenshot 2024-10-04 at 10 02 04
`Add verified members`
Screenshot 2024-10-04 at 10 02 34
Screenshot 2024-10-04 at 10 02 40
`Remove verified members`
Screenshot 2024-10-04 at 10 03 22
Screenshot 2024-10-04 at 10 03 30

Btw @davecreaser would it make sense to capitalise the action name?
Screenshot 2024-10-04 at 09 49 29

Another thing I noticed is that if you already have your user magic bell configuration in place before running the `create-data` script, also older notifications will show up

https://github.com/user-attachments/assets/71e46c3e-1ec6-49d3-9f3e-6197c527d313

And I run into an error when logging in as `amy` or `fry` on my `dev` environment, about which I messaged you on Discord, but I don't think it's a road blocker for this PR
Screenshot 2024-10-04 at 09 56 04

Nice job implementing this feature @davecreaser 🎉

**Review by iamsamgibbs — APPROVED** [review]
Nice work on this @davecreaser it is all working very nicely!

Screenshot 2024-10-04 at 09 44 53

Screenshot 2024-10-04 at 09 44 59

I've noticed a couple of unrelated issues. The hover state in the UserHub list is inconsistent with the other UserHub tabs.

No hover state:
Screenshot 2024-10-04 at 09 48 05

Compared to transactions:
Screenshot 2024-10-04 at 09 47 54

I also noticed this weird behaviour with the load more trigger. It seems to only happen after marking a notification as read then scrolling around a bunch at the bottom of the list, so I guess this is unlikely to ever actually be an issue once clicking them opens a transaction, but just thought I'd put it on the radar (maybe more of an issue for notifications that don't open anything?)

https://github.com/user-attachments/assets/3d73c70a-b5ff-486a-9190-f80beed19bee

Great work on this, it's nice seeing the feature come together!

**Comment by iamsamgibbs** [comment]
Oh, forgot to mention:

Screenshot 2024-10-04 at 09 44 59

The values for minting and transferring shouldn't exclude the network fee - might be fixed by this issue (or will need the same fix applied) https://github.com/JoinColony/colonyCDapp/issues/3069

**Pull request merged**
