### PR TITLE
Fix: Update UI on Main Extensions Page

### LINKED ISSUE #1637: Extensions: UI Updates to main menu page
## Descriptions

The extensions page (/beta/extensions/) of each Colony requires some minor UI changes. The scope of the PR is to make the following changes to this main Extensions page. The individual page of each extension is not included within the scope. 

1. Update the extension description font size from small regular (12px) to regular (14px) as per the Figma design across all responsive sizing. 
image

2. Increase the padding between each extension's title and the description text to 6px.
image

3. Align all the extension logos to the top of the title (currently they are positioned in the centre) across all responsive sizing. 
image

4. Change all buttons, including their variations, from primary to secondary button types. All interactions (hover etc) remain the same across all responsive sizing. 
image

5. Change the extension categories font from regular medium to regular bold across all responsive sizing. 
image

## Figma

Link to complete Figma file: https://www.figma.com/file/6qONTE1uD9K4yoIbfFzidg/Extensions?type=design&node-id=301-33136&mode=design&t=U9vcRNYy8fu8X0Az-4

### PR DESCRIPTION
**Pull request by iamsamgibbs**
## Description

On the main extensions page, increased the extension description font size from 12px to 14px, and increased the margin top to 6px. Aligned the extension logo to the top of the title. Resized the action buttons to match the small button size.

**Changes** 🏗

* Increase the extension description font from text-sm to text-md
* Increase the extension description margin top to mt-1.5
* Changed the alignment from items-center to items-start to align the extension logo to the top of the title.
* Descoped: ~~Changed the action button size for installed extensions by updating the actionButton css to match the small button css styling~~
* Descoped: ~~Changed the action button size for extensions which are not installed by passing the small size prop to the button component~~

Screenshot 2024-01-10 at 10 30 34

Resolves #1637

### CODE REVIEW

**Review by rdig — DISMISSED** [review]
UI wise / change wise this is all good. Congrats!

Screenshot from 2024-01-10 13-59-51

However, I see the same commits added here as in #1676, again authored by @bassgeta 

Commits 17adf47966cd324a30487e1f88052a71ba5dcbba and bde0c9a67286abfb190b3aeab4a870aeff04dbd6

Screenshot from 2024-01-10 13-59-20
Screenshot from 2024-01-10 13-59-28

How (or why) did they made their way into this PR. Does it need rebasing? Were they cherry picked ?

**Review by rdig — APPROVED** [review]

**Review by ArmandoGraterol — APPROVED** [review]
Looking good to me! Good job 🎉

**Review by melyndav — CHANGES_REQUESTED** [review]
Hey @iamsamgibbs nice start on this Pr, thanks for picking up the issue.

A minor thing - the secondary buttons have 12px left and right padding and 8px top and bottom. I'm seeing 10px and 6px. Could we get these adjusted? Globally they should all be the same. 

Component for reference: 
https://www.figma.com/file/l1dOM5qiQYwF0ElvKDqqjg/Design-System---Colony-v3?type=design&node-id=1805-572&mode=design&t=SR1Ar1N8TNoTYymY-4

**Comment by melyndav** [comment]
The request to change the buttons have been de-scoped from this PR @iamsamgibbs :)

**Comment by iamsamgibbs** [comment]
Reverted the button changes as requested.

**Review by melyndav — APPROVED** [review]
Looks great @iamsamgibbs! Thanks for the further updates. Approved!

**Review by rdig — APPROVED** [review]

**Pull request merged**
