### PR TITLE
Fix: Run truffle in network container, remove truffle package

### PR DESCRIPTION
**Pull request by jakubcolony**
## Description

Following changes to docker setup a while ago, the truffle console accessed via npm script no longer contained network contracts. This PR updates the truffle script to run truffle console inside network container, where it has access to contracts build output.

## Testing

Run `npm run truffle`.

Press `TAB` twice, and scroll up to verify the truffle instance picked up contracts properly. It should look similar to this:
image

## Diffs

**Changes** 🏗

* `truffle` script in package.json

**Deletions** ⚰️
* `truffle` package - no longer required

### CODE REVIEW

**Review by rdig — APPROVED** [review]
Yup, all good.

Feel free to also remove the local truffle config file as it's no longer being used: https://github.com/JoinColony/colonyCDapp/blob/22edb9e8d5bef7121e4fcf6a45bce1759f146dd4/truffle.js

Nice job on adding the testing section as well.

**Comment by jakubcolony** [comment]
@rdig removed, thanks

**Review by warrencolliver — APPROVED** [review]
looks Good

**Review by bassgeta — APPROVED** [review]
works on my machine and probably all of the machines too, lgtm :ship:

**Pull request merged**
