### PR TITLE
fix token blockies not showing consistently

### LINKED ISSUE #1712: Global: Blockies are not showing consistent
## Description

When navigating around the user interface, the blockies are showing inconsistently for the same element. Here in my screenshot below, you can see that the popover for the same token, shows a different blockie. This shouldn't be happening to avoid user confusion. This is not just for tokens, but for members etc.

image

## Expected behaviour

* Example: Blockies should display consistently to avoid user confusion and help users connect blockies to members and other UI elements.

### PR DESCRIPTION
**Pull request by warrencolliver**
## Description

This PR fixes the issue where blockies for tokens were showing inconsistently, when in the colony balance token list, each token has it's own thumbnail, if this thumbnail / image is a default blockie it'll appear as a different blockie when the user clicks on the token for more info. This is because currently a new blockie is being generated specifically for this token info image instead of using the tokens original blockie default

**New stuff** ✨
The same blockie is now shown in the token info image
Screenshot 2024-01-24 at 12 43 40

User blockies in the user drop down menu now show consistently with the user's blockie
Screenshot 2024-01-25 at 15 31 54

**Changes** 🏗

Changed <avatar> within TokenInfo.tsx to <TokenIcon> 
Removed the <Avatar> import 
Added <TokenIcon> import
Removed { avatar, thumbnail } as they are no longer used.

Resolves #1712

### CODE REVIEW

**Review by rdig — DISMISSED** [review]
Looks good. Thank you for your fixing this.

Screenshot from 2024-01-24 16-21-53

**Review by melyndav — CHANGES_REQUESTED** [review]
Hey @warrencolliver - as mentioned in Discord, this issue needs to be resolved globally and not just for the balance tokens as per my orgional issue raised. 

Here you can see EchoTango's blockie on the left does not match the same blockie within the user dropdown. 

image

**Review by ArmandoGraterol — COMMENTED** [review]
Looking good! The only place I could find with a different blockie was in the dropdowns of the action side panel like Mel already pointed out. I'll re-review once that's addressed

**Comment by melyndav** [comment]
> @melyndav if have a list of locations where this issue can be encountered, I'm sure it will help out @warrencolliver

It's globally. So if it's a member, the icons will the different on the members page then from a members dropdown in actions. It's also the members pop-over etc.

Anywhere where a blockie can be show needs to align with what is assigned to the user profile or the token on creation.

**Review by ArmandoGraterol — APPROVED** [review]
I've looked into every place that I know that has a blockie and they seem to be consistent 👍 Good job

**Review by melyndav — APPROVED** [review]
@warrencolliver you've gone and smashed this out of the park! Thank you for fixing an issue that had bothered me for so long with the lack of the one avatr showing consistently for users. 💯 🥇 THANK YOU!

**Review by bassgeta — APPROVED** [review]

**Pull request merged**
