### PR TITLE
Image upload form styling & interaction issues

### LINKED ISSUE #2267: Image upload form styling & interaction issues
## Description

In production, there are a number of minor UI issues that require addressing within the upload modal of the 'Edit Colony details' and the inline upload form within the User Account to better align the UI with the correct component designs within the Design System. 

Changes should be made to both file upload section and across all responsive sizes. 

**Issue 1: The main button in the modal should say 'Confirm change' as per the Figma design. Relevant only for the Edit Colony details action type**

Button title change: 
image

As per Figma:
image

--

**Issue 2: The styling of the error state does not match the component design. Across both upload forms.**

image

As per component design in Figma:
image
 
 Component link in design system: https://www.figma.com/file/l1dOM5qiQYwF0ElvKDqqjg/Design-System---Colony-v3?type=design&node-id=1782-9638&mode=design&t=UCmEsZubFQMtqi5S-4

--

**Issue 3: When there is a file error, the cancel and confirm buttons should not show in the modal only during the default upload state. The buttons should not show in the error state, only default and complete states. Relevant only for the Edit Colony details action type.** 

image

-- 

**Issue 4: When I upload an image that is too large and receive the error state, when I try again with an image that is the correct file size it uploads it correctly, but the form breaks again. The page needs a refresh in order for the form to work again.**

Video:
https://jmp.sh/XiUpEUnP

### PR DESCRIPTION
**Pull request by davecreaser**
## Description

Fix some image upload form UI issues:
- Fix text of the confirm change button
- Fix styling of error state
- Don't show the cancel and confirm buttons in the Colony Avatar upload modal when there's an error

More details here:
https://github.com/JoinColony/colonyCDapp/issues/2267

Note: I could not reproduce issue number 4 in the above issue, and since there is already another investigation ticket raised to fix some problems with the image upload, I think it is better if this part of the issue is moved to that ticket, since it seems very related. Details in comments of issue 2267.

## Testing

Check that the UI of the image upload is as expected

* Confirm Change button text
* Styling of the error
* Buttons don't show on the colony avatar modal when there's an error in uploading

## Diffs

**Changes** 🏗

* Changes to the image upload UI

Resolves #2267

### CODE REVIEW

**Review by iamsamgibbs — CHANGES_REQUESTED** [review]
Nice work on this!

Issue 1 is resolved, button text is now correct:

Screenshot 2024-04-29 at 09 48 56

Issue 2 is mostly resolved, text is all looking correct. Only one tiny change, the trash icon should be aligned to the top.

Screenshot 2024-04-29 at 09 42 30

Figma:

Screenshot 2024-04-29 at 09 51 44

Issue 3 is resolved, buttons now disappear when there is an error.

I'm also unable to recreate issue 4 (and agree that it makes sense to tackle with #2262)

**Review by melyndav — CHANGES_REQUESTED** [review]
Hey @davecreaser nice start on this.

There's hover state is missing on the trash icon. Can you add one so it matches the retry and ensure consistency within the component? 

Also, I'm still experiencing issue 4 which I've commented on the other PR since it's not being covered here - https://github.com/JoinColony/colonyCDapp/issues/2262#issuecomment-2082335429

Can you leave a comment on #2262 making sure issue 4 from the original issue is linked so it's not forgotten? Thanks.

**Review by melyndav — APPROVED** [review]
Thank you for the additional hover state @davecreaser looking great now! 💯

**Review by iamsamgibbs — APPROVED** [review]
Great, all looks good now!

Screenshot 2024-04-29 at 15 39 22

**Pull request merged**
