### PR TITLE
feat: add leave colony confirmation modal

### LINKED ISSUE #1468: Leave Colony confirmation modal
## Description
During the Beta period, leaving a Colony will kick members out of their joined Colony, unable to join again unless they use an invite code.

As users have the intent of testing the UI, it is possible that they will click the leave button and thus lose access to their Colony.

While we could manually provide them with their invite code again, having a confirmation modal will be an improved solution.

Figma link - Desktop: https://www.figma.com/file/5V8pr7iMwXsT9L3VAZsmUt/Colony-V5?type=design&node-id=17706-65306&mode=design&t=VIWzYPyliiEaXm41-4
Figma link - Mobile: https://www.figma.com/file/5V8pr7iMwXsT9L3VAZsmUt/Colony-V5?type=design&node-id=17706-157354&mode=design&t=VIWzYPyliiEaXm41-4

image

### PR DESCRIPTION
**Pull request by chmanie**
## Description

This PR adds a modal to confirm the leaving of a Colony.

Confirm

Closes #1468.

### CODE REVIEW

**Review by bassgeta — DISMISSED** [review]
works for me, also onClicks in hooks :drooling_face: good job, ship it

**Review by bassgeta — APPROVED** [review]

**Review by thomassdk — COMMENTED** [review]
UI looks good but its a bit broken at the moment as I am also getting the:

image

I think this may be because the colony contributor is no longer being created so the query fails as it tries to mutate a contributor that does not exist

**Comment by chmanie** [comment]
Good find! @thomassdk Could you look into it and maybe open another PR with a fix?

**Comment by thomassdk** [comment]
I think @rdig is working on a fix for that at this very moment https://github.com/JoinColony/colonyCDapp/commit/f558a3154fa2addf37170f99fac38b5e4a27607b as it seemed to be removed for a specific reason

Another thought I had about this PR is that it is missing removing the user from the colony whitelist as part of the leaving a colony. I can take this over as I want to refactor the whitelist so that it aligns with the new model of contributors by adding a `isWhitelisted` to the colony contributor model.

Does that sound reasonable to you @chmanie ?

**Comment by rdig** [comment]
Not working specifically on that, but working on refactoring the colony creation flow

**Comment by rdig** [comment]
Also note, that any changes we do from now on to the schema will require a database migration to work properly

**Comment by chmanie** [comment]
> Does that sound reasonable to you @chmanie ?

Let's do it!

**Pull request merged**
