### PR TITLE
fix: Update payment message descriptor case

### LINKED ISSUE #3755: [UserHub] Metadata for activity is replaced by long code snippets in the UI
## Steps to reproduce

1. Leela creates a simple payment with the reputation for Leela.
2. Open UserHub.
3. Click on the View Staked balance.
4. Observe inconsistent formatting and unclear labels.

## Expected behaviour

* Display metadata info.

## Actual behaviour

* Metadata for activity is replaced by long code snippets in the UI.

image
image
image

### PR DESCRIPTION
**Pull request by rumzledz**
## Description

Just a wee one-liner. It also fixes copies in the Activity Table for Simple Payment Reputation and Multi-Sig motions.

Screenshot 2024-11-28 at 14 23 34

## Testing

1. Enable the Reputation and Multi-Sig extensions
2. Create a Simple Payment via Reputation motion
3. Stake it
4. Open the User Hub and open the Stakes tab
5. Verify that the correct copy is shown

image

6. Create a Simple Payment Multi-Sig motion
7. Go to the Dashboard
8. Verify that the correct copies are shown for the Simple Payment Reputation and Multi-Sig motions

Resolves #3755

### CODE REVIEW

**Review by mmioana — APPROVED** [review]
Smashed another issue @rumzledz 💯 

Installed both extensions
Screenshot 2024-11-28 at 09 04 59
Screenshot 2024-11-28 at 09 05 07

Created a `Simple payment` using reputation
Screenshot 2024-11-28 at 09 05 49

In the `UserHub` the correct description shows up
Screenshot 2024-11-28 at 09 06 26

Gave `leela` Multi-sig permissions
Screenshot 2024-11-28 at 09 07 07

Created a `Simple payment` using Multi-sig
Screenshot 2024-11-28 at 09 08 28

And both actions have the right descriptions showing up in the `Activity` tables
Screenshot 2024-11-28 at 09 08 57
Screenshot 2024-11-28 at 09 13 23

**Review by Nortsova — DISMISSED** [review]
Great, thank you for this fix ✨ 

image

**Review by iamsamgibbs — APPROVED** [review]
Nice simple fix!

Screenshot 2024-11-29 at 10 20 31

Screenshot 2024-11-29 at 10 23 13

**Review by davecreaser — CHANGES_REQUESTED** [review]
Hey @rumzledz, I think that this may break advanced payments.

Screenshot 2024-11-29 at 10 26 59

Here i've done a staged payment. I think since it's now an 'includes' instead of '===' it means that the switch case will incorrectly end here for advanced payments (since they include 'payment' in the action type).

**Comment by rumzledz** [comment]
@davecreaser

> Here i've done a staged payment. I think since it's now an 'includes' instead of '===' it means that the switch case will incorrectly end here for advanced payments (since they include 'payment' in the action type)

Oh wow this is a really nice find @davecreaser ! All right I'll investigate and make adjustments 👌

**Comment by rumzledz** [comment]
@davecreaser I've just pushed the fix 🚀

**Review by davecreaser — APPROVED** [review]
Nice! Clever way of fixing it, just rearranging the order 😆 I love it.

All the messages look good to me now (tested a few payment types / decision methods etc):

Screenshot 2024-12-02 at 09 31 02

**Review by iamsamgibbs — APPROVED** [review]
Nice job, looks good to me!

Screenshot 2024-12-02 at 10 50 16

Screenshot 2024-12-02 at 10 53 07

**Review by mmioana — APPROVED** [review]
Smashed @rumzledz 💯 

Screenshot 2024-12-02 at 17 44 26
Screenshot 2024-12-02 at 17 45 24
Screenshot 2024-12-02 at 17 45 54
Screenshot 2024-12-02 at 17 46 11

**Pull request merged**
