### PR TITLE
The grand phosphor icon refactor

### LINKED ISSUE #1423: Maintenance: the Grand Phosphor Icon refactor
For the migration to `tsup`/`esbuild` as well as the integrations framework we need to move all icons in the CDapp to use the [Phosphor](https://phosphoricons.com/) icon set. This mainly removes our reliance on dynamic imports (bad for tree shaking!) and provides more flexibility in terms of icon sizes (these are completely out of hand anyways).

So the plan is:

1) Remove the `Icon` component
2) Replace all occurrences with Phosphor icons (ask @melyndav for a replacement icon if it doesn't exist there) - be sure to use the right size!
3) Use [this method](https://github.com/phosphor-icons/react?tab=readme-ov-file#custom-icons) for icons that are not available on Phosphor (like the Colony logo)
4) Profit!

### PR DESCRIPTION
**Pull request by chmanie**
## Description

This (huge) PR replaces all custom icons with more consistent and more flexible phosphor icons. This was mainly to get rid of webpack's dynamic `require()`s, but also has the advantage of providing a more consistent icon experience overall. Going forward there will be no more general `Icon` component.
Seeing there were so many sizes used for the icons (looking at you `largeSmall`!) I opted to just provide a pixel number for the size of individual icons.
This PR also updates the phosphor icon library to version 2.x as we were using some icons from this version (imported as custom ones).
Furthermore all of the custom icons had to be adjusted, which was luckily taken care of by @arrenv (thank you :heart: - see [here](https://github.com/phosphor-icons/react?tab=readme-ov-file#custom-icons)) how) and some fixes for colors and sizes were applied (in many places these were off on `master`, too). 

## Testing

Go through the app and check if all icons are the correct one (!) and have the right size and color in all available states (that's a @melyndav job :D).

## Diffs

**Changes** 🏗

* Update `phosphor-react` v1.4 to `@phosphor-icons/react` 2.1
* Migrate all general icons over to phosphor
* Migrate all custom icons over to phosphor
* Apply fixes for icon colors and sizes

**Deletions** ⚰️

* `Icon` component and most of the custom icons as well as all unused ones.

Resolves #1423

### CODE REVIEW

**Review by iamsamgibbs — CHANGES_REQUESTED** [review]
Thanks for tackling what I imagine was quite a gruelling task! I hit a couple of issues where `icon.content.replace` is leftover(?) / not working properly for the wallet onboarding - I changed them to empty strings to get the site to load properly and was able to get into the main part of the app where everything seems to be working great, all icons seem as expected!

Screenshot 2024-02-09 at 10 50 44

`ganacheModule.ts` and `onboard.ts` both inside `src/redux/sagas/wallet` are where the issue is occuring.

**Comment by iamsamgibbs** [comment]
Screenshot 2024-02-09 at 11 02 36

All icons looking great otherwise though! 🎉

**Comment by chmanie** [comment]
@iamsamgibbs Thanks for checking this out! Mel made me aware of this as well, seems a rebase went wrong somewhere. Let me fix this and give you a shout once it's ready again :)

**Comment by chmanie** [comment]
@iamsamgibbs @melyndav Should be good now!

**Comment by iamsamgibbs** [comment]
Tested again and this is working great! 🎉

**Review by iamsamgibbs — APPROVED** [review]

**Review by melyndav — CHANGES_REQUESTED** [review]
Heya @chmanie! I've done another check and just noticed a few things that are off.

1. In the main Colony switcher draw in both the in and out of Colony context's both the Colony avatar and chain icon are too small and too big. Both should be 18x18px.

image

2. The icons in the hamburger menu for inside menus are too small and should be 16x16
image
image

3. Icons from the kebab menu on the dashboard should be 16x16
image

4. All search icons should be 14x14px in the filter menus. The one in the colony switcher looks correct. 
image
image

5. Hamburger icon should be 16x16px.
image


Mobile looks good. 👍

**Comment by chmanie** [comment]
@melyndav Thank you for the thorough review, I'll get to work immediately!

Just as a note: all of these issues that you found did exist in production already.

**Comment by melyndav** [comment]
@chmanie I can see a few like the search icons in the filter & hamburger for example. 

image

image


The other's I'm happy to raise as a separate issue. :)

**Comment by chmanie** [comment]
It's alright, I fixed all of them already, it's easy to do. On app.colony.io the Hamburger Icon is 12x12px. The filter icons seem to have gotten messed up indeed in this PR.

**Comment by melyndav** [comment]
> It's alright, I fixed all of them already, it's easy to do. On app.colony.io the Hamburger Icon is 12x12px. The filter icons seem to have gotten messed up indeed in this PR.

You the best! 💯

**Comment by chmanie** [comment]
Alright, feel free to check again, I should have caught them all :)

**Review by melyndav — APPROVED** [review]
You're amazing @chmanie let's get this baby shipped!!

**Review by iamsamgibbs — APPROVED** [review]

**Pull request merged**
