### PR TITLE
[New Nav] Trigger the Intercom Widget using the Help & Feedback button

### LINKED ISSUE #3148: FEATURE: Help & Feedback Widget functionality
## Description

We are currently using [Intercom](https://www.intercom.com/) as our way to get feedback and messages from our users and we are using Google Tag Manager to integrate their app into ours. With the current setup, all we have to do is provide a value for the `GOOGLE_TAG_MANAGER_ID` env variable to enable the integration.

This Issue is about having our own custom triggers for displaying their widget. This will not cover extra/custom functionalities within their widget.

## Acceptance Checklist

* [ ] Clicking the Help & Feedback button should toggle the Intercom widget
* [ ] Clicking outside Widget should dismiss it
* [ ] If the integration is blocked, clicking the Help & Feedback button should take the user to https://help.colony.io/ on a new tab

### PR DESCRIPTION
**Pull request by rumzledz**
## Description

This PR is not going to update any piece of logic that happens within the Intercom widget. This includes attempting to hide the Previews from an Operator when the Widget is hidden.

This PR simply aims to do the following:
- Control the visibility of the Intercom Widget via  custom triggers
- Control the page offset of the Intercom Widget via Intercom's javascript API
- Redirect the user to https://help.colony.io/ if Intercom is not accessible

> [!IMPORTANT]
> There might be a delay when you click the Help & Feedback button for the first time on page load. I have discussed this extensively with Arren including options of how to handle the delay with loaders perhaps etc. etc.. But TLDR: It's fine as it is because it's not our fault that their widget takes time to be initialised. Even their native floating button can take time to show up on the page because of this inherent delay. The important thing is that the Widget eventually loads if Intercom is available. Otherwise, it should take the user to the Colony Help page.
 
intercom

## Testing

> [!IMPORTANT]
> 1. Please speak to me or Arren about the `GOOGLE_TAG_MANAGER_ID` env variable value
> 2. Update the `GOOGLE_TAG_MANAGER_ID` env variable in your `.env` file
> 3. Run `npm run prepare` to inject the env variables properly
> 3. Reload the page

### Integration enabled

1. Visit a Colony
2. Click the Help & Feedback button
3. Verify that the Intercom widget shows up
4. Click it again
5. Verify that the Intercom widget is dismissed
6. Click it again
7. Verify that the Intercom widget shows up
8. Click outside of it
9. Verify that the Intercom widget is dismissed
10. Click it again
11. Verify that you see this UI:

image

12. Click Send us a message
13. Verify that you see this UI:

image

## Integration disabled

> [!IMPORTANT]
> 1. Please remove the value for the `GOOGLE_TAG_MANAGER_ID` env variable
> 2. Reload the page

1. Click the Help & Feedback button
2. Verify that you are taken to https://help.colony.io/ on a new tab

Resolves #3148

### CODE REVIEW

**Review by bassgeta — APPROVED** [review]
Nice job integrating this, it's also quite nicer than what we've had before!
on the Colony page :heavy_check_mark: 
image
I get to spam Arren :sunglasses: 
image

It works legit, but if you check my video (at 16 seconds) trying to test stuff out, it can get into a weird state when it's open and you navigate away via the URL... Probably not gonna happen a lot, but if we can fix it easily we should

https://github.com/user-attachments/assets/4061f39d-a094-4eae-b6ea-0c7596c68d52

**Comment by rumzledz** [comment]
> It works legit, but if you check my video (at 16 seconds) trying to test stuff out, it can get into a weird state when it's open and you navigate away via the URL... Probably not gonna happen a lot, but if we can fix it easily we should

@bassgeta ah! I can replicate its actual native behaviour instead whereby it just dismisses the widget when you do that 👌

**Review by iamsamgibbs — CHANGES_REQUESTED** [review]
Nice work on getting this integrated, it's looking great! Only a couple of issues I noticed.

Can the menu item remain highlighted whilst the intercom is open in the same way that it does for the colony switcher?

Screenshot 2024-09-26 at 08 48 42

Screenshot 2024-09-26 at 08 51 24

I also noticed this `1` badge is added to the favicon even though there are no unread messages.

Screenshot 2024-09-26 at 08 50 03

Is there any chance intercom has a dark mode we can toggle? 👀 

Screenshot 2024-09-26 at 08 52 15

I also noticed this issue when opening the message tab that there are no back or close icons like on the other tabs? I'm guessing this is an intercom issue that we can't fix though?

https://github.com/user-attachments/assets/fdfad7dc-a62b-46cf-898e-a131bcf22df0

And finally, when no API key is provided it does indeed function like a link and opens in a new tab. It doesn't show the link preview in the bottom left like the other navigation items, it would be nice if we could add this.

https://github.com/user-attachments/assets/13e83e41-d66a-4c7a-98e9-f2de0b638787

Screenshot 2024-09-26 at 09 03 18

**Review by mmioana — CHANGES_REQUESTED** [review]
Veeery nice work on this one @rumzledz 🙌 

### Having the integration enabled

https://github.com/user-attachments/assets/df715d17-1056-42bd-9f96-2326feb343d5

Screenshot 2024-09-26 at 09 57 21
Screenshot 2024-09-26 at 09 57 35

### Having it disabled leads to the expected page
https://github.com/user-attachments/assets/a4c360a1-bd06-4d00-aff8-65f2b34661bb

The only reason I'm rejecting this is due to the fact that if you have the chat opened and you reload another page, the chat opens in the right side of the screen for a bit, then is repositioned as expected 🫠 I'm wondering if we couldn't place the page loader on top until everything is loaded?

https://github.com/user-attachments/assets/0c83f0e3-dd05-4709-89fc-a4897f095d61

**Comment by rumzledz** [comment]
All right let's start with @iamsamgibbs 😂 

> Can the menu item remain highlighted whilst the intercom is open in the same way that it does for the colony switcher?

Great shout for consistency!

> Is there any chance intercom has a dark mode we can toggle? 👀

Nope! Sorry! They don't have a way to make us programatically change to dark mode 

> I also noticed this issue when opening the message tab that there are no back or close icons like on the other tabs? I'm guessing this is an intercom issue that we can't fix though?

Yep! 🙃 

> And finally, when no API key is provided it does indeed function like a link and opens in a new tab. It doesn't show the link preview in the bottom left like the other navigation items, it would be nice if we could add this.

I mean... I can hack something together to make this work but it probably wont' be pretty 😄 I'll try to come up with something

> I also noticed this 1 badge is added to the favicon even though there are no unread messages.

Apparently this is something Beamer-related 🤷‍♂️ Best person to ask is Arren

Now onto @mmioana's comment 😄 

> The only reason I'm rejecting this is due to the fact that if you have the chat opened and you reload another page, the chat opens in the right side of the screen for a bit, then is repositioned as expected 

Sadly, there's only so much I can do about an injected component's style 😅 I already addressed this on Kerry's comment but I'll post a gif of how this behaves using their native behaviour:

weird behaviour

**Comment by rumzledz** [comment]
@mmioana I've just pushed the following update:
- Make the Help & Feedback button consistent with the Colony Switcher's behaviour whereby it stays highlighted when its widget is visible

**Review by rdig — APPROVED** [review]
So this works, but with one very huge caveat: does not work if Adblocker, and the stats I find about this online put adblocker usage at between 45 and 60% on desktop

So this defaults to linking to `help.colony.io`

Screenshot from 2024-09-26 15-11-55
Screenshot from 2024-09-26 15-12-01

Screenshot from 2024-09-26 15-12-57
Screenshot from 2024-09-26 15-13-08

It is only after I disable the adblocker that I am able to access the widget:

Screenshot from 2024-09-26 15-13-29
Screenshot from 2024-09-26 15-14-44

https://github.com/user-attachments/assets/2a77eadf-b7e9-4e85-a37d-57796d23dc56

PS: your testing steps are missing running `npm run prepare` after updating your `env` file with the Tag Manager key

**Comment by rumzledz** [comment]
@rdig 

> It is only after I disable the adblocker that I am able to access the widget:

This is actually a pretty good test! This confirms that it does indeed navigate to our Colony help page if Intercom is not accessible 👌 

> your testing steps are missing running npm run prepare after updating your env file with the Tag Manager key

Oh right, I didn't run this command because it just worked when I supplied the key BUT maybe this is because I've run the command prior or something. Will update, thank you!

**Comment by rumzledz** [comment]
@mmioana @iamsamgibbs just paired up with Arren and we're now going to explicitly hide the widget on a hard navigation even if Intercom intends for their message widget is visible 😄

**Comment by mmioana** [comment]
@rumzledz will give this use case another test 🙌

**Review by mmioana — APPROVED** [review]
Thanks for your change @rumzledz 🙌 now the chat no longer shows upon page hard navigation

https://github.com/user-attachments/assets/65700673-7159-4951-a935-47b187928169

Let's get this one merged 🚀

**Pull request merged**
