### PR TITLE
Add onboarding splash screen for when wallets are not connected

### PR DESCRIPTION
**Pull request by thomassdk**
## Description

This PR adds in the onboarding splash screen that handles the state when a user tries to create a profile or colony via a link but have not yet connected their wallet

image

To test disconnect your wallet and then to go toe the create-colony route with a inviteCode

### CODE REVIEW

**Review by melyndav — CHANGES_REQUESTED** [review]
Heya buddy @thomassdk! Thanks for the PR.  :) 

1. Button should match Figma as it's being used across the whole flow (tex-gray-900 outline border and solid on hover). Chris has it in the other splash screens & it's the same from the create a Colony flow. 

image

2. I can break the invite code in my URL and I can still go ahead and create a Colony. It should show this version of the design and stop the user from moving further. 

https://www.figma.com/file/5V8pr7iMwXsT9L3VAZsmUt/Colony-V5?type=design&node-id=16431-374375&mode=design&t=P1wuBbhYhDDlW38d-4

**Comment by thomassdk** [comment]
Thanks for the review @melyndav.

1. Good to know about the button i wasn't sure what version it was and just used the same one as in the navigation

2. The validity of the invite codes cannot be checked in this PR as that is still waiting to be merged, but I will add in that state so that when it is merged that will work

**Comment by thomassdk** [comment]
Those changes are done now, but as I mentioned we will have to wait to test the invalid splash variant

**Review by melyndav — DISMISSED** [review]
Thanks for the update @thomassdk! All good from my side.

**Review by arrenv — DISMISSED** [review]
Works as expected and looks good to me, nice one!

**Comment by thomassdk** [comment]
This is not as straight forward as I intially thought as this PR should account for more states

**Comment by rdig** [comment]
Is this ready for review? As it's still in `Draft` ?

**Comment by thomassdk** [comment]
> Is this ready for review? As it's still in `Draft` ?

Ive moved this back into draft as I realised after talking to Arren that this PR should account for more states where the splash screeen is required

**Comment by chmanie** [comment]
Chris is taking over

**Review by thomassdk — COMMENTED** [review]
Works like a charm and stings like a bee I'd approve it if I could

**Review by arrenv — CHANGES_REQUESTED** [review]
Something seems to have broken since testing earlier today? Do I need to restart everything?

image

**Comment by chmanie** [comment]
OK, all fixed now.

**Review by arrenv — APPROVED** [review]
Great work @chmanie! Everything tested is working as expected.

**Pull request merged**
