### PR TITLE
fix: change richtext paragraph lineheight and lists padding

### PR DESCRIPTION
**Pull request by mksawic**
## Description

Teamwork task: https://tw.auroracreation.com/app/tasks/15646129

**Changes** 🏗

* Changed margin for paragraphs. Now `my-1` is equal to 0.5em from top and bottom (as requested in ticket).
* Added more padding-left for lists on mobile (QA found an issue with cut-off elements for small resolution devices)
e5052513db6498b8da6b42cfb78e7b74

Contributes to #1611

### CODE REVIEW

**Review by iamsamgibbs — CHANGES_REQUESTED** [review]
This is looking good! I just noticed a couple of things while testing.

Issue 4 says to reduce to 0.5em for regular text which looks great, but to keep it at 1.25em for the headings. The changes have removed the padding for the headings - so please add this back in (and ensure the first-child has no padding top as the :not(:first-child) which was removed in the commit).

Screenshot 2024-01-29 at 09 47 18

Also spotted that the block quote padding-left doesn’t match the Figma design. Please increase to 2rem.

Screenshot 2024-01-29 at 09 29 04

Screenshot 2024-01-29 at 09 30 46

**Review by warrencolliver — APPROVED** [review]
Looks good so I'll approve but please address Sam's review before merging as I am experiencing the same

**Review by melyndav — CHANGES_REQUESTED** [review]
Hey @mksawic, great start on this PR.

1. When I highlighted the first row of content (h1) and changed the heading level in the WYSIWYG, the whole block changed formatting and not my highlighted section.

image
 
 2. When I have H1 and B selected in the WYSIWYG, the font does not change the H1 font size. The H1 should be prioristised because the font weight is already in a bold state for the H1. This goes for italic etc. 
 
image

3. When I try to use the bullets or numbered lists, when I select what I want to have this treatment applied to as shown in my screenshot, it applies it to the whole list, even though I have highlighted content and the WYSIWYG is placed right above my selection. 

Also, when I select multiple, the numbers or bullet points should be applied to each individual row. 

image

4. Line spacing is too big.

image
 
 5. The placement of the numbers or bullets doesn't line up with the content being selected.
 
image
 
 6. When trying to apply the blockquote, the whole section is formatted and the WYSIWYG looks broken and just floats over the content.
 
 
image

7. Heading formatted gets applied to whole blocks but the italics doesn't 

image

**Comment by mksawic** [comment]
@iamsamgibbs Changed as requested with following solution:

1. All direct childrens have default margin-bottom set for 0.25em (which is half of 0.5em).
2. H1, H2 and H3 have margin-bottom set for 0.625em (which is half of 1.25em).
3. Blockquote have additional padding-left

SCR-20240129-qjmz

**Comment by mksawic** [comment]
@melyndav Thanks for a huge feedback :)

Issues 1, 3, 6, 7 - Are you sure you didn't used soft line break (Shift+Enter) instead of hard line break? 
You can check that in inspector. Soft line break are treat as single line so that's why is being all being formatted when add a heading.
SCR-20240129-qllg

Issue 2 - This should be definitely fixed. But I suggest to create another ticket for that (just to keep this PR in the scope and also we can attach some more changes if needed). I can ask @AdrianDudko  to do that

Issue 4 - Line spacings should be changed now in this PR as mentioned:
> 1. All direct childrens have default margin-bottom set for 0.25em (which is half of 0.5em).
> 2. H1, H2 and H3 have margin-bottom set for 0.625em (which is half of 1.25em).

Issue 5 - I think it's an extra line break added

**Review by iamsamgibbs — CHANGES_REQUESTED** [review]
Thanks for making those changes @mksawic - the heading spacing looks great now.

I made a mistake in my last comment. I circled "margin-left" in my screenshot, but I wrote "padding-left" accidentally. The margin-left should be 32 and padding-left should be 8.

How it is currently:
Screenshot 2024-01-30 at 10 09 59

**Review by iamsamgibbs — APPROVED** [review]
This is working great now, thank you for the changes!

Blockquote margin is as expected.

Screenshot 2024-01-30 at 16 32 41

**Review by warrencolliver — APPROVED** [review]
good work on making the changes

**Review by ArmandoGraterol — COMMENTED** [review]
Is it intentional that the content doesn't align with the lists on mobile but on desktop they do?

Mobile:
Screenshot 2024-01-31 at 12 44 38

Desktop:
Screenshot 2024-01-31 at 12 44 48

**Review by melyndav — APPROVED** [review]
Hey @mksawic thanks for checking about the break issues on my review.

Everything looks to be resolved except the mobile vs desktop alignment issue that @ArmandoGraterol addressed. I will approve but please ensure this issue is fixed before merging.

Also re: this point. Happy for this to be raised in a separate issue to ensure all heading _levels (h1 - 3). Thanks! 

Issue 2 - This should be definitely fixed. But I suggest to create another ticket for that (just to keep this PR in the scope and also we can attach some more changes if needed). I can ask @AdrianDudko to do that_

**Comment by mksawic** [comment]
@ArmandoGraterol Unfortunately figma design with lists for WYSIWYG was not specified. But the intend for list on mobile was intentional. As I mentioned in PR description the QA found that WYSIWYG list on low resolution mobiles (like iPhone 12 Mini) is being cut off. Quickest and simplest solution was to add some additional intend which is actually not really messy but it protects the list from being cut off :)
image

**Pull request merged**
