### PR TITLE
Fix: prevent app crash on mobile view when viewing a transaction that's ready to be finalized

### LINKED ISSUE #2538: The app crashes on mobile view when you view a transaction that's ready to be Finalized
## Steps to reproduce

1. Enable the "Reputation weighted" extension and use the "Testing governance" preset
2. Create a Simple Payment and choose the "Reputation" decision method
3. Support the stake and submit the Max staking amount
4. Run the following commands to forward the time:
```
curl -X POST --data '{"jsonrpc":"2.0","method":"evm_increaseTime","params":[3600],"id":1}' localhost:8545
curl -X POST --data '{"jsonrpc":"2.0","method":"evm_mine","params":[],"id":1}' localhost:8545
```
5. Reload the page

## Expected behaviour

The app should not crash.

## Actual behaviour

The app crashes.

mobile_crash

## Console errors

image

### PR DESCRIPTION
**Pull request by rumzledz**
## Description

null guard

## Testing

1. Enable the "Reputation weighted" extension and use the "Testing governance" preset
2. Create a Simple Payment and choose the "Reputation" decision method
3. Support the stake and submit the Max staking amount
4. Run the following commands to forward the time:
```
curl -X POST --data '{"jsonrpc":"2.0","method":"evm_increaseTime","params":[3600],"id":1}' localhost:8545
curl -X POST --data '{"jsonrpc":"2.0","method":"evm_mine","params":[],"id":1}' localhost:8545
```
5. Reload the page
6. Make sure the app doesn't crash

## Diffs

* Just a good ol' optional chaining to make sure we're not extracting a field from an undefined object.

Resolves #2538

### CODE REVIEW

**Review by iamsamgibbs — DISMISSED** [review]
Nice simple fix!

https://github.com/JoinColony/colonyCDapp/assets/34915414/22532b29-0807-415e-93f0-d06f3088eba6

**Review by melyndav — DISMISSED** [review]
@rumzledz another one smashed. Thank you for the great work 🌮

**Review by jakubcolony — DISMISSED** [review]

**Comment by rumzledz** [comment]
Hey @iamsamgibbs @melyndav @jakubcolony apologies I had to rebase due to merge conflicts 😅 Can you please have a look again? 🙏

**Review by iamsamgibbs — APPROVED** [review]

**Review by mmioana — APPROVED** [review]
Looks good to me! Great work @rumzledz 👏 

https://github.com/JoinColony/colonyCDapp/assets/32430018/de20d432-03d3-4a8a-abe4-7018046f5792

**Review by davecreaser — APPROVED** [review]
Good ol' optional chaining eh 🤣 Nice find, and nice fix, all working, so adding my approval!

**Review by melyndav — APPROVED** [review]
Reapproving this bad boy @rumzledz! Thanks for your work again on this one! 🌮

**Pull request merged**
