### PR TITLE
feat: streaming payments extension page

### PR DESCRIPTION
**Pull request by joanna-pagepro**
## Description

Provides the ability to manage Streaming Payment Extension.

## Testing

* Step 1. Go to the extensions page
* Step 2. Click on Streaming Payments
* Step 3. Install the extension
* Step 4. Deprecate the extension
* Step 5. Uninstall the extension - please note that displaying the right messages in the modal will be handled in a separate issue.

## Diffs

**New stuff** ✨

* 

**Changes** 🏗

* The structure of the folders was updated to be the same as for the Staged Payments extension page (on a different branch)

**Deletions** ⚰️

* 

## TODO

- [ ] Update variables in Uninstall Modal to show correct messages

Resolves https://github.com/JoinColony/colonyCDapp/issues/2716

### CODE REVIEW

**Review by rdig — COMMENTED** [review]
Seems to be working and looking as expected, however the folder structure re-shuffle made things hard to spot when doing the code review

Screenshot from 2024-07-17 19-41-07
Screenshot from 2024-07-17 19-41-11
Screenshot from 2024-07-17 19-41-24
Screenshot from 2024-07-17 19-41-37
Screenshot from 2024-07-17 19-41-56
Screenshot from 2024-07-17 19-42-04

I do want to point out however that this branch has a broken package-json file:

**Review by rdig — APPROVED** [review]
Seems to be working and looking as expected, however the folder structure re-shuffle made things hard to spot when doing the code review

Screenshot from 2024-07-17 19-41-07
Screenshot from 2024-07-17 19-41-11
Screenshot from 2024-07-17 19-41-24
Screenshot from 2024-07-17 19-41-37
Screenshot from 2024-07-17 19-41-56
Screenshot from 2024-07-17 19-42-04

I do want to point out however that this branch has a broken package-json file:

Screenshot from 2024-07-17 19-38-32

Although that's most likely coming from upstream.

Please test this locally before merging

**Review by mmioana — APPROVED** [review]
Amazing work on this one @joanna-pagepro 👏 

Love the usage of the`ExtensionDetailsPageContext` ❤️ 

Can confirm it works as described 
Screenshot 2024-07-18 at 10 22 19
Screenshot 2024-07-18 at 10 22 26
Screenshot 2024-07-18 at 10 22 31
Screenshot 2024-07-18 at 10 22 37
Screenshot 2024-07-18 at 10 22 43
Screenshot 2024-07-18 at 10 22 52

**Comment by mmioana** [comment]
@rdig I did not encounter any error when running the frontend on this branch

Screenshot 2024-07-18 at 10 30 09

**Pull request merged**
