### PR TITLE
fix: button width, hide timer, cache query, remove extension banner

### PR DESCRIPTION
**Pull request by CzarekDryl**
## Description

- Few fixes to unblock split payment
- It's best to go through each issue one by one

Resolves:
https://github.com/JoinColony/colonyCDapp/issues/2862
https://github.com/JoinColony/colonyCDapp/issues/2879
https://github.com/JoinColony/colonyCDapp/issues/2890
https://github.com/JoinColony/colonyCDapp/issues/2896

### CODE REVIEW

**Review by davecreaser — APPROVED** [review]
Thanks for the fixes @CzarekDryl. Everything is looking alright to me, and I've tested each of the issues individually. Nice work 🎉 

The button width is fixed on the modals:
1_button_fixed

The loader is now not shown when it shouldn't be:
2_loader_not_shown

The graphql requests seem to be much more _relaxed_:
https://github.com/user-attachments/assets/43dd6726-e74c-4a4c-99df-6dce5d340ef4

And the permissions banner is no longer shown on the extensions page.
4_permissions_banner

Just one note: in the future could you please provide a bit more detail in the PR description? For example describing a little bit more in depth the changes that you've made and what exactly it fixes, and adding some testing steps. I realise that you added the links to the issues and that does help of course, but it makes it more easy to review the PR if it's consolidated in one place, with more in depth descriptions and testing steps. Thank you!

**Review by jakubcolony — CHANGES_REQUESTED** [review]
Nice work @CzarekDryl, most of the issues got resolved, and I have some comments regarding the last one. 

#2862 ✅ 
image

#2879 I was not able to reproduce with both passed and failed vote outcome ✅ 
image
image

#2890 Not sure changing the fetch policy had much effect on the number of requests but after discussing with Arren I consider this resolved and to be followed up in #2900 ✅ 

#2896 The permissions needed banner should not have been removed, instead the cause of the issue needs to be resolved, which is most likely the fact that permissions are not updated in cache after they have been set for the staking extension. 

At the moment there's a regression of permissions banner not showing for staged expenditure even though permissions are indeed missing:
image

Feel free to ping me if you have any questions regarding the cache update.

**Comment by CzarekDryl** [comment]
@jakubcolony Permission changes reverted and added description

**Review by jakubcolony — CHANGES_REQUESTED** [review]
@CzarekDryl the banner still shows up for staking extension even though permissions have been set as part of the installation:
image

image

The `refetchColony` bit needs to be called after roles have been automatically set for staking extension, not after clicking on the banner (you shouldn't see it in the first place).

**Comment by CzarekDryl** [comment]
@jakubcolony Now it uses refetchColony after installing

**Review by arrenv — CHANGES_REQUESTED** [review]
@CzarekDryl Thank you for tackling these issues.

Is it possible to prevent the permissions banner from flashing up at all?

[permission-banner.webm](https://github.com/user-attachments/assets/fd76848b-2dd4-463b-a903-e3d02e5e979a)

**Comment by CzarekDryl** [comment]
@arrenv Please check it now

**Review by jakubcolony — APPROVED** [review]
LGTM, thanks for your work @CzarekDryl 👍 

image

Can confirm there's no flickering after setting permissions.

**Review by arrenv — APPROVED** [review]
@CzarekDryl The installation all went smoothly and the extension shows up with the correct permissions. Thank you for the updates.

image


I ran into this issue though when doing an advanced payment with staking. Is this unrelated? Does it need a separate issue?

image

**Pull request merged**
