### PR TITLE
fix: staking widget radio buttons colors

### PR DESCRIPTION
**Pull request by joanna-pagepro**
https://github.com/JoinColony/colonyCDapp/issues/2055

Updated colors for radio buttons

### CODE REVIEW

**Review by warrencolliver — CHANGES_REQUESTED** [review]
The buttons are the correct colours, so good work. However I noticed the outcome step widget in figma is black, whereas in the app it's red, should this be changed too?
Screenshot 2024-03-18 at 13 47 26

**Comment by joanna-pagepro** [comment]
@warrencolliver there's a separate task for that and it's already updated in a different PR
https://github.com/JoinColony/colonyCDapp/issues/2056

**Review by warrencolliver — APPROVED** [review]
Apologies, good work!

**Comment by bassgeta** [comment]
could we maybe utilize native CSS for this?
https://developer.mozilla.org/en-US/docs/Web/CSS/:checked
https://developer.mozilla.org/en-US/docs/Web/CSS/:disabled

Tailwind also has support for these [selectors](https://tailwindcss.com/docs/hover-focus-and-other-states#disabled)

**Comment by joanna-pagepro** [comment]
@bassgeta I'm not sure if it will work correctly because the disabled state is added to the input and not the label

**Comment by bassgeta** [comment]
> @bassgeta I'm not sure if it will work correctly because the disabled state is added to the input and not the label

I mean since the label is actually the next sibling of the input we could use the `+` css selector. Maybe worth a shot, since className as a function feels unconventional

**Comment by joanna-pagepro** [comment]
@bassgeta there's another wrapper inside the label that is getting the classes passed with className prop. I think that this solution is cleaner and you can still pass just a string.

**Review by melyndav — APPROVED** [review]
I checked both oppose and support flows and all looks to be corrected. Thanks @joanna-pagepro

**Review by warrencolliver — APPROVED** [review]

**Pull request merged**
