### PR TITLE
Fix: Correcting all action type button labels

### LINKED ISSUE #1626: Actions: Correcting all action type button labels
##Description 

All the action types have custom primary button labels that are currently don't match what was spec'd. This issue aims to resolve the incorrect labels and ensure they align with Figma and the Product spec. 

_Note:_ All cancel buttons should not be changed or the pending loading state (once the button is selected by the user).

Action types that need correcting:

| Action type  | Correct button label |
| ------------- | ------------- |
| Mint tokens | Mint tokens  |
| Transfer funds  | Transfer funds  |
| Create a decision  | Create agreement   |
| Manage permissions  | Update permissions   |

## Figma

Link to all action types to cross-check: https://www.figma.com/file/5V8pr7iMwXsT9L3VAZsmUt/Colony-V5?type=design&node-id=2890-252544&mode=design&t=V9WB8knufbS8936p-4

### PR DESCRIPTION
**Pull request by warrencolliver**
## Description

This PR changes the action type button labels as outlined in the spec

**Changes** 🏗

Action Type: mint tokens
Screenshot 2024-01-10 at 11 33 54

Action Type: Transfer Funds
Screenshot 2024-01-10 at 11 35 16

Action Type: Edit Colony Details
Screenshot 2024-01-10 at 11 35 49

Action Type: Create Decision
Screenshot 2024-01-10 at 11 36 39

Action Type: Manage Permissions
Screenshot 2024-01-10 at 11 37 30

**Updates**

Action Type: Edit Colony Details - Revert 'Save details' back to 'Edit Details'
Screenshot 2024-01-10 at 14 26 55

Action Type: Create Decision - Dedicate a button to this action instead of using the generic button.createAction button
Screenshot 2024-01-10 at 14 28 11

Resolves #1626

### CODE REVIEW

**Review by bassgeta — APPROVED** [review]

**Review by rdig — APPROVED** [review]
All good. Congrats on your first PR :)

**Review by arrenv — CHANGES_REQUESTED** [review]
Thanks @warrencolliver.

1. The naming of `button.createAction` seems generic, perhaps we need one dedicated to agreements.

2. Can we change `Save details` back to `Edit details` please, as saving is not accurate.

**Comment by warrencolliver** [comment]
> Thanks @warrencolliver.
> 
> 1. The naming of `button.createAction` seems generic, perhaps we need one dedicated to agreements.
> 2. Can we change `Save details` back to `Edit details` please, as saving is not accurate.

I have changed 'Save details' back to 'Edit details' and have updated the Create Agreement action to have it's own button.
I've updated the PR Description (Updates section) with screenshots.

thank you @arrenv

**Review by ArmandoGraterol — APPROVED** [review]
Nice work 🎉

**Review by bassgeta — APPROVED** [review]

**Review by melyndav — APPROVED** [review]
Thanks for picking up my issue @warrencolliver, looks great!

**Review by arrenv — APPROVED** [review]
Nice, working for me! Thank you for the updates.

**Pull request merged**
