### PR TITLE
fix: colony switcher ui issue fix, header z-index update

### PR DESCRIPTION
**Pull request by joanna-pagepro**
https://github.com/JoinColony/colonyCDapp/issues/1926
https://github.com/JoinColony/colonyCDapp/issues/1932

### CODE REVIEW

**Review by ArmandoGraterol — APPROVED** [review]
Apart from what Mel pointed out, code is looking good to me so I'm approving 👍

**Comment by joanna-pagepro** [comment]
@melyndav it was fixed in https://github.com/JoinColony/colonyCDapp/pull/1950, but it's not merged yet.

**Review by melyndav — DISMISSED** [review]
Thanks @joanna-pagepro. Approved given the issue is being fixed in a separate PR. 👍

**Review by ArmandoGraterol — APPROVED** [review]

**Review by melyndav — APPROVED** [review]
Re-approving @joanna-pagepro.

**Pull request merged**
