### PR TITLE
Fix user hub stakes tab advanced payments

### LINKED ISSUE #2536: Missing details for creating an advanced payment in the Stakes tab
## Steps to reproduce

1. Ensure you have the Staking advanced payments extension enabled.
2. Create an advanced payment (Payment builder) action.
3. Use the staking decision method to create it.
4. Check the action details in the Userhub Stakes tab.

This PR https://github.com/JoinColony/colonyCDapp/pull/2340 adds the UI to be able to create Advanced payments using staking. Although, you should be able to replicate with the pseudo UI on this feature branch [feat/advanced-payments-ui](https://github.com/JoinColony/colonyCDapp/tree/feat/advanced-payments-ui)

## Expected behaviour

* The title of the action should show in the Stakes tab for an expenditure created using staking.
* The metadata of the action should include the action details.
* The status pill should be accurate.

## Actual behaviour

* The title of the action is missing.
* The Metadata of the transaction is missing.
* Status pill is missing.

image

image

### PR DESCRIPTION
**Pull request by davecreaser**
## Description

- Ensure stakes made for an advanced payment have all details shown properly in the user hub stakes tab

## Testing

* Ensure you have the Staking advanced payments extension enabled.
* Create an advanced payment (Payment builder) action. You can use any number of payments / users / tokens.
* Use the staking decision method to create it.
Screenshot 2024-07-15 at 17 55 18

* Check the action details in the Userhub Stakes tab. The name, metadata description and status should all be correct.
Screenshot 2024-07-15 at 17 55 46

* Go through all the steps in the action sidebar to complete the action fully and reclaim your stake.
Screenshot 2024-07-15 at 17 56 41

* The status in the stakes tab should be updated.
Screenshot 2024-07-15 at 17 56 19

## Diffs

**Changes** 🏗

* Ensure action metadata is created when a staked expenditure is made
* Load and display expenditure data when needed in the stakes tab of the user hub
* Ensure the correct user stake status is shown for expenditures in the stakes tab of the user hub

Resolves #2536

### CODE REVIEW

**Review by rdig — CHANGES_REQUESTED** [review]
Tested this and UI wise everything seems to be working, however the transaction to reclaim your stake fails gas estimation

Screenshot from 2024-07-16 20-07-00
Screenshot from 2024-07-16 20-06-28

As I mentioned above the actual transaction fails

Screenshot from 2024-07-16 20-07-37
Screenshot from 2024-07-16 20-07-55

Here's the error in copy-able form:
```js
Error: cannot estimate gas; transaction may fail or may require manual gas limit [ See: https://links.ethers.org/v5-errors-UNPREDICTABLE_GAS_LIMIT ] (reason="Error: VM Exception while processing transaction: reverted with reason string 'staked-expenditure-nothing-to-claim'", method="estimateGas", transaction={"from":"0xb77D57F4959eAfA0339424b83FcFaf9c15407461","to":"0xE12c7545951a32a6fC6B1C68F273DA692afedbfA","data":"0x85c6ccca0000000000000000000000000000000000000000000000000000000000000021","accessList":null}, error={"reason":"processing response error","code":"SERVER_ERROR","body":"{\"jsonrpc\":\"2.0\",\"id\":194,\"error\":{\"code\":-32603,\"message\":\"Error: VM Exception while processing transaction: reverted with reason string 'staked-expenditure-nothing-to-claim'\",\"data\":{\"message\":\"Error: VM Exception while processing transaction: reverted with reason string 'staked-expenditure-nothing-to-claim'\",\"data\":\"0x08c379a0000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000237374616b65642d657870656e6469747572652d6e6f7468696e672d746f2d636c61696d0000000000000000000000000000000000000000000000000000000000\"}}}","error":{"code":-32603,"data":{"message":"Error: VM Exception while processing transaction: reverted with reason string 'staked-expenditure-nothing-to-claim'","data":"0x08c379a0000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000237374616b65642d657870656e6469747572652d6e6f7468696e672d746f2d636c61696d0000000000000000000000000000000000000000000000000000000000"}},"requestBody":"{\"method\":\"eth_estimateGas\",\"params\":[{\"from\":\"0xb77d57f4959eafa0339424b83fcfaf9c15407461\",\"to\":\"0xe12c7545951a32a6fc6b1c68f273da692afedbfa\",\"data\":\"0x85c6ccca0000000000000000000000000000000000000000000000000000000000000021\"}],\"id\":194,\"jsonrpc\":\"2.0\"}","requestMethod":"POST","url":"http://localhost:8545"}, code=UNPREDICTABLE_GAS_LIMIT, version=providers/5.7.1)
```

However, the stakes take still shows up correctly as "claimed"

Screenshot from 2024-07-16 20-08-08

Please investigate the gas estimation issue, as while I'm not sure it originated on this branch, it's something we need to be aware of

**Comment by davecreaser** [comment]
@rdig Thanks for the review! Strange that it isn't reclaiming properly for you though, I didn't run into that at all while developing. I've just tried it a few times to see if I can trigger the error now too, but it's working fine each time:

Screenshot 2024-07-17 at 14 26 58
Screenshot 2024-07-17 at 14 28 37
Screenshot 2024-07-17 at 14 29 45

**Review by rdig — CHANGES_REQUESTED** [review]
Retested this and it's exactly the same deal again

Screenshot from 2024-07-17 20-44-54
Screenshot from 2024-07-17 20-45-05
Screenshot from 2024-07-17 20-45-47
Screenshot from 2024-07-17 20-45-54

Am I perhaps doing something wrong when setting up the payment ?

Although I want to point up the the error message is pointing at there being nothing there to claim: `staked-expenditure-nothing-to-claim'`

Screenshot from 2024-07-17 20-46-38

Maybe we can ask someone else for their review as to ensure is not either my machine or your machine that is acting up

**Comment by davecreaser** [comment]
@rdig Very odd. I'm still unable to replicate the claiming error you're seeing, and it looks like Sam also didn't have it.

I checked in the contracts and this is the only place that error is thrown: https://github.com/JoinColony/colonyNetwork/blob/eb3620dbc1232e896f8e4d028889d058363cd0eb/contracts/extensions/StakedExpenditure.sol#L145

So it looks like you're getting some error with the stake creator being incorrect? Not entirely sure how that would happen tbh... Could it be a simple case of reinstalling npm packages and restarting docker etc?

**Review by Nortsova — APPROVED** [review]
Hi @davecreaser ! Thanks for this one ✨

Can confirm that testing functionality works for me:

image
image

**Review by rdig — APPROVED** [review]
Re-tested this on my laptop, managed (I think) to make it work.

The only difference from the other instances I've tested is that the first claim (amy in this case) was payed automatically. On my previous tests I had to click the button, which generated the error

Screenshot from 2024-07-18 20-24-34
Screenshot from 2024-07-18 20-25-20
Screenshot from 2024-07-18 20-25-34
Screenshot from 2024-07-18 20-26-17
Screenshot from 2024-07-18 20-26-33

But then again, it seems that I'm the outlier here, so we can just assume that this is working as expected.

Nicely done.

**Pull request merged**
