### PR TITLE
Fix: Reveal domain for manage tokens action

### LINKED ISSUE #2830: Manage tokens activity item is missing team
## Steps to reproduce

1. Create a Manage tokens action.
2. Check the activity feed page.
3. Note the team field in the table.

## Expected behaviour

* The "General" team should be visible in the activity feed.

## Actual behaviour

* There is no team pill showing at all for Manage tokens.

image

### PR DESCRIPTION
**Pull request by rumzledz**
## Description

Screenshot 2024-08-13 at 18 13 58

## Testing

> [!IMPORTANT]
> This requires the following block ingestor changes: [block-ingestor#267 Fix: Reveal domain for manage tokens action](https://github.com/JoinColony/block-ingestor/pull/267)

1. Bring up the Action form
2. Set the Action type to Manage tokens
3. Add a token
4. Visit the Activity page `/{colonyName}/activity`
5. Verify that the the entry for Manage tokens is showing the domain

Resolves #2830

### CODE REVIEW

**Review by mmioana — APPROVED** [review]
Really cool @rumzledz 👏 I can confirm the domain appears after switching to your branch
Screenshot 2024-08-14 at 09 12 15
Screenshot 2024-08-14 at 09 13 10

**Review by Nortsova — DISMISSED** [review]
Great work @rumzledz ! 👏 Can confirm that the team is shown now!

image

**Review by bassgeta — APPROVED** [review]
Nice and simple :ok_hand: 
image

**Comment by rumzledz** [comment]
Hey @bassgeta @mmioana @Nortsova , I had to rebase the checks went away. Can you please have a look again?

**Review by bassgeta — APPROVED** [review]
Reapproving the hashes :D 
Still working as intended :muscle: 
image

**Review by Nortsova — APPROVED** [review]
Retested again, everything works as expected. Thanks @rumzledz 🙌

| Before | After |
| ------- | -------- |
| image | 
image
 |

**Review by iamsamgibbs — APPROVED** [review]
Nice job! Tested adding a token via action and removing a token via motion, both working as expected!

Screenshot 2024-08-28 at 20 46 34

**Pull request merged**
