### PR TITLE
Manage Reputation feature

### PR DESCRIPTION
**Pull request by ArmandoGraterol**
This is the feature branch for the Manage Reputation functionality.

### CODE REVIEW

**Comment by arrenv** [comment]
@ArmandoGraterol What is left to still do on Manage Reputation?

**Comment by rdig** [comment]
I think this needs a rebase though

**Review by rdig — APPROVED** [review]
PARTTYYY! :tada:

**Review by bassgeta — APPROVED** [review]
S H I P I T

**Pull request merged**
