### PR TITLE
Fix[15637012]: action type dropdown menu

### PR DESCRIPTION
**Pull request by KornelKwiatkowski**
## Description

task: https://tw.auroracreation.com/app/tasks/15637012

Fixed UI issues with action type dropdown menu

Changes 🏗

image

image

### CODE REVIEW

**Comment by KornelKwiatkowski** [comment]
@arrenv comment from original PR:

Thanks @KornelKwiatkowski, I just noticed an issue with the warning icon alignment.

In this PR:
image

Design:
image

**Review by TomaszChmielPagepro — DISMISSED** [review]

**Comment by KornelKwiatkowski** [comment]
@arrenv I fixed issue with padding :)

**Review by krawczykkatarzyna — APPROVED** [review]

**Review by TomaszChmielPagepro — APPROVED** [review]

**Review by rdig — CHANGES_REQUESTED** [review]
- Missing translation string for managing colony objective
Screenshot from 2023-11-09 15-52-36

**Comment by KornelKwiatkowski** [comment]
Hi @rdig, thanks for feedback.

Even though it's a small thing, it's not related to the current task. I think you'll agree that if we all start making small changes in our pull requests that aren't related to the main task, it could cause conflicts and unnecessary duplications. I will ask Adrian to create a separated task for this :)

**Review by rdig — APPROVED** [review]

**Comment by AdrianDudko** [comment]
@rdig I've created a separate task in our project management tool (Teamwork) for the issue mentioned in this comment https://github.com/JoinColony/colonyCDapp/pull/1283#pullrequestreview-1722591663.

Your remark won't be missed, just will be handled in another task. 
https://tw.auroracreation.com/#/tasks/15661659

cc: @KornelKwiatkowski

**Pull request merged**
