### PR TITLE
Feat: Add share action functionality

### LINKED ISSUE #2510: Add copy functionality to completed actions
### Story

As a USER, I would like to be able to easily copy action URLs to share them.

### Description

We want to be able to make sharing actions with others much easier, there is sharing functionality designed, however it depends on the Notifications feature to be in place. So, in the meantime, we would like to add the icon that simply copies the URL of the action, then enrich it in future.

So, the while the design shows a modal, we just want want the icon to be visible, with the hover state and the copied confirmation tooltip as exists elsewhere. Shown as of the placement and copy of the screenshot included in this issue.

### Design

[Figma link](https://www.figma.com/design/BNYMCxFDpd5AA1YAeKcgi3/Sharing-%26-inviting?node-id=3501-48914&t=cgPPrWPShWVEr9xK-4)

image

image

### This issue is complete when...

- [ ] The share icon is visible on all completed actions.
- [ ] The share icon has a hover state.
- [ ] Clicking on the share icon copies the URL of the action, including the transaction hash.
- [ ] After copying, the tooltip should appear below the icon, confirming that the URL has been copied.

### PR DESCRIPTION
**Pull request by mmioana**
Add share icon on action sidebar
Add translations

## Description

- Add share icon to allow copy-to-clipboard functionality for the action url

## Testing

* Step 1. Create a new action
* Step 2. After action got created, check the share icon appears in the action sidebar header
* Step 3. Upon clicking the icon, check url is copied to clipboard

Resolves #2510

### CODE REVIEW

**Review by melyndav — DISMISSED** [review]
Hey @mmioana 🐰 

Nice work on this PR! Everything looks and works as expected. I can copy and use the URL with no issues. Thanks for your work on this.

**Review by bassgeta — DISMISSED** [review]
Sharing is caring, now with actions too! Nice one :ship:

**Review by davecreaser — DISMISSED** [review]
Nice work! Tested and working as expected 🤝

**Review by rdig — DISMISSED** [review]
Mostly good, besides the mismatched message descriptors.

Screenshot from 2024-06-19 21-02-29

However when testing this I noticed that the colony dashboard share icon has a "hover" tooltip (shows up when howevering the icon) plus one that shows up after you clicked it
Screenshot from 2024-06-19 21-02-39
Screenshot from 2024-06-19 21-02-43

While the action share icon, only has a tooltip once clicked (the confirmation one)
Screenshot from 2024-06-19 21-03-00

I believe both should act in the same way, and even more so, I believe they should both be the same _(`core`)_ component.

Please check with product if that is the actual spec, and if it is, please fix that

**Comment by mmioana** [comment]
> Mostly good, besides the mismatched message descriptors.
> 
> Screenshot from 2024-06-19 21-02-29
> 
> However when testing this I noticed that the colony dashboard share icon has a "hover" tooltip (shows up when howevering the icon) plus one that shows up after you clicked it Screenshot from 2024-06-19 21-02-39 Screenshot from 2024-06-19 21-02-43
> 
> While the action share icon, only has a tooltip once clicked (the confirmation one) Screenshot from 2024-06-19 21-03-00
> 
> I believe both should act in the same way, and even more so, I believe they should both be the same _(`core`)_ component.
> 
> Please check with product if that is the actual spec, and if it is, please fix that

As discussed with @melyndav no other tooltip is needed for the share icon, as we'll add a modal in the future

**Review by iamsamgibbs — APPROVED** [review]
Nice work, code looks good and working as expected.

Screenshot 2024-06-27 at 14 27 33

Screenshot 2024-06-27 at 14 28 19

**Review by rumzledz — APPROVED** [review]
I can confirm that the share button is present and when clicked, copies the transaction's URL to the clipboard. Visiting the copied URL also leads to the correct transaction. Awesome work! ✨

**Review by bassgeta — APPROVED** [review]
Nice solution, I was able to copy the URL, tooltip showing up and all the shabang! 
image

**Pull request merged**
