### PR TITLE
fix: user account area mobile styles

### PR DESCRIPTION
**Pull request by joanna-pagepro**
## Description

- User account area styles update on mobile

## Testing

* Step 1. Go to the user account page
* Step 2. Check the `User account` tab using mobile view
* Step 3. Go to the `Preferences` tab on mobile and check if it's the same as on a design.

## Diffs

**New stuff** ✨

* 

**Changes** 🏗

* Styles update for `Toast` component
* Styles update for the items that are returned from `useUserPreferencesPage` and `useUserProfilePageForm` hooks
* `allowLayoutShift` prop added to `InputProps` to avoid error text overflow

**Deletions** ⚰️

* removed redundant classNames and `!important`s

Resolves https://github.com/JoinColony/colonyCDapp/issues/2079

### CODE REVIEW

**Review by iamsamgibbs — DISMISSED** [review]
This all looks good to me. All changes match the figma designs:

Screenshot 2024-04-03 at 15 44 43

Screenshot 2024-04-03 at 15 45 33

Screenshot 2024-04-03 at 15 45 41

Screenshot 2024-04-03 at 15 46 05

No regressions on desktop either:

Screenshot 2024-04-03 at 15 52 09

Good job!

**Review by melyndav — CHANGES_REQUESTED** [review]
Hey @joanna-pagepro appreciate your work on this PR and picking up my QA issue.

Everything looks great, the only minor pick up I have is the toasts. In Figma, they match the content width and sit at the top of the content. As per Figma:

image

Currently:
image


Link to some of the first toast designs from Stage 1 - https://www.figma.com/file/6qONTE1uD9K4yoIbfFzidg/Extensions?type=design&node-id=301-40088&mode=design&t=ZAHNHNLbZbz6KlhX-4 

https://www.figma.com/file/0Fi3AaDlr3LAXBfsOXBGyk/User-Account?type=design&node-id=6401-13230&mode=design&t=mxVEFTXo1ZU1cyk2-4

**Comment by joanna-pagepro** [comment]
@melyndav @iamsamgibbs toasts position updated

**Review by iamsamgibbs — APPROVED** [review]
Thanks for the change, looks good to me!

Screenshot 2024-04-04 at 09 39 35

**Review by ArmandoGraterol — APPROVED** [review]
Looking good 👍 

FireShot Capture 282 - Account Preferences - Colony - localhost
FireShot Capture 283 - Account Profile - Colony - localhost

**Review by melyndav — APPROVED** [review]
Niccceeeee work @joanna-pagepro appreciate you cleaning up that toast positioning. Thank you for your work as always! :)

**Pull request merged**
