### PR TITLE
[Arbitrary transactions]: saga via permissions

### PR DESCRIPTION
**Pull request by Nortsova**
## Description
This PR covers the permissions flow of creating arbitrary transactions.

Block-ingestor PR: https://github.com/JoinColony/block-ingestor/pull/301

## Testing

> [!IMPORTANT] 
> This PR covers only "happy path" cases. I will create a ticket to handle errors soon.
> For some reason, the "Edit" functionality is broken. Here an issue - https://github.com/JoinColony/colonyCDapp/issues/3866

Step 1. Update `src/components/v5/common/ActionSidebar/partials/forms/ArbitraryTxsForm/partials/AddTransactionModal/useGenerateABI.ts`  line 21 to `return;` (Unfortunately, we can't get a local contract from arbiscan, so we will put it manually 🙌 )
image

Step 2. Open Arbitrary Transaction motion (Just open a random action and select Arbitrary transaction)
image

Step 3. Create transaction with: 
Contract address: `0xeF841fe1611ce41bFCf0265097EFaf50486F5111`
ABI: 
```json
[{"type":"constructor","payable":false,"inputs":[{"type":"string","name":"_name"},{"type":"string","name":"_symbol"},{"type":"uint8","name":"_decimals"}]},{"type":"event","anonymous":false,"name":"Approval","inputs":[{"type":"address","name":"src","indexed":true},{"type":"address","name":"guy","indexed":true},{"type":"uint256","name":"wad","indexed":false}]},{"type":"event","anonymous":false,"name":"Burn","inputs":[{"type":"address","name":"guy","indexed":true},{"type":"uint256","name":"wad","indexed":false}]},{"type":"event","anonymous":false,"name":"LogSetAuthority","inputs":[{"type":"address","name":"authority","indexed":true}]},{"type":"event","anonymous":false,"name":"LogSetOwner","inputs":[{"type":"address","name":"owner","indexed":true}]},{"type":"event","anonymous":false,"name":"MetaTransactionExecuted","inputs":[{"type":"address","name":"user","indexed":false},{"type":"address","name":"relayerAddress","indexed":false},{"type":"bytes","name":"functionSignature","indexed":false}]},{"type":"event","anonymous":false,"name":"Mint","inputs":[{"type":"address","name":"guy","indexed":true},{"type":"uint256","name":"wad","indexed":false}]},{"type":"event","anonymous":false,"name":"Transfer","inputs":[{"type":"address","name":"src","indexed":true},{"type":"address","name":"dst","indexed":true},{"type":"uint256","name":"wad","indexed":false}]},{"type":"function","name":"DOMAIN_SEPARATOR","constant":true,"stateMutability":"view","payable":false,"inputs":[],"outputs":[{"type":"bytes32"}]},{"type":"function","name":"PERMIT_TYPEHASH","constant":true,"stateMutability":"view","payable":false,"inputs":[],"outputs":[{"type":"bytes32"}]},{"type":"function","name":"allowance","constant":true,"stateMutability":"view","payable":false,"inputs":[{"type":"address","name":"src"},{"type":"address","name":"guy"}],"outputs":[{"type":"uint256"}]},{"type":"function","name":"approve","constant":false,"payable":false,"inputs":[{"type":"address","name":"guy"},{"type":"uint256","name":"wad"}],"outputs":[{"type":"bool"}]},{"type":"function","name":"authority","constant":true,"stateMutability":"view","payable":false,"inputs":[],"outputs":[{"type":"address"}]},{"type":"function","name":"balanceOf","constant":true,"stateMutability":"view","payable":false,"inputs":[{"type":"address","name":"src"}],"outputs":[{"type":"uint256"}]},{"type":"function","name":"burn","constant":false,"payable":false,"inputs":[{"type":"uint256","name":"wad"}],"outputs":[]},{"type":"function","name":"burn","constant":false,"payable":false,"inputs":[{"type":"address","name":"guy"},{"type":"uint256","name":"wad"}],"outputs":[]},{"type":"function","name":"decimals","constant":true,"stateMutability":"view","payable":false,"inputs":[],"outputs":[{"type":"uint8"}]},{"type":"function","name":"executeMetaTransaction","constant":false,"stateMutability":"payable","payable":true,"inputs":[{"type":"address","name":"_user"},{"type":"bytes","name":"_payload"},{"type":"bytes32","name":"_sigR"},{"type":"bytes32","name":"_sigS"},{"type":"uint8","name":"_sigV"}],"outputs":[{"type":"bytes"}]},{"type":"function","name":"getMetatransactionNonce","constant":true,"stateMutability":"view","payable":false,"inputs":[{"type":"address","name":"_user"}],"outputs":[{"type":"uint256","name":"nonce"}]},{"type":"function","name":"locked","constant":true,"stateMutability":"view","payable":false,"inputs":[],"outputs":[{"type":"bool"}]},{"type":"function","name":"mint","constant":false,"payable":false,"inputs":[{"type":"address","name":"guy"},{"type":"uint256","name":"wad"}],"outputs":[]},{"type":"function","name":"mint","constant":false,"payable":false,"inputs":[{"type":"uint256","name":"wad"}],"outputs":[]},{"type":"function","name":"name","constant":true,"stateMutability":"view","payable":false,"inputs":[],"outputs":[{"type":"string"}]},{"type":"function","name":"nonces","constant":true,"stateMutability":"view","payable":false,"inputs":[{"type":"address","name":"_user"}],"outputs":[{"type":"uint256","name":"nonce"}]},{"type":"function","name":"owner","constant":true,"stateMutability":"view","payable":false,"inputs":[],"outputs":[{"type":"address"}]},{"type":"function","name":"permit","constant":false,"payable":false,"inputs":[{"type":"address","name":"owner"},{"type":"address","name":"spender"},{"type":"uint256","name":"value"},{"type":"uint256","name":"deadline"},{"type":"uint8","name":"v"},{"type":"bytes32","name":"r"},{"type":"bytes32","name":"s"}],"outputs":[]},{"type":"function","name":"setAuthority","constant":false,"payable":false,"inputs":[{"type":"address","name":"authority_"}],"outputs":[]},{"type":"function","name":"setOwner","constant":false,"payable":false,"inputs":[{"type":"address","name":"owner_"}],"outputs":[]},{"type":"function","name":"symbol","constant":true,"stateMutability":"view","payable":false,"inputs":[],"outputs":[{"type":"string"}]},{"type":"function","name":"totalSupply","constant":true,"stateMutability":"view","payable":false,"inputs":[],"outputs":[{"type":"uint256"}]},{"type":"function","name":"transfer","constant":false,"payable":false,"inputs":[{"type":"address","name":"dst"},{"type":"uint256","name":"wad"}],"outputs":[{"type":"bool"}]},{"type":"function","name":"transferFrom","constant":false,"payable":false,"inputs":[{"type":"address","name":"src"},{"type":"address","name":"dst"},{"type":"uint256","name":"wad"}],"outputs":[{"type":"bool"}]},{"type":"function","name":"unlock","constant":false,"payable":false,"inputs":[],"outputs":[]},{"type":"function","name":"verify","constant":true,"stateMutability":"view","payable":false,"inputs":[{"type":"address","name":"_user"},{"type":"uint256","name":"_nonce"},{"type":"uint256","name":"_chainId"},{"type":"bytes","name":"_payload"},{"type":"bytes32","name":"_sigR"},{"type":"bytes32","name":"_sigS"},{"type":"uint8","name":"_sigV"}],"outputs":[{"type":"bool"}]}]
```
Method: mint(uint256)
wad (uint256): `2200000000000000000` (value in wei)

image

Step 4. Submit transaction
Step 5. Add a second transaction with the same contractAddress and ABI, (Please do not use "duplicate" functionality, I am investigating a bug with it) just select other method (I will select `lock()`)

image

Step 6. Fill other fields, add description as well
image

Step 7. Submit form

Step 8. Verify that CompletedAction "In progress" opened

Step 9. Verify that annotation is the same as you put in description field
Step 10. Verify that there are arbitrary transactions (method name could be different due to our decoding implementation - https://github.com/JoinColony/block-ingestor/pull/299, it will be improved soon)
Step 11. Verify that Action Type is `MAKE_ARBITRARY_TRANSACTION `

Screenshot 2024-12-05 at 21 08 45

Step 12. Navigate to the Incoming page and verify that 2.2 CREDS is received as the result of the mint token contract call.
image

## TODO

- [ ] Implement contract error handling
- [ ] Investigate meatball functionality bugs (https://github.com/JoinColony/colonyCDapp/issues/3866) 
- [ ] Improve decode function

Contributes to #3535

### CODE REVIEW

**Review by jakubcolony — CHANGES_REQUESTED** [review]
Very nicely done, especially given it's your first shot at sagas & block-ingestor! 👏 

It looks like there's a small regression around filtering available functions, the dropdown should not display `view` or `pure` functions such as decimals():
image


image

The action type and initiator details look good:
image

However, argument of type `address` was stored as escaped string, could you update the processing logic to unescape it first?
image

**Review by jakubcolony — APPROVED** [review]
Nice work on the fixes, looks good to me! 👍 

View and pure functions are filtered out ✅ 
image

----

Address argument is unescaped before storing ✅ I also came across an even worse collision than what we've seen so far, `approve(address,uint256)` was misclassified as `watch_tg_invmru_2f69f1b(address,address)`, so a function with completely different arguments. That means we'll need to store potential matches not only for function names, but also their arguments.

image

image


----

Encoded function data is now in the DB ✅

**Review by iamsamgibbs — APPROVED** [review]
Nice job getting is all working @Nortsova ! Congratulations on your first saga!

Everything is getting correctly logged:

Screenshot 2024-12-10 at 11 47 13

Screenshot 2024-12-10 at 11 47 46

Shows up in the activity feed too:

Screenshot 2024-12-10 at 11 48 10

And the tokens are indeed here:
 
Screenshot 2024-12-10 at 11 48 22

However, I did use the `unlock` method and the token is still locked. I assume this is what the `unlock` method should do in this scenario, but I'm not 100% sure.

Screenshot 2024-12-10 at 11 48 37

I've found a few issues, some of which are sort of related to the saga, so could be worth fixing here, others are form UI issues, either way feel free to either fix things here or create new issues, however you best see fit!

The transaction in the UserHub is missing the translation string in the accordion header, but also the {title} in the first transaction.

Screenshot 2024-12-10 at 12 07 20

No notifications are sent:

Screenshot 2024-12-10 at 12 06 30

The decision methods don't seem to have been setup properly for the form, as a user with no permissions I should see the validation error rather than the empty select:
 
Screenshot 2024-12-10 at 11 49 15

Like this:
 
Screenshot 2024-12-10 at 12 15 14

It will need adding to the `PERMISSIONS_NEEDED_FOR_ACTION` variable.

Definitely unrelated to this PR, but just a note for the future that the action type will need to be added to this list here as part of the work to get the description messages showing in the activity feed:
Screenshot 2024-12-10 at 12 18 02

Also noticed some focus state issues in the form:

Screenshot 2024-12-10 at 12 19 34

Screenshot 2024-12-10 at 11 16 44

https://github.com/user-attachments/assets/2619fd17-0881-4aad-9071-126766a46824

Great job on all of this!

**Review by rdig — APPROVED** [review]
Everything works as you said. Nicely done! :100: 

Screenshot from 2024-12-11 16-14-23
Screenshot from 2024-12-11 16-14-49
Screenshot from 2024-12-11 16-18-26
Screenshot from 2024-12-11 16-18-36
Screenshot from 2024-12-11 16-19-10
Screenshot from 2024-12-11 16-19-31

**Comment by Nortsova** [comment]
Thank you all, for your review!

I added a permissions error (as @iamsamgibbs mentioned): 
image

However, some other UI fixes I decided to put in a separate ticket: 
https://github.com/JoinColony/colonyCDapp/issues/3917

**Pull request merged**
