### PR TITLE
fix: popover position, loading, copy, menu item

### PR DESCRIPTION
**Pull request by CzarekDryl**
https://tw.auroracreation.com/app/tasks/15763226
https://tw.auroracreation.com/app/tasks/15577569

**Changes** 🏗

* Member popover position changed to left instead of center
* Changed copy
* Moved permissions link to members menu
* Permission page loading

### CODE REVIEW

**Review by iamsamgibbs — DISMISSED** [review]
All looks good to me! 🎉

**Review by warrencolliver — DISMISSED** [review]
Can't find any issues with this. Good work

**Review by melyndav — CHANGES_REQUESTED** [review]
Hey @CzarekDryl!Great start on this.

With the skeleton loader for all sizes (desktop, mobile etc) can the loading elements match the same size as the actual content? Currently the avatar and other skeleton elements is bigger which causes a change to the UI when the actual content loads in.

**Review by iamsamgibbs — CHANGES_REQUESTED** [review]
The loading skeleton is looking a lot better now.

It is possible to hide the "No results available" message whilst loading without breaking anything? It briefly shows when first loading the page.


https://github.com/JoinColony/colonyCDapp/assets/34915414/dee046e6-9ec1-43eb-b5da-f7c78bc079e8

**Review by iamsamgibbs — APPROVED** [review]
Nice one, thank you!

**Pull request merged**
