### PR TITLE
fix: longer title should break line

### PR DESCRIPTION
**Pull request by mksawic**
## Description

https://tw.auroracreation.com/app/tasks/15695338

[Figma Link](https://www.figma.com/file/5V8pr7iMwXsT9L3VAZsmUt/Colony-v5?type=design&node-id=10818-342705&mode=design&t=7yZOOa1vH5S971Td-4)
image

## Testing

Check if long action title breaks into new line but user is not able to insert new lines manually.

* Step 1. Open create action side panel and choose any action type.
* Step 2. Type in long title ➡️ Line should break at the end of input
* Step 3. Try to insert new line manually ➡️ New line should be prevented
* Step 4. Try to paste a copied text with line breaks ➡️ Line breaks should be removed

**Changes** 🏗

* Changed `input` to `textarea` for action title
* Added `onKeyDown` event for action title to prevent entering new line
* Added `onChange` event to prevent pasting text with line breaks

### CODE REVIEW

**Review by iamsamgibbs — CHANGES_REQUESTED** [review]
Great start to this ticket! Wrapping to a new line is working great, and tested pasting in text with a line break and that is all working as expected.

I've noticed a couple of issues with the error validation.

* If you type a title before selecting an action, you won't get an invalid state until you select an action and try changing the title again.
* If you exceed the character limit, the text will turn red, but the max character limit error message won't appear until you actually try to submit the form. (After this the error will update correctly onChange which is great).

https://github.com/JoinColony/colonyCDapp/assets/34915414/9f944123-574c-4cee-8b37-19e5234d01c1

**Review by ArmandoGraterol — DISMISSED** [review]
Other than what Sam pointed out, this looks good to me

**Review by melyndav — CHANGES_REQUESTED** [review]
Hey @mksawic, thanks for your work on this.

Can you please updated the error text to show in the error summary section 'Title must not exceed 60 characters'.

**Comment by mksawic** [comment]
@iamsamgibbs @melyndav - Changed as requested. Now create action sidebar should act like following test scenario

1. Open create action side panel and enter title over 60 characters ➡️ Text turns red and error message should display
2. Fix title and select action type. Try to enter incorrect value for some field ➡️ Field turns red and error message should display
3. Fix field error and leave some required field empty. Submit form ➡️ Required field turns red and error message is displayed. Also info that something went wrong is added

https://github.com/JoinColony/colonyCDapp/assets/58193726/619a0797-2856-41ea-8d0e-73e8cc790339

**Review by iamsamgibbs — APPROVED** [review]
Thanks for the changes, looks good to me! Working as expected

**Review by melyndav — CHANGES_REQUESTED** [review]
Hey @mksawic 

The styling of this error state should be consistent with the other input error states when the error is on it's own

image

Example: 
image

**Comment by mksawic** [comment]
@melyndav state should be consistent right now

**Review by ArmandoGraterol — APPROVED** [review]

**Review by melyndav — APPROVED** [review]
@mksawic thanks for the fixes on my request! Looks great 👍

**Pull request merged**
