### PR TITLE
Feat: Hook up new pill on payment group

### PR DESCRIPTION
**Pull request by iamsamgibbs**
## Description

When discussing #3318 with Mel, realised the "New" pill should also appear on the payment group items as part of the new navigation.

This PR hooks up the new pill (99% of the work had already been done by @Nortsova when originally building this! 🎉 ) it just needed passing to the component.

## Testing

Click "Make payment" from the menu. Check "Advanced payments" has a "New" pill in the action sidebar.

Screenshot 2024-10-15 at 10 17 20

## Diffs

**Changes** 🏗

isNew prop is passed to GroupedActionItem component.

### CODE REVIEW

**Review by rdig — APPROVED** [review]
Nicely done!

Screenshot from 2024-10-16 11-57-41
Screenshot from 2024-10-16 11-57-47

**Review by mmioana — CHANGES_REQUESTED** [review]
Awesome you spotted this @iamsamgibbs 🎉 

The `New` pill is now showing up 🥇 
Screenshot 2024-10-16 at 11 05 04

However I noticed there is a slight mismatch compared to Figma, where the pill is centred with the action icon
Screenshot 2024-10-16 at 11 07 41

**Comment by iamsamgibbs** [comment]
Eagle eyes @mmioana ! Fixed!

**Review by Nortsova — APPROVED** [review]
Thank you @iamsamgibbs ✨

Looks perfect!
image

**Review by mmioana — APPROVED** [review]
Thanks for the fast fix @iamsamgibbs now it's pixel-perfect 🥇✨ 

Screenshot 2024-10-17 at 13 11 49

**Review by mmioana — APPROVED** [review]

**Review by rdig — APPROVED** [review]

**Review by Nortsova — APPROVED** [review]

**Review by rdig — APPROVED** [review]

**Review by mmioana — APPROVED** [review]

**Review by Nortsova — APPROVED** [review]

**Pull request merged**
