### PR TITLE
Fix: Update username validation message

### LINKED ISSUE #3312: [Create Profile]: Unclear validation message shown in username field
## Steps to reproduce

1. Open create the user profile
2. Open Create your Colony profile
3. Enter special characters (spaces and special symbols) in the username field
4. Observe the validation message displayed

## Expected behaviour

*  We might show a more specific message, e.g. "Only letters and numbers allowed"

## Actual behaviour

* The message "A valid username is required" is displayed, which is unclear

image

### PR DESCRIPTION
**Pull request by iamsamgibbs**
## Description

The previous username validation message was too vague, this PR updates the validation to be more descriptive and adds a minimum character count.

## Testing

* Step 1 - Connect to a wallet (Dev wallet 4 onwards) without a profile and create a new profile. Enter a username with either fewer than 3 characters, more than 30, or includes special characters.

Screenshot 2024-11-22 at 08 38 11

* Step 2 - Either finish creating a profile, or connect to a wallet with a profile already created.
* Step 3 - Go to the manage profile page.
* Step 4 - Open: `src/components/frame/v5/pages/UserProfilePage/partials/UserAccountPage/hooks.tsx` and change line 92 to `canChangeUsername: true,` - the username field should now be editable.
* Step 5 - Check the same validation applies and the same messages appear.

Screenshot 2024-11-22 at 14 53 44

## Diffs

**Changes** 🏗

* Updated username validation message
* Added minimum character count validation

Resolves #3312

### CODE REVIEW

**Review by bassgeta — APPROVED** [review]
Nice and to the point :sunglasses: 
image

Additionally, do we wanna pull this validation to the user account page too? `UserProfilePage/validation.ts` :eyes: 
image
Maybe as a separate issue if it would be too much work

**Review by rdig — APPROVED** [review]
All good, both on the user profile creation, and later on username update

Screenshot from 2024-11-22 17-46-21
Screenshot from 2024-11-22 17-45-37

**Review by rdig — APPROVED** [review]
Still good from my side

**Review by mmioana — APPROVED** [review]
Thanks for your fast changes @iamsamgibbs 🫶 

The username field on both `Create profile` and `Profile` pages has the correct behaviour

Screenshot 2024-11-26 at 16 17 09
Screenshot 2024-11-26 at 16 17 19

https://github.com/user-attachments/assets/3024686a-3cd3-4532-b83c-7d20dea6f4f9

Awesome work as always 🥇

**Review by bassgeta — APPROVED** [review]
Nice job unifying both of them, still works good :ok_hand: 
image
(my dev env crashed and I couldn't grab screenshots for creating a new profile, but I can confirm that works too :sweat_smile: )

**Pull request merged**
