### PR TITLE
fix: completed permissions action

### PR DESCRIPTION
**Pull request by joanna-pagepro**
## Description

Fixes for issues related to completed permissions action

## Testing

* Step 1. Create a Manage permission action.
* Step 2. Review the completed state of the action.

## Diffs

**New stuff** ✨

* 

**Changes** 🏗

* `direction` field includes `rolesChanged` value now
* `title` and `description` of the action are now using the same translations as in the edit state
* if no role is added to the `userColonyRoles` array, `Remove permissions` is set as the `Permissions` field value instead of `Custom`

**Deletions** ⚰️

* `rolesChanged` field from description 
* `ActionTitleMessageKeys.RolesChanged`

## TODO

Resolves https://github.com/JoinColony/colonyCDapp/issues/2313

### CODE REVIEW

**Review by melyndav — CHANGES_REQUESTED** [review]
Hey @joanna-pagepro great start on this!

By default, the metadata shows 'remove permissions' before selecting to remove or add. Can the metadata please show the following by default:

Manage permissions for user in team by [USER] 

Everything else seemed to be working as expected.

image

**Comment by joanna-pagepro** [comment]
@melyndav done. Please check if it's ok.

**Review by iamsamgibbs — APPROVED** [review]
All looks good to me! Default metadata is correct:

Screenshot 2024-05-07 at 09 35 17

And completed action looks good:

Screenshot 2024-05-07 at 09 36 13

**Review by arrenv — APPROVED** [review]
@joanna-pagepro All looks good on my end! Thank you :)

**Review by ArmandoGraterol — APPROVED** [review]
Looks good to me 👌

**Review by melyndav — APPROVED** [review]
Approving from my side @joanna-pagepro! Great work as always :)

**Pull request merged**
