### PR TITLE
fix: input outline, hide pagination

### PR DESCRIPTION
**Pull request by CzarekDryl**
https://tw.auroracreation.com/app/tasks/15741061

**Changes** 🏗

* Removed default input outline on focus
* Hide pagination while there is no enough items

Resolves [1695](https://github.com/JoinColony/colonyCDapp/issues/1695)

### CODE REVIEW

**Review by ArmandoGraterol — DISMISSED** [review]
LGTM 👍

**Review by jakubcolony — DISMISSED** [review]
Nice work, code looks good, but please wait for Mel's approval before merging as I can see there's some ongoing discussion in the original issue. Thanks!

**Review by melyndav — CHANGES_REQUESTED** [review]
Hey @CzarekDryl!

Thanks for picking up this issue.

1. The pagination has been fixed, thank you!

2. The search input has also been fixed but now it's active when I trigger the filter button. It should only be active when the user selects the input to actively search. This aligns the interaction with all the other inputs across the site.

image

**Review by ArmandoGraterol — APPROVED** [review]

**Review by melyndav — APPROVED** [review]
Thanks for the updates @CzarekDryl. This one is good to go! 👍

**Review by rdig — APPROVED** [review]
All good

**Review by jakubcolony — APPROVED** [review]

**Review by ArmandoGraterol — APPROVED** [review]

**Review by warrencolliver — APPROVED** [review]
looks good to me

**Review by melyndav — APPROVED** [review]
Re-approving @CzarekDryl 👍

**Pull request merged**
