### PR TITLE
fix: pending button ui, release modal box

### PR DESCRIPTION
**Pull request by CzarekDryl**
## Description

- In this PR I've fixed only UI part. Jakub told me to put the rest on hold and he will fix rejection/fail action.

## Testing

* Create payment builder action
* Check for pending buttons instead of spinners

## Diffs

**Changes** 🏗

* Changed default spinner with pending button

## TODO

- Handle action reject/fail

Resolves [https://github.com/JoinColony/colonyCDapp/issues/2389](https://github.com/JoinColony/colonyCDapp/issues/2389)

### CODE REVIEW

**Review by iamsamgibbs — CHANGES_REQUESTED** [review]
Looks good to me, I think the only one missing is the make payment button which is still a spinner.
 
Screenshot 2024-05-24 at 08 48 01

The others all look good though.

 
Screenshot 2024-05-24 at 08 46 56
Screenshot 2024-05-24 at 08 47 14
Screenshot 2024-05-24 at 08 43 29

**Review by marcocolony — APPROVED** [review]
Looking good @CzarekDryl !

Export-1716846698491

Export-1716846893524

**Comment by CzarekDryl** [comment]
@iamsamgibbs Please take a look at this one :)

**Review by iamsamgibbs — APPROVED** [review]
Looks good to me!

Screenshot 2024-05-28 at 10 20 11

**Pull request merged**
