### PR TITLE
feat: added staged extension page

### PR DESCRIPTION
**Pull request by CzarekDryl**
## Description

- Added staged payments extension page

## Testing

* Go to staged payments extension page from extensions listing

Resolves https://github.com/JoinColony/colonyCDapp/issues/2735

### CODE REVIEW

**Review by rdig — APPROVED** [review]
Tested this and it looks as expected. Nicely done.

Screenshot from 2024-08-02 16-05-09
Screenshot from 2024-08-02 16-05-20
Screenshot from 2024-08-02 16-06-37
Screenshot from 2024-08-02 16-07-01

**Review by melyndav — CHANGES_REQUESTED** [review]
Hey @CzarekDryl nice start on this one! A couple of minor updates.

1. The payment pill next to the extension title should be styled to match all the other extensions as per Figma:

image

--

2. The staged avatar should be green also to match Figma: 

image

--

3. This and the other payment extensions should be grouped on the main extensions landing page under 'Payments' as per Figma.

image
 
 
image

Link for reference:
https://www.figma.com/design/6qONTE1uD9K4yoIbfFzidg/Extensions?node-id=1908-21184&t=iqNqWC5gVVuoXdPz-4


(https://www.figma.com/design/6qONTE1uD9K4yoIbfFzidg/Extensions?node-id=2155-15496&t=iqNqWC5gVVuoXdPz-4)

**Comment by CzarekDryl** [comment]
@melyndav Now everything should be fine

**Review by melyndav — APPROVED** [review]
Hey @CzarekDryl! I appreciate you making these updates, nice work! All are done, so a nice approval from my end! 🎇

**Pull request merged**
