### PR TITLE
Refactor Arbitrum Specific Urls

### PR DESCRIPTION
**Pull request by rdig**
## Intro Note

This PR is part of the set that will be opened by me to (re)introduce all the changes made to support the Arbitrum deployment, from the `master-arbitrum` branch back into `master` so that the two branches can be _(more or less)_ identical 

We need to run two branches, since AWS enforces one deployment per branch, meaning we can't run both the `Gnosis` and `Arbitrum` deployment from the same branch.

This will get cleaned up, once we get to Multichain and we will be back to only supporting one main deployment _(which itself will support multiple networks, whatever form this might take)_

## Current PR Details

This PR updates the initial URLs we were using for Arbitrum to point to the various block explorer endpoints, as well as refactor the `getBlockExplorerLink` removing most of it's legacy logic and simplifying it's code.

Testing this is easier done in production, by going to any place where we link to an external token, address or transaction. One of the fastest place where you can access this is via the token popup:

Screenshot from 2024-04-30 17-04-32

Alternatively, you can **test this locally** as well, however, if you still use the local dev chain, you won't get a proper URL generated for the block explorer

### CODE REVIEW

**Review by jakubcolony — APPROVED** [review]
Changes look sensible, in production all the URLs work but I noticed there's a double slash in the URL:
image

**Comment by rdig** [comment]
Nice catch, I'll look into that

**Comment by rdig** [comment]
@jakubcolony fixed

**Review by jakubcolony — DISMISSED** [review]

**Review by ArmandoGraterol — DISMISSED** [review]
Nice changes! Looking good to me 👍

**Pull request merged**
