### PR TITLE
Fix: Remove `Available funds` copy from tokens dropdown

### PR DESCRIPTION
**Pull request by mmioana**
## Description

On production, the UI of the token dropdown across all relevant actions and inside tables breaks on mobile when there are large sums of tokens and long token symbols. 

image

This PR aims to fix this issue.

- [X] The 'Available funds:' portion of the text should be removed across all responsive sizes. Leaving the token amount and the token symbol only as per the design below:

image

Figma link: 
https://www.figma.com/design/l1dOM5qiQYwF0ElvKDqqjg/Design-System---Colony-v3?node-id=1782-1807&t=vXcO4MJs6WQh4eCa-4

- [X] The spacing between the 'Available tokens' heading and the first token in the list should be 16px. Currently it's 8px. - note this is already in place

image

## Testing

TODO: Please try to create any `payment/mint tokens/transfer funds` action. 

* Step 1. Click on the token in the action form
Screenshot 2024-10-04 at 14 32 46

* Step 2. Check the `Available funds:` copy is no longer shown
* Step 3. Also check the spacing between the `'Available tokens` title and the first token in the list is `16px` - there are no changes done in this PR related to it
Screenshot 2024-10-04 at 14 20 58
Screenshot 2024-10-04 at 14 21 05
* Step 4. Check this dropdown on tablet and mobile and compare it to [Figma](https://www.figma.com/design/l1dOM5qiQYwF0ElvKDqqjg/Design-System---Colony-v3?node-id=1782-1807&node-type=frame&t=fWgypvRlTQMXi03H-0) 

## Diffs

**Changes** 🏗

* Removed usage of `actionSidebar.availableFunds` from `TokenItem`

**Deletions** ⚰️

* Remove `actionSidebar.availableFunds` translation

Resolves [#2960](https://github.com/JoinColony/colonyCDapp/issues/2960)

### CODE REVIEW

**Review by iamsamgibbs — DISMISSED** [review]
Thanks for fixing this up! It looks a lot better:

Desktop: (I edited the CREDS symbol to check how it handled extra long symbol names, even though this shouldn't be possible)
Screenshot 2024-10-07 at 10 49 27

Mobile:
Screenshot 2024-10-07 at 10 49 55

The only change I would suggest is adding a min-width on desktop so that it better matches the figma design and has some extra space between the symbol and the amount:

Screenshot 2024-10-07 at 10 50 10

**Review by rdig — DISMISSED** [review]
Nicely done! Works as expected.

Screenshot from 2024-10-08 12-31-04
Screenshot from 2024-10-08 12-31-37


Tested both desktop and mobile. Had a "weird" interaction when switching from desktop to mobile, but one which went away and can't be replicated constantly.

All good here!

**Review by davecreaser — DISMISSED** [review]
Nice and simple @mmioana! Looks good on both desktop and mobile. Agree with Sam's comment too, it might be a nice thing to do but it doesn't block approval!

Screenshot 2024-10-09 at 18 22 25
Screenshot 2024-10-09 at 18 23 18
Screenshot 2024-10-09 at 18 24 59

**Comment by mmioana** [comment]
@rdig @iamsamgibbs @davecreaser I have rebased with master and did a bit of refactoring, thus the number of changes.
I have added a min-width and also more spacing between the token avatar and name in the dropdown, if you could be so kind to re-check 🙏

**Review by iamsamgibbs — DISMISSED** [review]
Nice job! Looks like you have done a lot to tidy up the code here, it looks a lot better!

Everything is still functioning as expected, plus we get some nice whitespace between the amounts and the symbol now!

Screenshot 2024-10-15 at 12 55 20
Screenshot 2024-10-15 at 12 55 54
Screenshot 2024-10-15 at 12 56 41

**Comment by mmioana** [comment]
Thanks @iamsamgibbs 🙏 actually I just reverted some changes I did some time ago about the structure of the tokens menu as the rebase brought everything back into a single component

**Review by rdig — CHANGES_REQUESTED** [review]
I have to reject this. Not because your copy changes are to blame, but because of the way the token dropdown works.

I've added a bunch of tokens to the colony:

Screenshot from 2024-10-16 13-02-02

But when opening the dropdown, only a small section of the tokens shows (they're all approved), and no option to scroll the list any further:

Screenshot from 2024-10-16 13-01-45
Screenshot from 2024-10-16 13-01-54

And if you go to the balances page, you can clearly see all the tokens being added and approved:

Screenshot from 2024-10-16 13-02-11
Screenshot from 2024-10-16 13-02-16

PS: If you want to replicate my setup:
- run the create data script with the max number of colonies: `node scripts/create-data.js --timeout 100 --coloniesCount 12`
- manually add all tokens to the colony (to "approve" them)
- claim all incoming funds

**Comment by mmioana** [comment]
Awesome @rdig thank you so much for spotting this issue 🙏 now it should be fixed, if you could please re-test

**Review by rdig — APPROVED** [review]
Re-tested this and now the token dropdown scrolls to account for all the tokens, as well as the initial fix that this PR put in is still there, the removal of the copy

Nicely done!


https://github.com/user-attachments/assets/c84ad1a4-4d58-4e7d-8aaf-781e7b0cc7e5

**Review by davecreaser — APPROVED** [review]
Still looking good @mmioana! Cool stuff fixing the scroll issue too 👍 

Screenshot 2024-10-18 at 16 37 34

**Review by iamsamgibbs — APPROVED** [review]
Nice job fixing the scroll! All looks good!

Screenshot 2024-10-21 at 10 15 37

Screenshot 2024-10-21 at 10 15 49

**Pull request merged**
