### PR TITLE
Move colors out of extend to only allow styleguide colors

### PR DESCRIPTION
**Pull request by chmanie**
## Description

We need to limit the color palette of tailwind to only colors that are defined in the style guide. Two advantages here:

- People won't get tempted to use colors that aren't in our palette
- Dark mode will work if light mode looks good

## TODO

- [x] Find all occurrences of invallid colors and replace them with valid ones

### CODE REVIEW

**Comment by chmanie** [comment]
This can be reviewed now!

**Review by jakubcolony — DISMISSED** [review]

**Review by melyndav — CHANGES_REQUESTED** [review]
Hey @chmanie thanks for working on getting these colours all neatly organised.

Looks like we've lost some key team colours in the process with them now not appearing in the UI. 

image

image

image


I recently worked with Arren to get all these team colours and corresponding team pills/badges sorted in this PR - not sure if you can grab the missing - https://github.com/JoinColony/colonyCDapp/pull/1502

Colour tokens from the Design system if you need: https://www.figma.com/file/l1dOM5qiQYwF0ElvKDqqjg/Design-System---Colony-V3-(2023)?type=design&node-id=1621-7222&mode=design&t=n59cvULRQBtTAkqs-4

Link to Figma if you need: https://www.figma.com/file/5V8pr7iMwXsT9L3VAZsmUt/Colony-V5?type=design&node-id=1417-103591&mode=design&t=P9EKLNuPzSNBys7M-4

image

**Comment by chmanie** [comment]
I have no idea what had happened here but it should be good now. @melyndav ready for your review again

**Review by rdig — CHANGES_REQUESTED** [review]
These two colors error out when trying to build the branch:

Screenshot from 2024-01-19 01-31-17

**Comment by chmanie** [comment]
> These two colors error out when trying to build the branch:
> 
> Screenshot from 2024-01-19 01-31-17

Beautiful, that’s exactly why I did this here :)

**Comment by chmanie** [comment]
@melyndav this is now building and can be reviewed. There might be some colors that are still wrong but I can't see that from a code side of view. Maybe you can take a look at this branch and let me know whether something stands out to you in terms of colors.

**Comment by melyndav** [comment]
Hey @chmanie,

There's something up with the navigation colouring now. See screenshots below. Both Arren and I can see this. 

The initial issue I raised about the colours missing seems to have been fixed. 

image

image

**Review by rdig — CHANGES_REQUESTED** [review]
Compile error is gone.

But I confirm Mel's findings in terms of the left side's menu's colors:

Screenshot from 2024-01-19 17-11-32
Screenshot from 2024-01-19 17-12-24

The domain colors seem to be alright though:

Screenshot from 2024-01-19 17-12-01

**Comment by chmanie** [comment]
@melyndav @rdig Thank you so much for spotting this. Luckily this should be easily fixed.

**Comment by chmanie** [comment]
@melyndav @rdig OK, I am pretty sure I caught all of them now! Feel free to review again.

**Review by melyndav — APPROVED** [review]
Thanks for fixing those issues raised @chmanie, they look to be resolved! 💯

**Review by rdig — APPROVED** [review]
All good on my end as well

Screenshot from 2024-01-23 19-04-46
Screenshot from 2024-01-23 19-04-52
Screenshot from 2024-01-23 19-05-08

However, I do want to point out that the first time I've ran into that `heading-5` compilation error was on this branch. I don't think it originates here, but wanted to point it out nonetheless

Screenshot from 2024-01-23 19-03-22

Thank you for your work here Chris!

**Pull request merged**
