### PR TITLE
Streaming Payments API: Updates following network changes

### LINKED ISSUE #2481: Streaming Payments API: Contracts version update
Creating this issue to cover all the work to update contracts version in `feat/streaming-payments`, including new colony-js release and adjusting all the sagas and handlers for which underlying contracts changed.

### PR DESCRIPTION
**Pull request by jakubcolony**
## Description

This PR contains changes to make streaming payments compatible with the new contracts, mainly revolving around the fact a stream can now only contain one token.

There's also a block-ingestor update, however changes were cosmetic so they have been pushed directly to `feat/streaming-payments`.

## Testing

Create a few streaming payment, check the testing UI still shows correct amount to claim. Test claiming and displaying the claimed amount.

Use the following query to check data in DB:
```gql
query StreamingPayments {
  listStreamingPayments {
    items {
      id
      tokenAddress
      amount
      claims {
        timestamp
        amount
      }
      interval
      recipientAddress
    }
  }
}

```

Resolves #2481

### CODE REVIEW

**Review by iamsamgibbs — CHANGES_REQUESTED** [review]
The changes seem good, am able to create a new streaming payment without issue and claim a payment:

Screenshot 2024-06-07 at 11 07 00
Screenshot 2024-06-07 at 11 07 32

The temporary UI seems a bit broken though:

https://github.com/JoinColony/colonyCDapp/assets/34915414/9b5be7b3-00dd-437c-bf1c-07eb57659330

**Comment by jakubcolony** [comment]
Hey @iamsamgibbs, thanks, ready for you to test again!

**Review by iamsamgibbs — APPROVED** [review]
Looks good to me! All working as expected now! 🎉 

Screenshot 2024-06-10 at 08 34 57
Screenshot 2024-06-10 at 08 35 44

**Review by rdig — APPROVED** [review]
Looks good both codewise and functional.

Screenshot from 2024-06-11 00-17-10
Screenshot from 2024-06-11 00-17-35

**Review by davecreaser — APPROVED** [review]
Looks good to me, nice one.

Tested locally and creating / claiming still works great:
Screenshot 2024-06-11 at 17 34 59

**Pull request merged**
