### PR TITLE
fix: staking buttons, changed chart colors, indicator display, stakin…

### PR DESCRIPTION
**Pull request by CzarekDryl**
https://tw.auroracreation.com/app/tasks/15685033
https://tw.auroracreation.com/app/tasks/15649439
https://tw.auroracreation.com/app/tasks/15655944

Things that I've fixed in this PR:
- Fixed colors of staking chart progress bar
- Hiding indicator of staking chart when for vote is higher than minimum value
- Staking buttons can untoggle now

Closed [#1397](https://github.com/JoinColony/colonyCDapp/pull/1397) PR and moved styling fixes here to prevent conflicts.

### CODE REVIEW

**Comment by ArmandoGraterol** [comment]
@CzarekDryl Hello! Could you rebase this PR, please?

**Comment by CzarekDryl** [comment]
@ArmandoGraterol Done :)

**Review by melyndav — CHANGES_REQUESTED** [review]
Hey @CzarekDryl great work on this one! Just one issue:

1. The threshold indicator doesn't hide when the user inputs an amount that passes the threshold:
image

**Comment by CzarekDryl** [comment]
@melyndav Raul said something else in other PR
image

**Review by melyndav — CHANGES_REQUESTED** [review]
Hey @CzarekDryl just adding the comment from our clack channel so I can keep track of all the open PR's.

One requested change:

Instead of hiding the line and the text when the 10% threshold is met, can we keep everything showing and just change the text to '10% threshold met, will be made public'

**Pull request closed without merging**
