### PR TITLE
update team purpose length to 120 chr

### LINKED ISSUE #1709: Actions: Increasing character limit in 'Create new team' action
## Description

Since we're showing team descriptions in the soon to be completed Teams page, the current limit of the 'Team purpose' field should be increased from 90 to 120 characters to allow for more content to be shown.

image

Error validations on char limits should also be updated.

### PR DESCRIPTION
**Pull request by warrencolliver**
## Description

This PR updates the character length of the team purpose field in the 'create new team' action. now the character limit is 120. When the 120 character limit is exceeded, the character exceeded count error banner shows.

**New stuff** ✨

Screenshot 2024-01-30 at 12 32 21

**Changes**
Adding word-break so the UI isn't broken when a long non-broken text is inputted into the form.
Screenshot 2024-01-31 at 10 27 44

Added onChange validation so validation happens without the user being required to click out of the field. this change will apply to all form fields that are validated.
onChange validation

Resolves #1709

### CODE REVIEW

**Review by rdig — CHANGES_REQUESTED** [review]
Tested this with both team creation and team edit and behaves as expected.

However I found some issues, which while not part of the original scope, I want you to address.

1. If there's long, non breakeable text entered as team purpouse, it breaks the UI

Screenshot from 2024-01-30 14-42-47

2. Initial length validation happens on blur initially, but after that, when you resume editing, it happens on change

Please have this all work onchange, even the initial instance

[Screencast from 2024-01-30 14-44-20.webm](https://github.com/JoinColony/colonyCDapp/assets/1193222/50e3efd7-5761-4436-9192-86c70f2fd133)

Very nice work so far and tank you for tackling this.

**Review by melyndav — CHANGES_REQUESTED** [review]
Hey @warrencolliver,

Thanks for picking up my issue! A noticed one thing when testing the completed state of the action, if that the title got stripped out and the error state shown.

image

I couldn't replicate this in production but I'm not sure if this is linked to your updates. 

Also, can I kindly request for any UI/UX issues you pick up to tag me/ design team in the PR reviewer section? Thank you :)

**Comment by rdig** [comment]
@melyndav  The title error is not related to this issue, as it shows up in `master` as well.

If you refresh the action (or page) the title will show back up.

@warrencolliver  This needs to be tracked in a separate issue

**Review by melyndav — DISMISSED** [review]
Hey @warrencolliver I re-reviewed this since Raul was able to verify the title issue is outside the PR and will be raised. So it's approved from my side. Thanks again for picking up my issue! 👍

**Review by bassgeta — DISMISSED** [review]

**Review by melyndav — COMMENTED** [review]
Re-approving @warrencolliver 👍

**Comment by warrencolliver** [comment]
> Tested this with both team creation and team edit and behaves as expected.
> 
> However I found some issues, which while not part of the original scope, I want you to address.
> 
> 1. If there's long, non breakeable text entered as team purpouse, it breaks the UI
> 
> Screenshot from 2024-01-30 14-42-47
> 
> 2. Initial length validation happens on blur initially, but after that, when you resume editing, it happens on change
> 
> Please have this all work onchange, even the initial instance
> 
>  Screencast.from.2024-01-30.14-44-20.webm 
> Very nice work so far and tank you for tackling this.

I've made the changes and added them to the PR description. thanks

**Review by rdig — APPROVED** [review]
This now works as it's supposed to. Nice work Warren! :100:

**Review by iamsamgibbs — APPROVED** [review]
Great job! All tested and working as expected.

https://github.com/JoinColony/colonyCDapp/assets/34915414/2f1bf59a-75e2-4035-b349-f83533c7e116

**Pull request merged**
