### PR TITLE
feat: added additional content to sidebar when action is forced

### PR DESCRIPTION
**Pull request by CzarekDryl**
https://tw.auroracreation.com/app/tasks/15701328

**New stuff** ✨
* Added additional content to sidebar when action is forced

image

### CODE REVIEW

**Review by arrenv — CHANGES_REQUESTED** [review]
@CzarekDryl Nice addition, this is pretty much good to go from my end, but I did notice this issue when clicking the New action button then opening a transaction, which does not seem to happen on `master`.

issue-opening

**Comment by CzarekDryl** [comment]
@arrenv This should be fixed now, please check it again.

**Review by melyndav — APPROVED** [review]
This is good to go from my end @CzarekDryl. Thank you for your work on this!

**Review by arrenv — APPROVED** [review]
Working great now, thank you!!

**Review by TomaszChmielPagepro — APPROVED** [review]

**Pull request merged**
