### PR TITLE
Fix: Update style for user and token popovers

### PR DESCRIPTION
**Pull request by mmioana**
## Description

Add domain color to ContributorReputation and ContributorRoles fragments 
Update styling for user popover
Update styling for token popover

## Testing

* Step 1. Go to colony members
* Step 2. Check the user card styling for each type of member (Top/Dedicated/Verified/Unverified etc) - maximum height and different width for tablet/desktop, scrollable Teams section 
  
* Step 3. Go to colony finance
* Step 4. Check the token card styling - different width for tablet/desktop

Resolves [#2496](https://github.com/JoinColony/colonyCDapp/issues/2496)

### CODE REVIEW

**Review by melyndav — CHANGES_REQUESTED** [review]
Hey @mmioana nice start on this PR and thanks for picking up my issue. A couple of required changes to match the Figma designs.

1. The padding inside each permission pill type should match Figma. Currently, there is extra padding to the right.
image

2. The height of each team section isn't consistent with Figma. Here they are 44Px

image


But in this card they are 52px. Don't both match the Figma height and should be consistent no matter the card type.

image
 
 3. Reputation and star icons have not been updated to match Figma.
 
image

 
Be sure to check Figma before requesting a review just to help ensure all the scope has been covered in the first stage of the PR. Thanks! 👍 

image

**Comment by mmioana** [comment]
> Hey @mmioana nice start on this PR and thanks for picking up my issue. A couple of required changes to match the Figma designs.
> 
> 1. The padding inside each permission pill type should match Figma. Currently, there is extra padding to the right.
> 
> image
> 2. The height of each team section isn't consistent with Figma. Here they are 44Px
> 
> image
> But in this card they are 52px. Don't both match the Figma height and should be consistent no matter the card type.
> 
> image
> 3. Reputation and star icons have not been updated to match Figma.
> 
> image
> Be sure to check Figma before requesting a review just to help ensure all the scope has been covered in the first stage of the PR. Thanks! 👍
> 
> image

You're right @melyndav, I have overlooked some of the styling changes. Hope now everything is in place, if you want to re-check 😄

**Review by iamsamgibbs — CHANGES_REQUESTED** [review]
Nice work on this so far! The code all looks good, and the UI changes are mostly looking good too!

Screenshot 2024-07-01 at 11 14 55

Mel's previous concerns have been addressed:

Screenshot 2024-07-01 at 11 17 23

I've found a couple of small issues. My apologies if any of these are too nitpicky (@melyndav can advise on if any of these are okay to leave as they are!)

The scrollbar is too close to the teams compared to figma:

Screenshot 2024-07-01 at 11 08 21

Figma:

Screenshot 2024-07-01 at 11 08 41

(Sorry that will probably be a pain to change with padding 🥲)

The scrollbar should appear when there are more than 4 teams:

Screenshot 2024-07-01 at 11 20 54

Screenshot 2024-07-01 at 11 26 53

And when there are more than 4 teams, the first four should fit neatly into the containing element without cutting off the fourth, or showing any of the fifth when scrolled to the top.
 
Screenshot 2024-07-01 at 11 09 02

Screenshot 2024-07-01 at 11 23 52

This card is also only showing 2 teams instead of 4:

Screenshot 2024-07-01 at 11 08 00

The padding is inconsistent on mobile:
 
Screenshot 2024-07-01 at 11 10 12

Screenshot 2024-07-01 at 11 10 42

These last two aren't necessarily issues, just things I noticed that seem a bit off / personal opinion - questions for @melyndav :

As a user it feels like this should have tooltips to show the full team name when truncated and the additional '+5' teams.
 
Screenshot 2024-07-01 at 11 03 41

On mobile, it won't be possible to hover on these icons so the tooltips won't be visible. I wonder if they should be clickable to toggle on mobile? (This probably affects other icons in the app too)
 
Screenshot 2024-07-01 at 11 13 31

Some of those points might increase the scope of the issue too much, so feel free to use your judgement and we can always open new issues to tackle them separately.

**Review by melyndav — CHANGES_REQUESTED** [review]
Hey again @mmioana - thanks for your continued work on this one.

I see all the issue's Sam has picked up, so it would be great to get these addressed.

One further issue, is the X close on mobile. Can you ensure this is aligned to the right of the content container? It's currently floating a little too far on the left. 

image


@iamsamgibbs  - I've noted your pick-ups (especially the truncation now we've expanded the width of the overall pop-over) since this scope was just for the permission handling. :)

**Pull request closed without merging**
