### PR TITLE
UI: New Navigation

### PR DESCRIPTION
**Pull request by rumzledz**
## Description

This serves as the base branch for all PRs relevant to the New Nav OKR.

**Specs**: https://www.notion.so/colony/Navigation-21cb75bea48d4b99bec05f0b3142a608

**Figma URL:** https://www.figma.com/design/uKxVl441Wnn02SNiOA24De/Navigation?node-id=3931-21252&node-type=frame&t=YGhXELOG6ekOydHH-0

**Relevant issues**: https://github.com/orgs/JoinColony/projects/70/views/1

### CODE REVIEW

**Review by melyndav — CHANGES_REQUESTED** [review]
Really fantastic work @rumzledz, @Nortsova  & @iamsamgibbs  and everyone else who has contributed and reviewed the [ui/new-navigation-ui] branch. I've reviewed the work completed to-date, with the following minor UI/UX requests identified.

Not tested: 
- Help & feedback component 
- Dark mode
- User account nav + tab removal

## Inside a Colony

1. I changed the colony name, but the nav or the switcher did not update across any size.

image
image

Mobile:
image


---

2. When the switcher is active on the desktop version, the highlight on the left side nav bar should remain active in the select state. Currently, it only shows on hover. 
image

---

3. The padding between the colony switcher and first nav item should be 32px + the additional top padding on the first navigation item that handles the hover on desktop:
image

---

4. Activity feed should be 'Activity' as per Figma across all sizes.

image

---

5. The padding between the navigation and main content should be maintained at 32px as per production on desktop. 

image

---

6. There's additional padding around the content container, causing the actual content to display at 1096px.

image

---

7. The number of contributor cards on the members page at desktop/tablet sizes should be reduced to from 4 to 3 as per the original designs to accommodate the extra width of the nav and reducing any issues with permission pills in the individual member cards:

https://www.figma.com/design/uKxVl441Wnn02SNiOA24De/Navigation?node-id=4481-10663&t=IWFwNfDd3Nnbi4w7-4

---

8. I updated the colony logo, but the switcher logo didn't get updated after completing the action:

image

Even with a reload or colony switch, the logo doesn't update:

image


On mobile:

image

---

9. On mobile, when I select the 'Finances' dropdown, the menu closes and takes me to the 'Balances' page without allowing me to see the menu items below the Finances section first. I can't get to incoming funds unless I go back into the menu again.

---

10. The 'Create new colony' button doesn't work on all sizes.

image


---

11. Padding between page title and content doesn't match Production on desktop. 

image
 
 
Every inside page should be consistent with 32px as per Figma:
 
image

---

12. The very top container padding has also been changed too and is causing padding misalignment of the user pills on the top right when an action is triggered.

image

image

As per production:

image






## Outside the colony (wallet disconnected)

1. The styling of the disconnected icon is slightly off compared to Figma.

image

---

2. On mobile, there's some funky duplication of menu items on the settings pill (which may need to be a separate PR). 

image




## Outside a Colony (no colonies joined or created)

1. The styling of the 'No colonies joined' including padding and the icon should match Figma. Also, the button doesn't go anywhere. 

image

Also on mobile:

image

**Comment by rdig** [comment]
Thank you @melyndav :100:

**Comment by rumzledz** [comment]
@melyndav I've updated your previous comment and added references to the issues I made to track them, hope you don't mind!

**Comment by melyndav** [comment]
Hey team, another massive congrats to everyone on the hard work put into the nav re-work and addressing the first QA round. Stella work by you all @rumzledz @Nortsova and @iamsamgibbs and everyone else involved.

Some minor feedback after a second round review.


### Outside the colony (wallet disconnected)

The hover state on the 'Help & feedback' is missing the inclusion of the text as per Figma.

Currently:

image

Figma:
image

https://www.figma.com/design/uKxVl441Wnn02SNiOA24De/Navigation?node-id=3962-8846&t=J5fzgQt2qWWbuLnu-4

---


## All states

The CTA button here should be solid gray-900 on hover for all versions of this switcher (Connected, not connected and the no joined versions). 

image


----

## User account area

As part of this feature scope, we got rid of the tabs on the user account page and split these into individual pages. However, now each page when selected from the new navigation, just as the word 'Account' set as the page title and doesn't match the nav labels and breadcrumbs. Can these please be updated?

image


As mentioned, I'll raise the padding change in a separate issue. But again, wonderful work!

**Pull request merged**
