### PR TITLE
fix: ui on members page

### PR DESCRIPTION
**Pull request by CzarekDryl**
https://tw.auroracreation.com/app/tasks/15789352

## Description

- Few changes to members page on mobile

Resolves [1903](https://github.com/JoinColony/colonyCDapp/issues/1903)

### CODE REVIEW

**Review by melyndav — CHANGES_REQUESTED** [review]
Hey @CzarekDryl thanks for picking up these mobile issues.

1. I still see the kebab menu exceeding the container width on both member type tabs.

image
 
 
 2. Content is still clipping into the top header nav bar across both tabs
 
image
image


3. Reputation is missing 'sort by' in the title as per Figma. 

4. X icon in the search input isn't correct size.
image

5. When I search for a user on the contributors tab and there is no user that matches the search, the same empty search block should show on the contributors tab. This should also happen naturally for desktop as well (replacing the invite members dotted box when a false search is active)
image

**Review by melyndav — CHANGES_REQUESTED** [review]
Hey again @CzarekDryl appreciate the updates from my last round of checks.

When I search and get no results, the UI is showing empty on both tabs. 

image

They should match Figma here across all sizes: https://www.figma.com/file/moME7kMfr5pdt6PYrfDtm6/Members?type=design&node-id=201-9520&mode=design&t=GJMtoLQ3GtUchGy4-4

**Review by ArmandoGraterol — COMMENTED** [review]
Nice work man! Thank you for the changes, I only noticed that when I apply a custom filter and I go back to the filter menu, the options aren't checked as if the filter wasn't applied:

Screenshot 2024-02-21 at 14 41 19

This happens in the mobile version too. When I click on it, then it does recognize the filter is active and shows `Root` checked along with `Custom`

**Review by melyndav — CHANGES_REQUESTED** [review]
Hey @CzarekDryl 

When I open the filter, it breaks the whole page due to the alignment of the filter menu. As you can see in the screenshot, content is pushed off to the left of the browser window. 

image

**Review by iamsamgibbs — APPROVED** [review]
Looks good to me! Only one thing (and it might be more of a personal preference thing) but I would expect clicking custom here to remove all custom filters, currently it does nothing.

https://github.com/JoinColony/colonyCDapp/assets/34915414/69e35c2a-6303-4b3c-932a-8f5ffae72dde

**Review by warrencolliver — APPROVED** [review]
tested the changes made and can't find any issues + I agree with Sam's idea about the custom filter - it provides better user experience

**Review by ArmandoGraterol — DISMISSED** [review]
Looking good to me 👌 Thank you for the changes!

**Review by ArmandoGraterol — DISMISSED** [review]

**Review by warrencolliver — APPROVED** [review]

**Review by rdig — DISMISSED** [review]
Approving so we can get this merged

**Review by iamsamgibbs — APPROVED** [review]

**Review by warrencolliver — APPROVED** [review]

**Pull request merged**
