### PR TITLE
Fix: Allow separators in bank account number validation

### LINKED ISSUE #2961: [C2F] Formatting on IBAN input and correct error validation UX
## Description
There is no validation on incorrect formatting for the IBAN input field when the CTA button is selected, and only shows after it's been selected with a toast, which is inconsistent with the rest of the validation UX and does not indicate to the user what specifically the issue is and how to resolve it.

Example: When I enter (dummy data for screenshot purposes) IBAN details in that follow the format from my bank which includes spacing, no validation is shown upon selecting the CTA:

image

Toast with generic error:

image

However, if I input the incorrect SWIFT format, validation is provided.

image

### **Scope:** 
Add validation to match the accepted IBAN format from the API (no spacing between numbers and digits). Add inline to the form when the CTA is selected to ensure consistency in the error state UX.

Remove the toast validation. 

All updates should be made across all responsive sizes.

### PR DESCRIPTION
**Pull request by iamsamgibbs**
## Description

This PR adjusts the validation for the crypto to fiat bank account validation to allow for spaces or hyphens as separators. This will make it easier for users copying their bank details into the forms.

It adds an alphanumeric check to each account number field and will display a specific error message if any non alphanumeric values are entered (ignoring the two valid separators).

The separators are stripped out before validating against regex and when submitting the values to the API.

Please check Arren's comment on the original issue for the exact specs: https://github.com/JoinColony/colonyCDapp/issues/2961#issuecomment-2307001840

## Testing

* Step 1: Edit `src/components/frame/v5/pages/UserCryptoToFiatPage/partials/BankDetails/consts.ts` and replace line 95 with `false` to enable the CTA button and bypass the KYC check.
* Step 2: Navigate to http://localhost:9091/account/crypto-to-fiat
* Step 3: Click the "Add details" button and select USD as the payout currency.
* Step 4: Submit the form so that error validation shows.
* Step 5: Check the account number only allows numeric values, spaces or hyphens and is between 6 and 17 digits once separators are removed.
* Step 6: Check the routing number only allows numeric values, spaces or hyphens and is exactly 9 digits once separators are removed.

Screenshot 2024-10-25 at 09 47 48

Screenshot 2024-10-25 at 09 48 48

Screenshot 2024-10-25 at 09 48 01

* Step 7: Switch the payout currency to EUR.
* Step 8: Check the IBAN only allows alphanumeric values, spaces or hyphens. It should also only allow values that start with 2 uppercase letters, followed by 2 digits. The remainder of the IBAN should be alphanumeric and allow for a total length of 15-34 characters once separators are removed.
* Step 9: Check the SWIFT/BIC only allows alphanumeric values, spaces or hyphens and is either exactly 8 or 11 characters long once separators are removed.

Screenshot 2024-10-25 at 09 48 29

Screenshot 2024-10-25 at 09 48 37

Screenshot 2024-10-25 at 09 48 18

## Diffs

**Changes** 🏗

* Bank account numbers now allow separators
* Bank account numbers are now validated for alphanumeric values first
* Bank account number length validation adjusted
* Bank account numbers now strip separators when submitting to API

**Deletions** ⚰️

* Removed BIC regex

Resolves #2961

### CODE REVIEW

**Review by jakubcolony — CHANGES_REQUESTED** [review]
Very nice work @iamsamgibbs, tested it with the live API and overall it works great! 

USD ✅ 
image

image

image

EUR ✅ 

image

image

image
image


However, I'm requesting changes as I was able to make USD account/routing numbers validation to pass by entering just letters, as long as the length matches:
image

Account and routing numbers are digits only. I can see that's how it was spec'ed in the issue, so I'll mention it there too.

**Comment by iamsamgibbs** [comment]
Thanks for picking up on this @jakubcolony - I've made the change so that US account numbers only allow numeric values.

Screenshot 2024-10-29 at 13 11 57

I've not implemented the additional SWIFT validation Arren added as there are further changes required for proper SWIFT support so this should be addressed as part of that issue.

**Review by rdig — CHANGES_REQUESTED** [review]
I didn't really manage to test this, but it might be with the way I have went about this

I can't get the validation errors to trigger

Screenshot from 2024-10-29 18-44-49

But I am getting this error from the lambda, so I assume it's related

Screenshot from 2024-10-29 18-45-03

Lastly, I also tried the other way around (not commenting out the line), but actually using the sandbox to pass KYC

Screenshot from 2024-10-29 18-45-10

**Comment by iamsamgibbs** [comment]
@rdig Ah, the form requires submitting before any validation errors show. It's in the testing steps, but I'll move it into it's own testing step so it is more obvious.

**Review by rdig — APPROVED** [review]
Was able to test it properly this time, and yeah, you were correct as the form only validates after submitting.

Screenshot from 2024-10-31 17-40-57
Screenshot from 2024-10-31 17-41-24
Screenshot from 2024-10-31 17-41-35
Screenshot from 2024-10-31 17-42-23
Screenshot from 2024-10-31 17-43-02
Screenshot from 2024-10-31 17-43-08

**Pull request merged**
