### PR TITLE
[Dashboard] Move breadcrumbs from sticky header into page layout

### LINKED ISSUE #3160: [Dashboard] Realign the dashboard sticky header with breadcrumbs
Currently there's an issue with the sticky header on all pages:
Image

We should instead make it scrollable or at least make it function nicer.
[Figma link](https://www.figma.com/design/gac6xVgGNCAge5Bia933dp/Dashboard?node-id=4870-56993&t=IGjjs6PVdtuLhKqN-4)

### PR DESCRIPTION
**Pull request by iamsamgibbs**
## Description

This PR resolves an issue where the `PageHeading` component was part of the `PageHeader` which resulted in the breadcrumbs and page title being part of the sticky nav on mobile.

The `PageHeading` component has been removed entirely and the breadcrumbs and page title have been moved into more suitable homes.

This PR also fixes some alignment issues with the page title on ultra-wide screens and puts the page title in line with the content whilst allowing the breadcrumbs to expand out to the left. Which highlighted some spacing issues with the team switcher and general page layout, which this PR aims to resolve.

Had a fair bit of discussion with @melyndav about how this should all work and she has handily provided a figma design for how this should all look: https://www.figma.com/design/gac6xVgGNCAge5Bia933dp/Dashboard?node-id=6760-57700&t=7Q8sbaeEZ1zE6nwl-4

(I'm very sorry if these changes overlap too much with any other alignment fixes or with the nav feature 🥲 )

## Testing

On desktop, check that the header has 8px whitespace below the userhub button so there is space between the userhub button and the page content when you have scrolled:

Screenshot 2024-09-26 at 13 52 02

On mobile, the border bottom should be the clear dividing line:

Screenshot 2024-09-26 at 13 52 48

On all pages, check the page title lines up with the page content on a wide screen size:

Screenshot 2024-09-26 at 13 53 56

On mobile, check the page title lines up neatly with the breadcrumbs and that neither the page title nor the breadcrumbs are included in the sticky nav:

Screenshot 2024-09-26 at 13 54 28

Check the figma design for other specific changes.

## Diffs

**Changes** 🏗

* Various layout / structural changes
* Various alignment changes
* Realigned `PageHeader` props

**Deletions** ⚰️

* Removed `PageHeading` component

Resolves #3160

### CODE REVIEW

**Review by mmioana — CHANGES_REQUESTED** [review]
Awesome changes @iamsamgibbs thank you for picking up this issue 💯 

Screenshot 2024-09-26 at 15 45 18
Screenshot 2024-09-26 at 15 45 29
Screenshot 2024-09-26 at 15 48 36
Screenshot 2024-09-26 at 15 49 35
Screenshot 2024-09-26 at 15 50 00
Screenshot 2024-09-26 at 15 50 07
Screenshot 2024-09-26 at 15 50 13
Screenshot 2024-09-26 at 15 50 59
Screenshot 2024-09-26 at 15 51 08
Screenshot 2024-09-26 at 15 51 12

The only issue I have noticed is for the mobile when we have more 3-level breadcrumbs
Screenshot 2024-09-26 at 15 50 35

After discussing with @melyndav, we should show for the moment only the 2-level breadcrumbs on mobile

So in `src/components/v5/shared/Breadcrumbs/Breadcrumbs.tsx` we should filter the `breadcrumbItems` to have maximum length of 2 if `isMobile` is `true`
`breadcrumbItems.slice(0, 2).map...`

Sorry @iamsamgibbs I updated the way we should treat the breadcrumbs on mobile 🙌 

Everything else looks amazing, thanks so much for all your effort! 🥇

**Comment by iamsamgibbs** [comment]
Made this change!

Screenshot 2024-09-27 at 09 39 27

**Review by rumzledz — APPROVED** [review]
This is good to go @iamsamgibbs 🚀 

Can confirm that there's an 8px bottom padding for the header
Screenshot 2024-09-27 at 18 01 38

The title and breadcrumbs are not part of the top nav
non sticky

**Review by mmioana — CHANGES_REQUESTED** [review]
Awesome work @iamsamgibbs 🎉 

It all looks great for both `mobile` and `desktop`
Screenshot 2024-09-27 at 12 18 11
Screenshot 2024-09-27 at 12 18 14
Screenshot 2024-09-27 at 12 18 22
Screenshot 2024-09-27 at 12 18 38
Screenshot 2024-09-27 at 12 18 45
Screenshot 2024-09-27 at 12 18 49
Screenshot 2024-09-27 at 12 18 57
Screenshot 2024-09-27 at 12 19 04
Screenshot 2024-09-27 at 12 19 09
Screenshot 2024-09-27 at 12 19 29

However I noticed there is a small issue once you're on the `Profile` pages and you click on the `Colony` breadcrumb, if you can please fix it 🙏 

https://github.com/user-attachments/assets/0e10d50f-9b5f-41b7-a440-dc59c20e492b

I think we need the following change in `src/components/frame/v5/pages/UserProfilePage/UserProfilePage.tsx`
Screenshot 2024-09-27 at 12 23 18

**Comment by iamsamgibbs** [comment]
Good catch @mmioana and thanks for the code fix, all good now!

https://github.com/user-attachments/assets/cba044be-b44a-4fc2-92e5-ce4e10975dc2

**Review by mmioana — APPROVED** [review]
Let's get this one merged 🎆 🚀

**Review by jakubcolony — APPROVED** [review]
Nice work @iamsamgibbs! 💪 

- 8px padding on the header ✅ 
image

- Title lining up with the content ✅ 
image
image
image
image

- Alignment on mobile, showing max 2 breadcrumb items ✅ 
image
image
image

**Pull request merged**
