### PR TITLE
Fix: Onboard modal issues

### LINKED ISSUE #2073: Onboard.js modal UI issues
## Description

There's some UI issues with the onboard.js modal as shown below. Resolving the issues is dependent on whether we move away from onboard.js or not. 

image

**To replicate the issue:**

1. Disconnect any connected wallets
2. Trigger the connect wallet pill from the top right header 
3. The onboard.js modal will display

### PR DESCRIPTION
**Pull request by iamsamgibbs**
## Description

A recent update to `@web3-onboard/core` introduced new options which messed with the exisitng onboard modal styling. This PR changes the desktop icon to be an inline svg so that is shows properly, adds a new mobile icon, fixes the column styling on the wallet select.

## Testing

1. Disconnect any connected wallets
2. Trigger the connect wallet pill from the top right header
3. The onboard.js modal will display

## Diffs

**New stuff** ✨

* Mobile icon

**Changes** 🏗

* Fixed desktop icon
* Fixed wallet column styling

Screenshot 2024-03-21 at 11 50 22

Screenshot 2024-03-21 at 11 50 34

Resolves #2073

### CODE REVIEW

**Review by melyndav — APPROVED** [review]
Looks much better, thanks for fixing this issue @iamsamgibbs 🥇

**Review by rdig — CHANGES_REQUESTED** [review]
Looks good

Screenshot from 2024-03-21 15-57-01

However I'd also remove the block native logo. We have no obligation to link back to them (other than a moral one)

Screenshot from 2024-03-21 15-57-10

**Review by jakubcolony — APPROVED** [review]
LGTM 👍

**Comment by iamsamgibbs** [comment]
> Looks good
> 
> Screenshot from 2024-03-21 15-57-01
> 
> However I'd also remove the block native logo. We have no obligation to link back to them (other than a moral one)
> 
> Screenshot from 2024-03-21 15-57-10

This might not be feasible as the web3-onboard configuration doesn't give any option to hide this and the modal is created inside a shadow-root making it difficult to mess with the styles. If you feel like it is worthwhile I can investigate this further.

**Comment by iamsamgibbs** [comment]
> Looks good
> 
> Screenshot from 2024-03-21 15-57-01
> 
> However I'd also remove the block native logo. We have no obligation to link back to them (other than a moral one)
> 
> Screenshot from 2024-03-21 15-57-10

@rdig  This might not be feasible as the web3-onboard configuration doesn't give any option to hide this and the modal is created inside a shadow-root making it difficult to mess with the styles. If you feel like it is worthwhile I can investigate this further.

**Comment by rdig** [comment]
Prior to the style changes, those elements were controlled via these global style overwrites: https://github.com/JoinColony/colonyCDapp/blob/master/src/styles/main.css#L56-L92

I assumed this issue fix was just to re-enable these styles, so I'd look into that.

But if either the style names changed, or the lib did any update to prevent us from overwriting their styles, and this takes too much time to fix, then drop it and merge it as-is.

**Comment by iamsamgibbs** [comment]
I've looked into this further and can confirm the library did an update to prevent hiding this message - so will merge as is.

**Review by rdig — APPROVED** [review]
Fine by me then :) Nice work!

**Pull request merged**
