### PR TITLE
refactor: Rework action sidebar descriptions

### LINKED ISSUE #1669: Actions: Refactor the way our current form titles work
Currently we display the form titles in the following flow:
1. the hook `useActionDescriptionMetadata` (after [this PR](https://github.com/JoinColony/colonyCDapp/pull/1608) is merged it's a component called `ActionDescriptionMetadata`) has a map of "getters":
image
2. Then it calls the appropriate "getter", gets some modified action data
3. calls `ColonyActions/helpers/getActionTitleValues.ts`
image
image
4. finally it overrides the initiator metadata
image

This is quite complicated, we should just return data from the "getter", format it there and return it.
Note that it may get tricky since we are reusing the forms for display of completed actions, but it shouldn't be much work.

### PR DESCRIPTION
**Pull request by bassgeta**
## Description

This PR refactors the way our current action sidebar descriptions work.
Previously we wrapped it into many functions, I've implemented a single component which handles the rendering.
Then each description gets typed form values and renders appropriate content.
I've also made a reusable `Recipient` and `CurrentUser` component for ease of use.
I've left in `AdvancedPayment` and `SplitPayment` getters so we know what is the expected format when we implement them. I commented them out, so I was able to delete the utils and types.

**New stuff** ✨

* `ActionSidebarDescription` component and all of its partials!

**Changes** 🏗

* `ActionSidebarDescription` is used instead of `ActionDescriptionMetadata`, 

**Deletions** ⚰️

* all of the metadata getters and unnecessary utils

Resolves #1669

### CODE REVIEW

**Review by ArmandoGraterol — COMMENTED** [review]
Looking good to me 👍 Just left a small observation regarding some imports

**Review by iamsamgibbs — DISMISSED** [review]
This looks great to me - much nicer to use than what was there before. I agree with @ArmandoGraterol 's suggestion.

Just a heads up that #1741 also makes changes to the same lines in src/i18n/en-actions.ts with wording agreed with Arren.

**Review by warrencolliver — DISMISSED** [review]
looks good to me. Great work

**Review by iamsamgibbs — APPROVED** [review]
Looks good to me!

**Review by ArmandoGraterol — APPROVED** [review]
Looks good to me! Thank you for the changes

**Review by melyndav — CHANGES_REQUESTED** [review]
Hey @bassgeta nice work on this one. 

A couple of issues picked up:

1. When selecting a member, the alert icon and verified icon show for the same user. Which is contradictory. 

image

2. Formatting in the description field completely breaks when going to a completed state.

image

3. When typing in the amount field or in any other input field, the metadata jumps around for each character inputted - specifically letters for best example.

**Comment by bassgeta** [comment]
> Hey @bassgeta nice work on this one.
> 
> A couple of issues picked up:
> 
>     1. When selecting a member, the alert icon and verified icon show for the same user. Which is contradictory.
> 
> 
> image
> 
>     2. When typing in the amount field or in any other input field, the metadata jumps around for each character inputted - specifically letters for best example.

We can handle 1 in a separate issue since it's an already existing bug, and number 2 I think I've been able to fix with the recent changes, fingers crossed :D

**Review by iamsamgibbs — APPROVED** [review]
Looks good to me! Not experiencing the metadata jumping issue previously raised.

**Review by rdig — APPROVED** [review]
This is some very nice cleanup Kerry. Stellar work! I really like it.

I didn't experienced metadata jumps, so all good on that front.

**Comment by melyndav** [comment]
Hey @bassgeta I raised the user verification as a separate issue since it's appearing in master but not production.

**Review by melyndav — APPROVED** [review]
No more jumping! Thanks for the fix @bassgeta, appreciate the work! 💯

**Pull request merged**
