### PR TITLE
Fix: Multi-sig showing as an option in Split payments

### LINKED ISSUE #3250: Multi-sig showing as an option in Split payments
## Steps to reproduce

1. Ensure you have the Multi-sig extension installed.
2. Create a Split payment action.
3. Click on the Decision method field.
4. Note that Multi-sig option is available to select.
5. Note that you are not able to create it the action.

## Expected behaviour

* You should not be able to select a decision method that is not supported yet.

## Actual behaviour

* You are able to see the Multi-sig decision method on Split Payments action that is not supported yet.

image

### PR DESCRIPTION
**Pull request by mmioana**
Fix: add helper function to remove unsupported decision methods from SplitPaymentForm

## Description

- This PR introduces a helper function `createUnsupportedDecisionMethodFilter` that can be used to exclude decisions methods from the `DecisionMethodField`.
- Currently it is used only for the `SplitPaymentForm` and `StagedPaymentForm` to exclude the `DecisionMethod.Reputation, DecisionMethod.MultiSig` decision methods

## Testing

TODO: Test the `Multi-Sig` and `Reputation` decision methods don't show up in the `Split payment` action form

* Step 1. Install the `Reputation Weighted` extension
Screenshot 2024-10-04 at 12 49 08

* Step 2. Install the `Multi-Sig` extension
Screenshot 2024-10-04 at 12 27 44

* Step 3. Give `leela` `Owner` permissions to `Take actions via Multi-Sig`
Screenshot 2024-10-04 at 12 58 47

* Step 4. Create a `Split payment` action
Screenshot 2024-10-04 at 13 04 26

* Step 5. Check `Multi-sig` and `Reputation` are not showing up as options in the `Decision method` dropdown
Screenshot 2024-10-04 at 12 27 25

* Step 6. Check that even after a page refresh, these options are not showing up for a `Split payment` action 
* Step 7. Change to a `Staged payment` action and check that `Multi-sig` is not showing up as a decision method
Screenshot 2024-10-04 at 13 03 02

## Diffs

**New stuff** ✨

* `createUnsupportedDecisionMethodFilter`

**Changes** 🏗

* `Multi-Sig` is no longer shown as decision method for the `Split payment` and `Staged payment` actions 

Resolves #3250

### CODE REVIEW

**Review by jakubcolony — DISMISSED** [review]
Thanks again for a quick turn around on this @mmioana!

After assigning Multisig permissions I could use it to mint tokens for instance:
image

But I wasn't given that option for Split and Staged payments:
image

image

Great work! 💯

**Comment by rdig** [comment]
@mmioana when you get back, this branch will need a rebase

**Comment by jakubcolony** [comment]
@rdig branch rebased, it'd be nice to get this included in the upcoming advanced payments release

**Review by jakubcolony — APPROVED** [review]

**Review by davecreaser — APPROVED** [review]
Nice work @mmioana, cool little util!

After installing the extensions, and giving permissions:
Screenshot 2024-10-09 at 18 16 16
Screenshot 2024-10-09 at 18 16 51

The expected decision methods are excluded:
Screenshot 2024-10-09 at 18 17 42
Screenshot 2024-10-09 at 18 19 08
Screenshot 2024-10-09 at 18 19 41

**Review by iamsamgibbs — APPROVED** [review]
Great work on this, nice little util.

Not showing for split payment:
Screenshot 2024-10-10 at 13 21 38

Or staged payment:
Screenshot 2024-10-10 at 13 22 29

But does for other expected action types:
Screenshot 2024-10-10 at 13 23 08

**Pull request merged**
