### PR TITLE
Fix: Add zero reputation teams to dashboard influence-by-team list

### LINKED ISSUE #3684: [Dashboard - QA] "Influence by Team" section does not display teams with 0% reputation.
## Steps to reproduce

1. Navigate to the dashboard page with multiple teams.
2. Ensure that some teams have a 0% reputation value.
3. Check the "Influence by Team" section.

## Expected behaviour

* Teams with 0% reputation should be listed in the "Influence by Team" section but should not impact the donut chart.

## Actual behaviour

* Teams with 0% reputation are missing entirely from the "Influence by Team" section.

Requirements https://www.notion.so/colony/Dashboard-Colony-Home-322f296cb46240d3afddeddd7472ddd7

image

image

### PR DESCRIPTION
**Pull request by davecreaser**
## Description

- Any team which has zero reputation should be showing in the legend of the pie chart on the dashboard, but it should take up zero space in the actual pie chart.
- There should be a maximum of 5 teams shown in that legend. If there are more than 5 teams then it should show 4 teams and a 'All other' item which includes all of the others.

Full details and spec here: https://www.notion.so/colony/Dashboard-Colony-Home-322f296cb46240d3afddeddd7472ddd7?pvs=4#95f462343e974c048d88206eaaa860d8

## Testing

* Step 1. Go to Wayne Enterprises colony (it is easier to test with this colony since it starts with 4 subdomains by default). Check the Influence By Team chart on the dashboard (ensure you aren't filtering the app by a team). It should show 4 teams in both the pie chart and the legend below.
Screenshot 2024-12-02 at 17 13 41

* Step 2. Create a new team inside this colony. Check the chart again; this time there should still be 4 teams in the pie chart, but there should now be 5 teams underneath in the legend.
Screenshot 2024-12-02 at 17 14 31

* Step 3. Create another new team inside the colony. Again check the chart. There should still be 4 teams shown in the pie chart, and now there should be 4 teams in the legend underneath, followed by a 'All other' item.
Screenshot 2024-12-02 at 17 15 12

## Diffs

**Changes** 🏗

* Changes to the dashboard charts

Resolves #3684 and 3686

### CODE REVIEW

**Review by bassgeta — DISMISSED** [review]
Nice solution turning the data into 2 sources beforehand and just going with the flow :sunglasses: 
Wayne with 4 teams :eyes: 
image
After creating a new team, it shows up with 0% :heavy_check_mark: 
image

**Review by mmioana — CHANGES_REQUESTED** [review]
Nice start on this issue @davecreaser 💯 

Created a new colony
Screenshot 2024-12-03 at 10 12 26

Toggled the reputation monitor on and awarded `leela` some reputation
Screenshot 2024-12-03 at 10 13 56

And the chart correctly shows the `100%` for `General`
Screenshot 2024-12-03 at 10 18 59


Then switched to `Wayne`
Screenshot 2024-12-03 at 10 20 23

Created one new team
Screenshot 2024-12-03 at 10 21 10
Screenshot 2024-12-03 at 10 21 19

And another one
Screenshot 2024-12-03 at 10 21 56
Screenshot 2024-12-03 at 10 22 02

However, after transferring some funds to one of the new teams and doing a simple payment to `leela`, on http://localhost:9091/wayne/teams I could see the reputation update, but the `All other` item in the chart still remains at `0` which is not correct 😢 
Screenshot 2024-12-03 at 10 25 02
Screenshot 2024-12-03 at 10 25 12

**Comment by davecreaser** [comment]
Ooh @mmioana what a catch! Yeah I totally missed that, thanks so much for finding it 🤝 

Should now be all good 😄 

And @bassgeta it wiped your kind review, apologies 😅

**Review by iamsamgibbs — APPROVED** [review]
Nice job Dave, all looking good here!

Screenshot 2024-12-04 at 12 49 38
Screenshot 2024-12-04 at 12 50 28
Screenshot 2024-12-04 at 12 50 58

**Review by rumzledz — APPROVED** [review]
Clean fix @davecreaser ! ✨ 

## 1. 4 teams

Screenshot 2024-12-04 at 22 12 00

## 2. 5 teams

Screenshot 2024-12-04 at 22 12 32

## 3. 6 teams

Screenshot 2024-12-04 at 22 13 02

**Review by mmioana — APPROVED** [review]
Thanks for the changes @davecreaser 🙌  it now works as expected 🎉 

Initial chart in `wayne`
Screenshot 2024-12-05 at 10 59 02
Created a new team
Screenshot 2024-12-05 at 10 59 33
Then another
Screenshot 2024-12-05 at 10 59 55
Transferred some funds to `test team 1` and did some simple payments to `leela`. The reputation for `test team 1` updated
Screenshot 2024-12-05 at 11 02 24
And the update is visible for all teams in the chart 
Screenshot 2024-12-05 at 11 02 28

Nicely done! 💯

**Pull request merged**
