### PR TITLE
Maintenance: Remove all css.d.ts files

### LINKED ISSUE #1767: Remove `css.d.ts` files and research CSS modules <> Tailwind alternatives
We have been ignoring `css.d.ts` files using `.gitignore` for a while now and they should be properly disabled/deleted. 

@chmanie raised concerns over using CSS modules with Tailwind. The other part of this issue is to research alternatives to this approach (and either implement it or open a separate issue for it).

### PR DESCRIPTION
**Pull request by iamsamgibbs**
## Description

We have been ignoring css.d.ts files using .gitignore for a while now and any remaining files needed deleting. This PR removes all .css.d.ts files.

## Discussion

@chmanie raised concerns over using CSS modules with Tailwind. The other part of this issue is to research alternatives to this approach (and either implement it or open a separate issue for it).

The main issue with how we are currently use CSS modules with Tailwind is the use of ‘@apply’. There are quite a few instances where we are using @apply just to avoid having long lines of tailwind directly in the components. We should avoid doing this where possible as it will result in the CSS bundle size increasing: https://tailwindcss.com/docs/reusing-styles#avoiding-premature-abstraction

---

[src/components/v5/common/Pills/PillsBase.module.css](https://github.com/JoinColony/colonyCDapp/blob/7fcc807642c9de671db6cfd4be9c6086607bfe7c/src/components/v5/common/Pills/PillsBase.module.css)

^ This is an example of where we are using @apply badly. This should just be used inline in the component file instead.

---

[src/components/common/Extensions/UserHub/partials/ReputationTab/partials/PendingReputation/PendingReputation.tsx](https://github.com/JoinColony/colonyCDapp/blob/7fcc807642c9de671db6cfd4be9c6086607bfe7c/src/components/common/Extensions/UserHub/partials/ReputationTab/partials/PendingReputation/PendingReputation.tsx#L39)

```
<div className={styles.row}>
  <p className={styles.rowName}>
```

^ This is an example of where we are using @apply simply because the same class is used multiple times in the component. (Both styles.row and styles.rowName are used multiple names in the same file). This should just be a variable in the component instead.

---

[src/components/shared/Avatar/Avatar.module.css](https://github.com/JoinColony/colonyCDapp/blob/7fcc807642c9de671db6cfd4be9c6086607bfe7c/src/components/shared/Avatar/Avatar.module.css)

^ Here we have a bunch of different size options, which is used in the component file like this:

`const class = styles[‘xs’];`

We should instead have a ‘sizeClasses’ variable in the component file which is simply an object containing the different tailwind classes:

```
const sizeClasses = {  
  xxxs: 'relative w-[1rem] h-[1rem] rounded-full',
  xxs: 'relative w-[1.125rem] h-[1.125rem] rounded-full',
  …
}
```

And would use it like:

`const class = sizeClasses[‘xs’];`

It’s a small but important change as it means we get the tailwind classes added directly rather than a css module class.

We could keep these in their own .ts files rather than directly in the component if it bloats the file too much.

---

[src/components/shared/Extensions/Toast/Toast.module.css](https://github.com/JoinColony/colonyCDapp/blob/7fcc807642c9de671db6cfd4be9c6086607bfe7c/src/components/shared/Extensions/Toast/Toast.module.css)

^ This seems like a good example of how we should be using @apply, where a third party package is adding components with set classnames and we want to apply our own styles.

In this instance we should keep the file as is.

---

After reviewing this I would suggest we remove as many uses of @apply as possible by either using the tailwind style directly in the component, or creating a classes object. There are 226 uses of @apply across the project so it may be a big task to refactor all these uses.

We would need to decide whether it is acceptable to move class objects into their own .ts files or if they should always remain part of the component file.

We would need to decide how to handle situations where a module.css file is imported in multiple places. If we simply moved the tailwind to a variable in each component then if any changes needed to be made to the styling it would need to be updated in multiple untracked places so this is not a suitable solution. We could instead replace the module.css file with a .ts file which simply exports variables with the tailwind styles.

We should discuss this further and make a decision on whether this is the best approach.

## Diffs

**Deletions** ⚰️

* All .css.d.ts files

Resolves #1767

### CODE REVIEW

**Review by chmanie — APPROVED** [review]
Really nice investigation! I agree with your findings and conclusions and they make sense to me. Have you looked into whether we could use the `@layer` directive to help us out somehow?

**Comment by iamsamgibbs** [comment]
Thank you!

I don’t think we would get much use from @layer. It lets you tell Tailwind which “bucket” a set of custom styles belong to, either `base`, `components` or `utilities`. It applies these buckets in order of specificity, so a class in `utilities` would override `components` which would override `base`. So it’s just a way of giving certain custom classes more specificity, you still hit the same issues as with @apply if you’re simply using tailwind classes in an @layer as it increases the bundle size.

**Comment by iamsamgibbs** [comment]
Somewhat related, but this package is highly suggested to use with tailwind and prettier and I don't believe we are currently using it: https://tailwindcss.com/blog/automatic-class-sorting-with-prettier would want to check it plays nicely with clsx.

**Review by rdig — APPROVED** [review]
Ran, built and tested this locally. Builds fine, as well as I can't really spot any UI regressions. So that that means this is good to go.

Screenshot from 2024-02-05 19-00-13
Screenshot from 2024-02-05 19-00-27

I do like the idea of having automatic sorting via the `prettier-plugin-tailwindcss`  plugin, but that should be done via  separate issue, as not bloat this more than it is.

**Review by ArmandoGraterol — DISMISSED** [review]
Nice job 🎉 Cleaning the CDapp one step at a time :)

**Review by chmanie — CHANGES_REQUESTED** [review]
Actually I have one more thing. While you deleted all the d.ts files, they are still being re-generated.
Please see this commit to see how to disable that in webpack: https://github.com/JoinColony/colonyCDapp/pull/1748/commits/553b095afbb61b34e6f41a01a91d1cf5e0d8cb7e#diff-26b9fc42ec181eee49b1258fab5ad305a630d25e505c747c22ed26f667d7084dR78

Please also remove d.ts file from the .gitignore. Thanks!

**Comment by iamsamgibbs** [comment]
Good catch! I've removed the @teamsupercell/typings-for-css-modules-loader package, updated the webpack files and gitignore.

**Review by rdig — APPROVED** [review]
Re-approved

**Review by chmanie — APPROVED** [review]
Great, thank you!

**Review by ArmandoGraterol — APPROVED** [review]
LGTM 👍

**Pull request merged**
