### PR TITLE
Fix[15665954]: action sidebar paddings and horizontal line

### PR DESCRIPTION
**Pull request by KornelKwiatkowski**
## Description

Task: https://tw.auroracreation.com/app/tasks/15665954

**Changes** 🏗

Resolved issues:
- The horizontal line should take the whole width.
- The paddings are not like on the design.

Before:

image

image

After:

image

image

### CODE REVIEW

**Review by rdig — COMMENTED** [review]
Seems ok, however I think this PR should also handle the padding for the "most popular actions" section, which inconsistent as well

Screenshot from 2023-11-23 13-48-26

**Comment by KornelKwiatkowski** [comment]
Hi @melyndav. Done :)

**Review by ArmandoGraterol — APPROVED** [review]
Short and sweet!

**Review by melyndav — APPROVED** [review]
Great work on that change @KornelKwiatkowski, thank you. Approved from my end.

**Review by arrenv — APPROVED** [review]
Good to go!

**Pull request merged**
