### PR TITLE
Fix: Handle uninstalled Staged Expenditure extension

### LINKED ISSUE #3304: Staged payments no longer handling uninstalled extension
## Steps to reproduce

1. Ensure you have the Staged payment extension installed.
2. Create a new Staged payment.
3. Go through the entire process, up until the Payment step.
4. Uninstall the Staged payment extension.
5. Return to the action and try to make payments.
6. Note the error in the console (with MetaTx disabled).

## Expected behaviour

As added in this issue - https://github.com/JoinColony/colonyCDapp/pull/2719

* There should be a message to cancel the payment in the case where a Staged payment not yet finalizable has had the Staged payment extension uninstalled.
* There should be an error that is shown to users for Staged payments in the Payment step, where the extension has been uninstalled. 

image

image

## Actual behaviour

* You are able to continue with a Staged payment that is no longer a staged payment after the extension is uninstalled.
* You are given the option to make payments within staged payment that has had the extension uninstalled.

image

### PR DESCRIPTION
**Pull request by jakubcolony**
## Description

This PR fixes an issue where users could interact with staged payments created using a different installation of the Staged Expenditure extension. In order for the checks to work properly, there is a [block-ingestor PR](https://github.com/JoinColony/block-ingestor/pull/285) that facilitates storing the relevant extension address on the expenditure object.

In addition, it fixes an issue with the flow where you could not see previous funding actions after you uninstalled the extension. That meant if there was an unclaimed motion, there was no way for you to claim it. 

## Testing

1. Install Staged Expenditure extension.
2. Create 4 staged payments - you might find the Redo action option useful with that:

image

3. Leave the first payment at the review step. Advance each of the remaining payments to further steps:
 - Review
 - Funding
 - Release
 - Payment

4. Uninstall Staged Expenditure extension.

5. Verify that the uninstalled extension warning is shown in each payment you created. You should also be able to go back to any of the previous steps and see the details of the action related to that step (ie. the creator, date, etc.).

7. Now install Staged Expenditure extension again.

8. Verify the warning is still shown for payments created using the uninstalled extension. 

9. Create another Staged Expenditure payment and move it through all stages to check for regressions.

image

image

image

Screenshot 2024-10-20 at 22 49 19

Resolves #3304

### CODE REVIEW

**Review by rdig — DISMISSED** [review]
Long way to test this one :)

But ran through all the stages and it seems to be behaving properly now. Nicely done! :100: 

Screenshot from 2024-10-22 15-47-34
Screenshot from 2024-10-22 15-50-58
Screenshot from 2024-10-22 15-51-08
Screenshot from 2024-10-22 15-51-49
Screenshot from 2024-10-22 15-52-06
Screenshot from 2024-10-22 15-52-10
Screenshot from 2024-10-22 15-52-13
Screenshot from 2024-10-22 15-52-17
Screenshot from 2024-10-22 15-52-48
Screenshot from 2024-10-22 15-52-57
Screenshot from 2024-10-22 15-53-00
Screenshot from 2024-10-22 15-53-03
Screenshot from 2024-10-22 15-53-06
Screenshot from 2024-10-22 15-54-16
Screenshot from 2024-10-22 15-54-21
Screenshot from 2024-10-22 15-54-29
Screenshot from 2024-10-22 15-54-35
Screenshot from 2024-10-22 15-54-44

**Review by iamsamgibbs — DISMISSED** [review]
Very nicely done Jakub! All the test cases work as expected.

Screenshot 2024-10-24 at 11 42 06
Screenshot 2024-10-24 at 11 42 12
Screenshot 2024-10-24 at 11 42 17
Screenshot 2024-10-24 at 11 42 21

I'm not sure whether these pills should change to the "Uninstalled" pill for extensions which have been uninstalled - I think this is how the reputation extension behaves as far as I remember. But this can be it's own PR.

Screenshot 2024-10-24 at 11 40 59

Tested making another staged payment on the new extension installation and all worked without issue. Great job!

**Review by mmioana — APPROVED** [review]
Nice job on this one @jakubcolony 👏 💯 

Installed the extension
Screenshot 2024-10-25 at 13 43 48

Created the 4 staged payments and advanced them to a different step
Screenshot 2024-10-25 at 13 49 04
Screenshot 2024-10-25 at 13 49 28
Screenshot 2024-10-25 at 13 49 51
Screenshot 2024-10-25 at 13 50 14
Screenshot 2024-10-25 at 13 51 24

Uninstalled the extension
Screenshot 2024-10-25 at 13 51 44
Screenshot 2024-10-25 at 13 51 49

The errors are showing up
Screenshot 2024-10-25 at 13 52 02
Screenshot 2024-10-25 at 13 52 06
Screenshot 2024-10-25 at 13 52 10
Screenshot 2024-10-25 at 13 52 16

Re-installed the extension
Screenshot 2024-10-25 at 13 52 49

The errors are still showing up for the previous staged payments
Screenshot 2024-10-25 at 13 53 01
Screenshot 2024-10-25 at 13 53 05
Screenshot 2024-10-25 at 13 53 09
Screenshot 2024-10-25 at 13 53 13

And for regression I created a new staged payment and managed to finalise it
Screenshot 2024-10-25 at 13 53 49
Screenshot 2024-10-25 at 13 54 25

Awesome job 🥇 

Just one question that I have @jakubcolony is if we don't want to actually show up the card in the Grouped actions list?

Without applying this diff, I didn't manage to see it yet there

```
diff --git a/src/components/v5/common/ActionSidebar/partials/PaymentGroup/GroupList.ts b/src/components/v5/common/ActionSidebar/partials/PaymentGroup/GroupList.ts
index e2c060dff..fcd52f47d 100644
--- a/src/components/v5/common/ActionSidebar/partials/PaymentGroup/GroupList.ts
+++ b/src/components/v5/common/ActionSidebar/partials/PaymentGroup/GroupList.ts
@@ -1,11 +1,11 @@
 import {
   HandCoins,
   Money,
+  Steps,
 
   // @TODO: uncomment when streaming payment,split payment and staged payment will be ready
   // Waves,
   // ArrowsOutLineHorizontal,
-  // Steps,
 } from '@phosphor-icons/react';
 
 import { Action } from '~constants/actions.ts';
@@ -43,13 +43,13 @@ export const GROUP_LIST = [
   //   Icon: ArrowsOutLineHorizontal,
   //   action: Action.SplitPayment,
   // },
-  // {
-  //   title: formatText({ id: 'actions.stagedPayment' }),
-  //   description: formatText({
-  //     id: 'actions.description.stagedPayment',
-  //   }),
-  //   Icon: Steps,
-  //   action: Action.StagedPayment,
-  //   isNew: true,
-  // },
+  {
+    title: formatText({ id: 'actions.stagedPayment' }),
+    description: formatText({
+      id: 'actions.description.stagedPayment',
+    }),
+    Icon: Steps,
+    action: Action.StagedPayment,
+    isNew: true,
+  },
 ];

```

**Comment by iamsamgibbs** [comment]
> Just one question that I have @jakubcolony is if we don't want to actually show up the card in the Grouped actions list?

There is an issue for this @mmioana :) #3441

**Review by iamsamgibbs — APPROVED** [review]
All still working after the rebase:

Screenshot 2024-10-30 at 11 31 20
Screenshot 2024-10-30 at 11 31 31
Screenshot 2024-10-30 at 11 31 43
Screenshot 2024-10-30 at 11 31 50
Screenshot 2024-10-30 at 11 32 13
Screenshot 2024-10-30 at 11 32 43
Screenshot 2024-10-30 at 11 32 51

**Review by mmioana — APPROVED** [review]
Nice work @jakubcolony all works well even after rebasing 🎉 

Screenshot 2024-10-30 at 13 53 55
Screenshot 2024-10-30 at 13 55 43
Screenshot 2024-10-30 at 13 56 11
Screenshot 2024-10-30 at 13 56 51
Screenshot 2024-10-30 at 13 57 50
Screenshot 2024-10-30 at 13 57 59
Screenshot 2024-10-30 at 13 58 23
Screenshot 2024-10-30 at 13 58 32
Screenshot 2024-10-30 at 13 58 38
Screenshot 2024-10-30 at 13 58 42
Screenshot 2024-10-30 at 13 58 50
Screenshot 2024-10-30 at 14 00 36

**Pull request merged**
