### PR TITLE
fix: disabling action fields and buttons while its in pending mode

### PR DESCRIPTION
**Pull request by CzarekDryl**
https://tw.auroracreation.com/app/tasks/15656428

Changes in PR:
- disabled all fields and buttons while action is in pending mode

### CODE REVIEW

**Review by arrenv — CHANGES_REQUESTED** [review]
@CzarekDryl I am getting this error in console when outside of ColonyContext.

image

I am also able to edit fields while the button is pending, this was the result of a failed transaction.

image

**Review by jakubcolony — COMMENTED** [review]
All looks good, but I'm seeing the following issue when trying to create an action with description on this branch, which doesn't seem to happen on master:

https://github.com/JoinColony/colonyCDapp/assets/112586815/c53e0ca8-f749-4508-99d8-171296be5fad

Could someone else confirm if it's happening to them too?

**Comment by TomaszChmielPagepro** [comment]
This was fixed already in this PR https://github.com/JoinColony/colonyCDapp/pull/1483/files#diff-c9879fd623c2c9f88bd53ae62d4bfc1f1560d4d6bc8acf5c6041240b23abdb5c
@CzarekDryl you can close this or we can move code related to this task to this PR

**Comment by CzarekDryl** [comment]
@arrenv @jakubcolony Thanks for checking this one, but I'm closing this because it was fixed by @TomaszChmielPagepro in [#1483](https://github.com/JoinColony/colonyCDapp/pull/1483/files#diff-c9879fd623c2c9f88bd53ae62d4bfc1f1560d4d6bc8acf5c6041240b23abdb5c)

**Pull request closed without merging**
