### PR TITLE
Update dev environment for Hardhat

### PR DESCRIPTION
**Pull request by kronosapiens**
Mostly just invocation and path updates, nothing too crazy

### CODE REVIEW

**Review by rdig — CHANGES_REQUESTED** [review]
The package `@colony.io/colony-network-contracts@1.0.0` fails to install when building the network image. Could not get past that step.

Maybe the image that ours is based off needs to run a higher (or lower) version of `node` ? https://github.com/JoinColony/colonyCDapp/blob/e0ff4f64e73b8f798c1da1620042b9a1fa8fccb6/docker/colony-cdapp-dev-env-network#L1

Screenshot from 2024-03-30 19-10-33
Screenshot from 2024-03-30 19-11-22

**Comment by kronosapiens** [comment]
The unsupported engine warnings are normal -- network is still pinned to node 14 due to the dapp. We'll be able to upgrade once the dapp is out of production.

Looks like the error was due to a connection issue?

**Review by iamsamgibbs — CHANGES_REQUESTED** [review]
All installed okay for me, but I'm instead getting this block-ingestor error:

```
ingestor       | 2024-04-02T10:02:29.892Z Block Ingestor started on chain undefined
ingestor       | 2024-04-02T10:02:29.893Z Stats available at http://localhost:10001/stats
ingestor       | 2024-04-02T10:02:29.893Z Liveness check available at http://localhost:10001/liveness
ingestor       | 2024-04-02T10:02:29.893Z Last processed block number: 1
ingestor       | 2024-04-02T10:02:29.902Z Setting up listener for OneTxPayment extensions
ingestor       | 2024-04-02T10:02:29.903Z Setting up listeners for VotingReputation extensions
ingestor       | 2024-04-02T10:02:29.903Z Setting up listeners for StakedExpenditure extensions
ingestor       | 2024-04-02T10:02:29.904Z Setting up listeners for StagedExpenditure extensions
ingestor       | 2024-04-02T10:02:29.904Z Setting up listeners for StreamingPayments extensions
ingestor       | 2024-04-02T10:02:29.905Z Block listener started
ingestor       | 2024-04-02T10:02:29.913Z Fetching blocks from block 2 to 931
ingestor       | 2024-04-02T10:02:29.921Z Block 931 added to the queue
ingestor       | 2024-04-02T10:02:29.922Z Processing block 2
ingestor       | /colonyCDappBackend/block-ingestor/node_modules/@ethersproject/logger/src.ts/index.ts:269
ingestor       |         const error: any = new Error(message);
ingestor       |                            ^
ingestor       | Error: call revert exception [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="getFeeInverse()", data="0x", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.7.0)
ingestor       |     at Logger.makeError (/colonyCDappBackend/block-ingestor/node_modules/@ethersproject/logger/src.ts/index.ts:269:28)
ingestor       |     at Logger.throwError (/colonyCDappBackend/block-ingestor/node_modules/@ethersproject/logger/src.ts/index.ts:281:20)
ingestor       |     at Interface.decodeFunctionResult (/colonyCDappBackend/block-ingestor/node_modules/@ethersproject/abi/src.ts/interface.ts:427:23)
ingestor       |     at Contract.<anonymous> (/colonyCDappBackend/block-ingestor/node_modules/@ethersproject/contracts/src.ts/index.ts:400:44)
ingestor       |     at step (/colonyCDappBackend/block-ingestor/node_modules/@ethersproject/contracts/lib/index.js:48:23)
ingestor       |     at Object.next (/colonyCDappBackend/block-ingestor/node_modules/@ethersproject/contracts/lib/index.js:29:53)
ingestor       |     at fulfilled (/colonyCDappBackend/block-ingestor/node_modules/@ethersproject/contracts/lib/index.js:20:58)
ingestor       |     at processTicksAndRejections (node:internal/process/task_queues:95:5) {
ingestor       |   reason: null,
ingestor       |   code: 'CALL_EXCEPTION',
ingestor       |   method: 'getFeeInverse()',
ingestor       |   data: '0x',
ingestor       |   errorArgs: null,
ingestor       |   errorName: null,
ingestor       |   errorSignature: null,
ingestor       |   address: '0x5CC4a96B08e8C88f2c6FC5772496FeD9666e4D1F',
ingestor       |   args: [],
ingestor       |   transaction: {
ingestor       |     data: '0xef63c380',
ingestor       |     to: '0x5CC4a96B08e8C88f2c6FC5772496FeD9666e4D1F'
ingestor       |   }
ingestor       | }
ingestor exited with code 1
```

**Comment by kronosapiens** [comment]
@iamsamgibbs I believe I've sorted out the block ingestor issue, give it another try

**Review by iamsamgibbs — DISMISSED** [review]
Everything installs and builds okay now! 🎉 

However, the create-data.js script is getting an invalid json response.

```
/Users/samuelgibbs/Code/colonyCDapp/node_modules/node-fetch/lib/index.js:273
                                return Body.Promise.reject(new FetchError(`invalid json response body at ${_this2.url} reason: ${err.message}`, 'invalid-json'));
                                                           ^
FetchError: invalid json response body at http://localhost:3006/ganache-accounts.json reason: Unexpected end of JSON input
    at /Users/samuelgibbs/Code/colonyCDapp/node_modules/node-fetch/lib/index.js:273:32
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async createUserAndColonyData (/Users/samuelgibbs/Code/colonyCDapp/scripts/create-data.js:1092:18) {
  type: 'invalid-json'
}

Node.js v20.11.0
```

I also get the same invalid json error when trying to connect a wallet:

Screenshot 2024-04-05 at 08 43 08

**Comment by area** [comment]
Now that 7dd47b7 has been included in `master`, I've cherry-picked my commits from the `maint/hardhat-arbitrum` branch and fixed conflicts, such that I believe this now works - was able to `npm run dev`, run the `create-data` script and browse around/create some actions. I think it would be best to wait until Raul has finished picking what he wants from `master-arbitrum` in to `master` though (which is hopefully later today), as I know there are things that are broken here that are fixed with some of that work (e.g. the missing network bubble in the top-right when developing locally).

**Review by bassgeta — APPROVED** [review]
I tried creating some actions, connecting my wallet, all seems to work so from my side this is all good to go :+1:

**Review by rdig — APPROVED** [review]
Fixed, tested and re-tested. All good from my end!

**Review by area — APPROVED** [review]
Also tested after Raul's fixes.

**Pull request merged**
