### PR TITLE
Fix: position the Stepper buttons above the dotted lines

### LINKED ISSUE #2535: Mobile: Broken step navigation pills
## Description

On mobile, the stepped navigation pills are displaying broken. In this example below, the supported pill is behind the navigation line and isn't able to be selected by users. The example below:

image

Transaction in question: https://app.colony.io/beta/activity?tx=0x89733ad4a904d4bbbdec1efaadc499009cf80fffb830c50c70afdb9ff8a32f4f

Another example in production:
image

Transaction link: https://app.colony.io/beta/activity?tx=0xddeaf829e550e26ba851734bd6c540f32899e5b140ac6fbbad8702e0efa6aa6a 

The PR should fix this display issue and allow all pills to show correctly and be selected by users on mobile.

### PR DESCRIPTION
**Pull request by rumzledz**
## Description

| Before | After |
| ---- | ---- |
|  Screenshot 2024-06-18 at 16 00 27 | Screenshot 2024-06-18 at 15 57 31 |

## Testing

1. Enable the "Reputation weighted" extension and use the "Testing governance" preset
2. Create a Simple Payment and choose the "Reputation" decision method
3. Support the stake and submit the Max staking amount
4. Run the following commands to forward the time:
```
curl -X POST --data '{"jsonrpc":"2.0","method":"evm_increaseTime","params":[3600],"id":1}' localhost:8545
curl -X POST --data '{"jsonrpc":"2.0","method":"evm_mine","params":[],"id":1}' localhost:8545
```
5. Reload the page
6. Make sure the pill button is above the dotted lines

## Diffs

**Changes** 🏗

* Just a slight update for the Stepper Button's z-index

Resolves #2535#2535

### CODE REVIEW

**Review by melyndav — DISMISSED** [review]
Thanks for the fix on this one @rumzledz and for picking up my issue, much appreciated. The pill is displaying as expected.

image

**Review by mmioana — DISMISSED** [review]
Awesome @rumzledz! Can confirm the pill si no longer shown behind the dotted line even for rejected stake

Screenshot 2024-06-20 at 09 39 49

**Comment by rumzledz** [comment]
> However, there are some preconfigured z-index options in the tailwind config as it is preferred to use these:
> 
> Screenshot 2024-06-27 at 14 12 18
> Could you switch this out for `z-base`, I've noticed use of `z-10` in one other file, could you update it there too whilst you're at it?

Thanks for letting me know about these zIndex presets @iamsamgibbs, apologies I wasn't aware! And yes, I'll update the other one as well 👌

**Comment by rumzledz** [comment]
> (I've also noticed a few arbitrary uses (z-[x]) which should be avoided if possible. We might need to add something to enforce the use of the configured options?)

Tricky one but yes, I'll figure something out 😄  @iamsamgibbs

**Comment by rumzledz** [comment]
Hi @melyndav @mmioana @iamsamgibbs , I had to rebase my branch so all the approvals were wiped. Can you please have a look again? Thank you 🙏

**Review by mmioana — APPROVED** [review]
Awesome @rumzledz 👏 
Screenshot 2024-07-05 at 11 09 20

**Review by iamsamgibbs — APPROVED** [review]
Looks good to me!

Screenshot 2024-07-05 at 12 26 46

**Review by melyndav — APPROVED** [review]
Awesome work on this one @rumzledz! Thanks for the work to fix this issue! 💯

**Pull request merged**
