### PR TITLE
feat: filtering by multisig motion status

### PR DESCRIPTION
**Pull request by joanna-pagepro**
## Description

Multi Sig - filtering activity table data by status

## Testing

* Step 1. Make sure that you have some actions created using Multi-Sig and go to the activity page
* Step 2. Filter actions by status and check if correct data is displayed

## Diffs

**New stuff** ✨

* 

**Changes** 🏗

* `hasActionCompleted` added to return Passed state

**Deletions** ⚰️

* 

## TODO

Resolves https://github.com/JoinColony/colonyCDapp/issues/2523

### CODE REVIEW

**Comment by iamsamgibbs** [comment]
@joanna-pagepro is this ready to review? It looks like some work may have not made it up.

**Comment by joanna-pagepro** [comment]
@iamsamgibbs yes, it's ready to review

**Review by iamsamgibbs — APPROVED** [review]
Nice job Joanna! All looks good to me!

Screenshot 2024-07-23 at 09 31 25

Screenshot 2024-07-23 at 09 33 49

Screenshot 2024-07-23 at 09 36 56

This wasn't included in the scope of the original issue, but we'll need to handle this decision method filter too:

Screenshot 2024-07-23 at 09 32 12

If you could either handle it as part of this PR, or create a new PR for it that would be great.

**Review by davecreaser — APPROVED** [review]
Thanks @joanna-pagepro, it's working great. I agree with Sam too, it would be awesome to have that decision method filter working here also.

Screenshot 2024-07-23 at 10 06 52
Screenshot 2024-07-23 at 10 07 11
Screenshot 2024-07-23 at 10 07 21
Screenshot 2024-07-23 at 10 07 29

**Review by arrenv — CHANGES_REQUESTED** [review]
@joanna-pagepro Nice work on this, thank you for adding it.

The filters look to be working as expected, in teams, and with the new statuses.

image


1. I agree with both @davecreaser and @iamsamgibbs, we should have the Decision method filter here as well.

2. What is the logic to the sorting of the status filters? I think the easiest way to sort these would be just alphabetically, this should be easier to find the filter option you are looking for.

image

**Comment by joanna-pagepro** [comment]
@arrenv @iamsamgibbs @davecreaser PR updated, can you check again?

**Comment by davecreaser** [comment]
Hey @joanna-pagepro, thanks for adding that decision method filter in, appreciated!

I can confirm it's working and I can now filter by decision methods.

Screenshot 2024-07-24 at 14 20 49
Screenshot 2024-07-24 at 14 21 00

There is one issue I spotted though: the filter is behaving like a radio input, not a checkbox, so I cannot choose to filter by multiple decision methods. Could you take a look at that please? Thank you!

**Review by davecreaser — CHANGES_REQUESTED** [review]
Code wise all looking good, just one comment about the filtering behaviour which should be addressed. Thanks!

**Comment by joanna-pagepro** [comment]
@davecreaser done, can you check again?

**Review by iamsamgibbs — CHANGES_REQUESTED** [review]
Thanks for adding the decision method filtering into this!
 
Screenshot 2024-07-25 at 10 22 14

I'm unable to test if reputation motions are working due to an unrelated bug, but the code looks good.

However, filtering by action type doesn't seem to be working for multi-sig motions:


https://github.com/user-attachments/assets/24c53221-4ffe-460a-a0d0-34a64f4a6f06


https://github.com/user-attachments/assets/5174a475-5a70-4b18-b6d7-2cc19582bdc6

**Comment by joanna-pagepro** [comment]
@iamsamgibbs you should be able to filter by action type too. Can you check?

**Comment by iamsamgibbs** [comment]
@joanna-pagepro can you rebase this and I'll give it a review today

**Comment by joanna-pagepro** [comment]
@iamsamgibbs done!

**Review by iamsamgibbs — APPROVED** [review]
Thanks for the changes, this looks good to me!

Able to filter by action type:

Screenshot 2024-07-26 at 16 18 57

Able to filter by multi-sig decision method:

Screenshot 2024-07-26 at 16 19 05

Able to filter by motion decision method:

Screenshot 2024-07-26 at 16 20 20

**Pull request merged**
