### PR TITLE
Tweak user menu styles

### LINKED ISSUE #1410: Hamburger menu disconnected state
## Description

When disconnected, the hamburger menu is experiencing some display issues as seen below on **desktop and tablet sizes.**

image

The width should match the Figma component: https://www.figma.com/file/5V8pr7iMwXsT9L3VAZsmUt/Colony-V5?type=design&node-id=1941-199581&mode=design&t=BSCYCfiUenPPppRe-4

### PR DESCRIPTION
**Pull request by ArmandoGraterol**
Fixed the width being wrong on the disconnected state of user menu. 

Also tweaked a bit styles that weren't as aligned with the specs as they could have.

Screenshot 2023-11-28 at 19 53 00

Screenshot 2023-11-28 at 19 53 10

Resolves #1410

### CODE REVIEW

**Review by bassgeta — APPROVED** [review]
Looks good! Finally, no more janky user popup :D!

**Review by arrenv — CHANGES_REQUESTED** [review]
Nice one @ArmandoGraterol! Some things I noticed.

1. There is now extra padding on the nested menu.

image

2. There is an overflow when navigating to nested menus, I have slowed down the recording for dramatic effect. The overflow likely needs to be hidden, we just need to double check that it does not impact anything else if the component is used elsewhere.
overflow-menu

**Comment by ArmandoGraterol** [comment]
@arrenv Thank you for catching those! They should be fixed :) As far as I know, the overflow hidden changes shouldn't affect any other part other than the user menu's connected and disconnected state but let me know if you find something else anyways!

**Review by bassgeta — DISMISSED** [review]

**Review by melyndav — CHANGES_REQUESTED** [review]
Hey @ArmandoGraterol thanks for fixing this issue, it's great to see this looking the way it should.

A couple of very minor updates:

1. This HR in the disconnected state isn't needed.
image

2. There is extra padding missing here, it should be 16px 
image

3. For the hover states can we have the same as what is global across the app:

image

Link to example in Figma.

**Review by melyndav — DISMISSED** [review]
Hey @ArmandoGraterol super smooth work on this. Thanks for those extra UI updates. I did a good check of other dropdown menus that match this menu and don't see any issues. So I think we're all good to go. Thanks again!

**Review by thomassdk — CHANGES_REQUESTED** [review]
Hi armando this looks good but im getting the flash of the content when moving between options on the user menu

[Screencast from 2023-12-05 10-56-02.webm](https://github.com/JoinColony/colonyCDapp/assets/32598350/54a53ab6-4d20-4e63-87da-8ebaa33b8faf)

**Comment by ArmandoGraterol** [comment]
@thomassdk Hey that's an old issue that should have been fixed by one of my commits on this branch. I'm currently not able to reproduce it, could you check that your local branch is up-to-date?

**Review by thomassdk — APPROVED** [review]
Yep seems like the branch was out of date. Good work Armando

**Review by bassgeta — APPROVED** [review]

**Review by arrenv — APPROVED** [review]
Approved!

**Pull request merged**
