### PR TITLE
Added proper richtext styles

### PR DESCRIPTION
**Pull request by TomaszChmielPagepro**
Fixes some of the issues from #1611

The only issue left is clipping the content to 2 lines when it is not expanded.

### CODE REVIEW

**Comment by rdig** [comment]
Is this ready for review still? I noticed it got changed back to Draft

**Comment by joanna-pagepro** [comment]
Clipping the content to 2 lines when it is not expanded added

**Review by ArmandoGraterol — CHANGES_REQUESTED** [review]
Nice work! I've noticed that the space between each new line is still `16px` when it should be half of that:
Screenshot 2024-01-15 at 12 28 56

**Comment by joanna-pagepro** [comment]
> Nice work! I've noticed that the space between each new line is still `16px` when it should be half of that: Screenshot 2024-01-15 at 12 28 56

@ArmandoGraterol @melyndav  Where can I find an example with an `8px` gap? I can only see a `16px` gap between elements on a design. Maybe there are some rules that I'm not aware of.

**Comment by joanna-pagepro** [comment]
@ArmandoGraterol @arrenv please review again

**Comment by bassgeta** [comment]
> @joanna-pagepro Looking much better, thank you :)
> 
> image
> 
> The formatting just did not work in the completed state, but that should get resolved here - #1608
> 
> image

Just a heads up, that it will work there but not for all possible action types
We have the following issues which need to be wrapped up for it to properly work everywhere
1. https://github.com/JoinColony/colonyCDapp/issues/1645
2. https://github.com/JoinColony/colonyCDapp/issues/1646
3. https://github.com/JoinColony/colonyCDapp/issues/1647
4. https://github.com/JoinColony/colonyCDapp/issues/1648
5. https://github.com/JoinColony/colonyCDapp/issues/1649
6. https://github.com/JoinColony/colonyCDapp/issues/1650
7. https://github.com/JoinColony/colonyCDapp/issues/1651

**Review by ArmandoGraterol — APPROVED** [review]

**Pull request merged**
