### PR TITLE
fix: filtering dropdown menus

### PR DESCRIPTION
**Pull request by joanna-pagepro**
https://tw.auroracreation.com/app/tasks/15702934
image

Updated padding:
image

Filter button on mobile:
image

`Header` component from the old version was removed, because it wasn't used anywhere in the app.

### CODE REVIEW

**Review by ArmandoGraterol — CHANGES_REQUESTED** [review]
I've found some more dropdowns that need their spacing changed to 24px top - 24px bottom:

Screenshot 2024-01-03 at 13 09 06
Screenshot 2024-01-03 at 13 10 23
FireShot Capture 268 - Balances - Colony - Planet Express - localhost
FireShot Capture 270 - Colony App - localhost
FireShot Capture 271 - Planet Express - Colony - localhost
FireShot Capture 272 - Planet Express - Colony - localhost
FireShot Capture 273 - Planet Express - Colony - localhost

All of them have incorrect padding, either they have 24px top - 16px bottom or 16x16 straight-up.

**Comment by joanna-pagepro** [comment]
@ArmandoGraterol I've checked all the dropdowns and found bad values in one of them - select permission type. All others have correct padding values because they have 16px padding top and bottom, but almost all items inside have 8px padding top and bottom, so when you add those values you will get 24px spacing. It had to be done this way, because buttons have hover effects that require 8px padding. Let me know if it's ok now.

**Review by ArmandoGraterol — APPROVED** [review]
Looks good to me! Thank your for pointing that out as I didn't notice it in the first review

**Comment by joanna-pagepro** [comment]
@ArmandoGraterol I had to resolve conflicts. Can you approve it again so that I can merge it?

**Review by ArmandoGraterol — APPROVED** [review]

**Review by CzarekDryl — APPROVED** [review]

**Pull request merged**
