### PR TITLE
fix: uninstalled motion state

### PR DESCRIPTION
**Pull request by joanna-pagepro**
## Description

After uninstalling the `Reputation Weighted` extension, motion statuses are showing wrong status - `Invalid`. In such situation it should be `Uninstalled` and a box with the information about the uninstalled extension should be visible instead of the `Stepper` component inside the action preview (sidebar) component.

## Testing

* Step 1. Install `Reputation Weighted` extension if it's not installed yet
* Step 2. Create a `Create agreement` action and stake it, so that it shows up in the list
* Step 3. Deprecate and uninstall the `Reputation Weighted` extension
* Step 4. Go to the agreements page and open the agreement card

## Diffs

**New stuff** ✨

* new motion state `Uninstalled` shown when motion failed and voting reputation extension is uninstalled
* `ExtensionStatusBox` component to show that extension is uninstalled

**Changes** 🏗

* `getMotionState` function is also getting `isVotingReputationEnabled` arg right now, and based on that and networkMotionState we can return the `Uninstalled` status.

**Deletions** ⚰️

* 

Resolves https://github.com/JoinColony/colonyCDapp/issues/2080

### CODE REVIEW

**Review by melyndav — CHANGES_REQUESTED** [review]
Thanks for your work on this @joanna-pagepro it's working as expected when I deprecate and uninstall.

image

However, if I install and enable the extension again, this state should remain. However, it goes back to the invalid state and shows the empty motion pills.

image

**Comment by joanna-pagepro** [comment]
@melyndav this is what the API returns. @arrenv @rdig can you help here?

**Comment by arrenv** [comment]
> @melyndav this is what the API returns. @arrenv @rdig can you help here?

Is there a way to interpret the response from the API? Such as, comparing the active extension ID with the ID in the motion id?

**Comment by rdig** [comment]
So the the way this works is that once you uninstall the extension you have no more state for that motion, past or present.

Installed:
Screenshot from 2024-04-15 17-28-47
Screenshot from 2024-04-15 17-28-54

Uninstalled: (not voting rep extension active)
Screenshot from 2024-04-15 17-32-29
Screenshot from 2024-04-15 17-32-34

Reinstalled:
Screenshot from 2024-04-15 17-33-20
Screenshot from 2024-04-15 17-33-27

This is pretty easy to solve, at least from the UI perspective, in the context of this issue.

As long as your status is `Invalid` / network state is `0`, you can safely display the "uninstalled" banner

There shouldn't be any other instances where you get a `0` network state, so you can blanket assume that the extension was unistalled at some point

**Comment by joanna-pagepro** [comment]
Ok, so right now if the status is `Invalid`, I'm showing `Uninstalled` pill

**Review by iamsamgibbs — CHANGES_REQUESTED** [review]
Good start to this ticket!

The status is correctly showing "Uninstalled" for old motions which were done on previous installations of the extension.

Screenshot 2024-04-16 at 14 20 07

The status is correctly showing in the sidebar too.

Screenshot 2024-04-16 at 14 18 51

However, when the extension is installed again this status disappears:

Screenshot 2024-04-16 at 14 19 23

The motions also go to the "Uninstalled" state when the extension is deprecated (before it is uninstalled). From my understanding, when in the deprecated state it should still be possible to proceed through the remaining motion steps and finalize the motion.

Screenshot 2024-04-16 at 14 20 32

**Comment by rdig** [comment]
@iamsamgibbs @joanna-pagepro 

> The motions also go to the "Uninstalled" state when the extension is deprecated (before it is uninstalled). From my understanding, when in the deprecated state it should still be possible to proceed through the remaining motion steps and finalize the motion.

Sam is correct in this assumption. This needs to be addressed as while the extension is deprecated, all currently active motions can still be interacted with, even more so we get the correct state from them from the action/motion object

**Comment by arrenv** [comment]
> @rdig @melyndav how should the last step look like? Should there be a separate status for this state like `Extension deprecated` or something like this?

@joanna-pagepro When the extension is in a deprecated state the existing and past motions will still work as if it was enabled. You are just not able to create new ones. So, there should not need to be a different state for it.

**Pull request closed without merging**
