### PR TITLE
Move colonyNetwork commit up to one with Node 20 support

### PR DESCRIPTION
**Pull request by area**
## Description

Mostly what it says on the tin. We're bringing the network repository up to Node 20, so the dev environment here needs updating too :smile:

We now get to base ourselves on the `colony-cdapp-dev-env` image which will improve the from-scratch startup time slightly. Hopefully we can stay in lock-step from now on, node version wise!

## Testing

Just check the dev environment still works as expected, whatever that means for you

### CODE REVIEW

**Review by ArmandoGraterol — COMMENTED** [review]
I'm getting this error after removing the network containers (before I did that too) (just in case) and running `npm run dev`:

Screenshot 2024-05-01 at 16 24 27

**Review by jakubcolony — COMMENTED** [review]
Similar on my end:
image

**Review by rdig — APPROVED** [review]
Seems to be working for me

Screenshot from 2024-05-02 13-45-50
Screenshot from 2024-05-02 13-48-00
Screenshot from 2024-05-02 13-46-06

Do note however that I've removed all the old containers and images and recreated everything from scratch

**Comment by area** [comment]
Reverted to draft, because I don't want this merged yet (it's using a commit on the network side that is experimental), but interested in whether this current version works for you (I've amended the latest commit on autopilot, apologies for that, so take care when pulling or otherwise checking out that you're on the right commit), as it does for me on OSX.

**Comment by iamsamgibbs** [comment]
I'm experiencing the following error when running `npm i` (after rm -rf node_modules for good measure)

```
npm ERR! code 1
npm ERR! path /Users/samuelgibbs/Code/colonyCDapp/node_modules/vite/node_modules/esbuild
npm ERR! command failed
npm ERR! command sh -c node install.js
npm ERR! [esbuild] Failed to find package "@esbuild/darwin-arm64" on the file system
npm ERR! 
npm ERR! This can happen if you use the "--no-optional" flag. The "optionalDependencies"
npm ERR! package.json feature is used by esbuild to install the correct binary executable
npm ERR! for your current platform. This install script will now attempt to work around
npm ERR! this. If that fails, you need to remove the "--no-optional" flag to use esbuild.
npm ERR! 
npm ERR! [esbuild] Trying to install package "@esbuild/darwin-arm64" using npm
npm ERR! node:internal/errors:932
npm ERR!   const err = new Error(message);
npm ERR!               ^
npm ERR! 
npm ERR! Error: Command failed: /Users/samuelgibbs/Code/colonyCDapp/node_modules/vite/node_modules/esbuild/bin/esbuild --version
npm ERR!     at checkExecSyncError (node:child_process:890:11)
npm ERR!     at Object.execFileSync (node:child_process:926:15)
npm ERR!     at validateBinaryVersion (/Users/samuelgibbs/Code/colonyCDapp/node_modules/vite/node_modules/esbuild/install.js:99:28)
npm ERR!     at /Users/samuelgibbs/Code/colonyCDapp/node_modules/vite/node_modules/esbuild/install.js:286:5
npm ERR!     at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
npm ERR!   status: null,
npm ERR!   signal: 'SIGKILL',
npm ERR!   output: [ null, Buffer(0) [Uint8Array] [], Buffer(0) [Uint8Array] [] ],
npm ERR!   pid: 57015,
npm ERR!   stdout: Buffer(0) [Uint8Array] [],
npm ERR!   stderr: Buffer(0) [Uint8Array] []
npm ERR! }
npm ERR! 
npm ERR! Node.js v20.11.0
```

**Comment by area** [comment]
I think unfortunately that's an issue with the repository at the moment - there's no way the files I've edited could have affected `npm i`? I got the same (for my architecture) recently, I _think_ when I checked it out to work on this originally. If you install that package yourself, it'll proceed.

**Comment by area** [comment]
Updated once more with a new network hash. This also incorporates a new `npm run hardhat` command and removes `npm run truffle`, which has stopped working with the move to hardhat on the network side.

The hardhat console is very similar to the truffle console, but the syntax is different. There are [docs](https://hardhat.org/hardhat-runner/docs/guides/hardhat-console) but you'll be able to get a long way with, for example, `c = await ethers.getContractAt("IColony", 0x1234...5678)`. It can also take an ethers signer as a third parameter if you want to send transactions.

**Review by rdig — APPROVED** [review]
Tested and working

Screenshot from 2024-05-21 11-33-39

Screenshot from 2024-05-21 11-37-03


I've tested:
- dev env startup
- data creation script
- manual colony creation
- manual action creation (mint)

**Pull request merged**
