### PR TITLE
fix: remove permissions

### PR DESCRIPTION
**Pull request by joanna-pagepro**
## Description

Removing user permissions action update

## Testing

Check this scenario for users with custom and predefined roles

* Step 1. Open the Manage permissions action
* Step 2. Select a user with permissions
* Step 3. Select to remove the permissions option from the permissions dropdown
* Step 4. Complete the action and see the UI

## Diffs

**New stuff** ✨

* permissions validation

**Changes** 🏗

* displaying the table for remove permissions action (form and completed action)
* displaying an error when a user doesn't have any permissions in the selected domain and we want to use remove action

**Deletions** ⚰️

* 

## TODO

- [x] Add `Removed` pill when designs will be ready

Resolves https://github.com/JoinColony/colonyCDapp/issues/2339 and https://github.com/JoinColony/colonyCDapp/issues/2241

### CODE REVIEW

**Comment by joanna-pagepro** [comment]
@arrenv can you check this one again?

**Review by arrenv — CHANGES_REQUESTED** [review]
@joanna-pagepro The inherited permissions is a nice addition, thank you. To help reduce confusion for users. Can we remove the validation error and highlighting of the field when you switch to that parent team.

In my gif, you can see the inherited permissions message showing, but as you select to the parent team, the validation message remains.


permission-inherit-change

**Comment by joanna-pagepro** [comment]
@arrenv can you check if it's ok now?

**Review by arrenv — APPROVED** [review]
@joanna-pagepro Thank you for the updates, everything I tested worked as expected. Nice one!

**Pull request closed without merging**
