### PR TITLE
feat: hide existing tokens from tokens select

### PR DESCRIPTION
**Pull request by joanna-pagepro**
## Description

Hiding tokens that are already added to the table from the token dropdown list

## Testing

* Step 1. Open the action sidebar and select the `Manage tokens` action type.
* Step 2. Add a new token
* Step 3. Add a new row to the table and check if the newly added token is visible on the list inside the token dropdown.
* Step 4. Add the same token to the table using token address and try to change it.

## Diffs

**New stuff** ✨

* 

**Changes** 🏗

* `filterOptionsFn` added to `TokenSelect` component

**Deletions** ⚰️

* 

Resolves https://github.com/JoinColony/colonyCDapp/issues/2673

### CODE REVIEW

**Review by arrenv — COMMENTED** [review]
@joanna-pagepro Works exactly as expected.

Let me know if you would like the following as another issue.

While testing I identified some opportunities to make some enhancements to the dropdown.

Mostly around wording and handling empty states and searches.

Figma design link can be seen here - https://www.figma.com/design/l1dOM5qiQYwF0ElvKDqqjg/Design-System---Colony-v3?node-id=4689-11024&t=kxXjXROKeijA9ORF-4

image


## Acceptance criteria
- Default
    - Shows the list of approved tokens, excluding ones already added (as you have done in this PR).
    - "Suggested tokens" to be used as the default title.
    - Change "Search" & "Select token or enter contract address" to "Select token or enter token address".
- Default but all suggested tokens are already added
    - Add a new token empty state is shown.
    - No title.
- Search by name
    - Filters the list of suggested tokens.
    - No title.
    - Empty state is "No token found" state.
- Search by token address
    - Finds the token name by address and shows in list to select.
    - No title.
    - Empty state is "No token found" state.

**Review by iamsamgibbs — APPROVED** [review]
Thanks for this change @joanna-pagepro all looking great.

Filtered from list when adding:
Screenshot 2024-07-12 at 11 20 31

Filtered from list if it was already been added:
Screenshot 2024-07-12 at 11 21 05

**Comment by joanna-pagepro** [comment]
@arrenv enhancements added. @iamsamgibbs can you test this one again?

**Review by arrenv — CHANGES_REQUESTED** [review]
@joanna-pagepro Thank you, working great. I noticed one issue and would like to make one additional enhancement to improve the user experience.

1. If you do a token address search, and clear or click out, the result shows up as a suggested token.
searching-stays-there



2. Is it possible to add the checkboxes in like to have in Manage verified members?
image

**Review by davecreaser — APPROVED** [review]
Nice one @joanna-pagepro all looking good on my side.

Tested and working as expected:
Screenshot 2024-07-15 at 09 21 52
Screenshot 2024-07-15 at 09 22 03
Screenshot 2024-07-15 at 09 22 46

**Comment by joanna-pagepro** [comment]
@arrenv It's possible to use checkboxes, but I would have to rewrite a lot of logic that I've added in this PR. Can you create a separate issue for that?

**Comment by joanna-pagepro** [comment]
@arrenv you shouldn't see any new token in suggested tokens list now

**Review by iamsamgibbs — CHANGES_REQUESTED** [review]
Thanks for the changes here, all the changes Arren has asked for are looking good.

Screenshot 2024-07-15 at 12 00 36

Screenshot 2024-07-15 at 12 02 40

Also confirming tokens which are not included in the search by default show up as expected:

Screenshot 2024-07-15 at 12 06 38

The only thing I think might be worth changing is the filtered list when searching shouldn't include results that are already included in the table.
 
Screenshot 2024-07-15 at 12 01 52

I agree checkboxes should be addressed as a new issue.

**Comment by joanna-pagepro** [comment]
@arrenv @iamsamgibbs can you check it again?

**Review by iamsamgibbs — APPROVED** [review]
Thanks Joanna, this is great. Nice work on this issue 👍 

Screenshot 2024-07-16 at 09 54 17

Screenshot 2024-07-16 at 09 54 38

(And the work I did on #2688 is still working nicely)

Screenshot 2024-07-16 at 09 56 30

**Review by arrenv — APPROVED** [review]
@joanna-pagepro All working great, thank you for implementing the increased scope.

On point 2 regarding having checkboxes, thank you for providing details and an estimate. I will review and raise as a separate issue.

**Pull request merged**
