### PR TITLE
Fix: update action input fields placeholders

### LINKED ISSUE #2507: All action types: Table amount inputs
## Description 

All table inputs across all action types need to be updated to increase usability for these areas. Currently, a 0 value is shown as the default placeholder. These should be changed to the following across all responsive sizes: 

**Payment builder/ Advanced Payment action type**

image

1. Replace the 0 to 'Enter amount' for the 'Amount' field
2. Replace the 0 to 'Enter value' for the 'Claim delay' field

**Manage Reputation action type**

image

1. Replace the 0 to 'Enter value' for the 'Change' field

### PR DESCRIPTION
**Pull request by mmioana**
## Description

Update payment builder action input placeholder values 
Update manage reputation action input placeholder value 
Use usePlaceholderAsFallback flag for InputBase width 
Add translations

## Testing

* Step 1. Create Payment builder/Advanced Payment action
* Step 2. Check the placeholder for the Amount field is 'Enter amount'
* Step 3. Check the placeholder for the Claim delay field is 'Enter value'
* Step 4. Create Manage Reputation action
* Step 5. Check the placeholder for the Change field is 'Enter value'

Resolves #2507

### CODE REVIEW

**Review by melyndav — APPROVED** [review]
Hey @mmioana thanks for picking up my issue! Both actions are updated as requested. Thank you! 🦖 

image

**Review by rumzledz — APPROVED** [review]
Yes yes yes! ✨ Much easier to detect the fields now for someone as blind as me @melyndav !! 😉 

image

**Comment by melyndav** [comment]
> Yes yes yes! ✨ Much easier to detect the fields now for someone as blind as me @melyndav !! 😉
> 
> image

Haha @rumzledz this PR is alllll for you! ;)

**Review by iamsamgibbs — APPROVED** [review]
Looks good to me! Nice simple fixes :)

Screenshot 2024-06-27 at 11 28 48

Screenshot 2024-06-27 at 11 30 58

**Pull request merged**
