### PR TITLE
fix: motion data, action name, objective desc length

### PR DESCRIPTION
**Pull request by CzarekDryl**
## Description

- Fixed manage colony objective completed action

## Testing

- Create a new objective action in a colony.
- Try to add a description to the objective action.
- You are limited to only 200 characters.
- Complete the action.
- Notice the missing fields in the completed state.

Resolves [https://github.com/JoinColony/colonyCDapp/issues/2242](https://github.com/JoinColony/colonyCDapp/issues/2242)

### CODE REVIEW

**Review by bassgeta — APPROVED** [review]
Works like a charm, nice pickup! 
image

**Review by iamsamgibbs — COMMENTED** [review]
Good work on this so far, the completed action is looking good:

Screenshot 2024-04-17 at 09 34 19

The error messages are now showing correctly:
 
Screenshot 2024-04-17 at 09 36 19

The description now correctly has a character limit of 4000.

Just a couple of bits it'd be good to get @arrenv to confirm. The "Objective description" field previously had a character limit of 200, this has been increased to 4000 in addition to the "description" field - is it correct that both of these should be 4000?

And this wasn't in the original issue but I've just noticed it here, the placeholder text for "Objective description" is currently "Short objective overview", almost every other text input placeholder starts with "Enter...", does it make sense for consistencies sake to change this placeholder to "Enter a short description". @arrenv can you confirm you're happy with this change / wording? (The "Colony description" field on the "Edit colony details" action also has a similar placeholder).

**Review by melyndav — CHANGES_REQUESTED** [review]
Hi @CzarekDryl nice start on this one.

1. The Objective description should be a maximum of 200 characters and not 4000 as @iamsamgibbs pointed out. 

image

There are two different character limits.
1. 200 for the objective description.
2. 4000 for the action description that appears on every action at the bottom. 

2. This is a product change and is worth fixing in this PR. The objective title should be a maximum of 60 characters. 

3. Can we please change the action title to 'Manage objective' from 'Manage Colony objective'.

4. Also as @iamsamgibbs suggested, please update the placeholder inside the 'Objective description' to be 'Enter short description'.

**Comment by CzarekDryl** [comment]
@melyndav @iamsamgibbs All fixed

**Review by iamsamgibbs — CHANGES_REQUESTED** [review]
Thanks for the changes! Placeholder text looks better now and the character limits are correct.

One tiny change, can you change "Objective" to "objective" here to match the other uses of the word.

Screenshot 2024-04-23 at 10 25 28

The error validation message fix for the description seems to have reverted. Could you fix up the other error messages too?

Screenshot 2024-04-23 at 10 27 58

And if possible could you update the "Colony description" placeholder on the "Edit Colony details" action to match the new placeholder text "Enter short description".

**Comment by CzarekDryl** [comment]
@iamsamgibbs Error messages fixed :)

**Review by melyndav — CHANGES_REQUESTED** [review]
Hi @CzarekDryl nice work on the updates.

The only issue I see is the objective title doesn't wrap on mobile unlike the other input fields and just goes off the screen, making it hard to read the full title. 

image

**Review by iamsamgibbs — CHANGES_REQUESTED** [review]
Thanks for the changes, the 'Colony description' placeholder on the 'Edit Colony details' action is changed.

Screenshot 2024-04-24 at 09 47 53

And the error messages have been updated.

Screenshot 2024-04-24 at 09 46 07

I'm experiencing the same issues Mel has reported, so hopefully just those left to resolve!

**Review by iamsamgibbs — APPROVED** [review]
This looks good now, thanks for the fixes!
 
Screenshot 2024-04-26 at 15 11 44

**Review by melyndav — APPROVED** [review]
Thanks for the updates @CzarekDryl everything is looking great now. Appreciate all your work.

**Review by ArmandoGraterol — APPROVED** [review]
This is it 👌

**Pull request merged**
