### PR TITLE
Feat: Upgrade prettier and eslint, and add prettier-plugin-tailwindcss

### LINKED ISSUE #1886: Add the `prettier-plugin-tailwindcss` npm package
Add the `prettier-plugin-tailwindcss` npm package and update the prettier config file to add in the plugin.

Configure the plugin for use with `clsx` as described here: https://github.com/tailwindlabs/prettier-plugin-tailwindcss?tab=readme-ov-file#sorting-classes-in-function-calls

Also see if it is possible to get automatic sorting where classes are declared in objects as described in #1885.

```
const sizeClasses = {
  xxs: ‘relative w-[1.125rem] h-[1.125rem] rounded-full’,
  xs: ‘h-[1.625rem] w-[1.625rem] relative rounded-full’,
  s: ‘h-[2.125rem] w-[2.125rem] relative rounded-full’,
  …
} 
```

May need to add the following to `/vscode/settings.json`

```
  "tailwindCSS.experimental.classRegex": [
    ["Classes \\=([^;]*);", "'([^']*)'"],
    ["Classes \\=([^;]*);", "\"([^\"]*)\""],
    ["Classes \\=([^;]*);", "\\`([^\\`]*)\\`"]
  ]
```

### PR DESCRIPTION
**Pull request by iamsamgibbs**
## Description

This PR adds the `prettier-plugin-tailwindcss` npm package which automatically sorts tailwind classes based on their recommended class order this will provide consistency in class order throughout the project.

The package required upgrading prettier to v3.

## Testing

Run 'npm ci' to install the new packages. Check the app still builds okay and can lint correctly.

To test the automatic sorting, edit the order of classes in a component, when you save it should automatically sort into the recommended order. This should work inside of clsx too.

## Diffs

**New stuff** ✨

* pretter-plugin-tailwindcss automatic sorting

**Changes** 🏗

* prettier upgraded
* eslint upgraded
* Files affected by the prettier / linting changes

Resolves #1886

### CODE REVIEW

**Review by jakubcolony — APPROVED** [review]
It builds fine, I scanned through the files and also did some regression testing, everything seems good:

https://github.com/JoinColony/colonyCDapp/assets/112586815/6842564b-02f4-4ff7-ab0f-b5d86b6a0ef7

Great job @iamsamgibbs!

**Review by chmanie — APPROVED** [review]
This is great! I just love me such PRs. I think it's much easier to parse if you know what order to expect.

**Review by ArmandoGraterol — APPROVED** [review]
LGTM 👌

**Comment by iamsamgibbs** [comment]
Rebase after the vite merge and ready for re-review

**Review by ArmandoGraterol — APPROVED** [review]
Still working as expected for me 👌

**Review by rdig — APPROVED** [review]
Didn't go too deep into it, but as far as I can tell there's no visual regressions introduced.

Screenshot from 2024-03-19 21-25-57
Screenshot from 2024-03-19 21-26-37
Screenshot from 2024-03-19 21-27-07

Nice work!

**Review by rdig — APPROVED** [review]

**Review by warrencolliver — APPROVED** [review]
As soon as I clicked submit review you pushed a new commit 😃 so did another quick check and everything is still good. great work

**Pull request merged**
