### PR TITLE
feat: include user voter rewards in the user's total rewards

### LINKED ISSUE #2645: User has rewards, but, it is not showing in the UI
## Steps to reproduce

1. Create a new action with the Reputation decision method.
2. Fully Support and Oppose to get to voting.
3. Switch to a different user and vote on the intended winning side. (make sure the user 'Amy' does not have more rep than the threshold)
4. Switch back to the previous user and vote on the intended winning side. (easier if this user 'leela' does pass the voting threshold as you will progress to the reveal stage.)
5. Reveal your vote.
6. Switch back to the other user.
7. Reveal vote. Also, note that you should have some reward, even though you didn't stake.
8. You should be able to finalize. (See this issue https://github.com/JoinColony/colonyCDapp/issues/2644)

## Expected behaviour

* Tokens that the user is able to claim, should show up in the stakes tab.
* Users who vote but don't stake and are on the winning side should receive a reward and it should show in the staking overview of a motion.

## Actual behaviour

* The user has rewards that they should be able to claim, the rewards do not show up as claimable in the stakes tab. I was having finalizing this scenario, so, could be resolved with the issue #2644)
* Users rewards are not showing in the motion staking overview.

image

image

image

### PR DESCRIPTION
**Pull request by bassgeta**
## Description

When user's reveal a vote, they get a very small reward. We didn't display this in the UI before (nor did we keep track in them in the DB).
This PR resolves that, we put the rewards in the database after a vote was revealed.
Thus even users who haven't staked, but have voted, see that they receive a reward. This all happened automatically behind the scenes anyways.
[Block ingestor PR](https://github.com/JoinColony/block-ingestor/pull/263)

## Testing

A handy query to check if the DB is in sync
```gql
query MyQuery {
  getColonyAction(
    id: "<YOUR_TX_HASH>"
  ) {
    type
    motionData {
      id
      isDecision
      isFinalized
      voterRewards  {
        items {
          amount
          colonyAddress
          user {
            id
            profile {
              displayName
            }
          }
        }
      }
      usersStakes {
        address
        stakes {
          raw {
            nay
            yay
          }
        }
      }
    }
  }
}
```

You will need 2 browsers for this, just use `leela` and `amy`

1. Install the voting reputation extension
2. As `leela` create any motion
image
3. Fully support it AND fully oppose it as `leela`
image
4. Open up the transaction as `amy` and cast a support vote
image
5. As `leela` also support it
image
6. As `amy` reveal your vote and run the query above, `amy's rewards should show up in the `voterRewards` array (picture is before renaming)
image
image
7. As `leela` reveal your vote and check it again
image
8. Note that we don't display anything else except the `Finalize` button here
image
9. As `leela` the penalty should now be slightly less than it was usually, since the voter reward gets added
image
10. As `amy` you shouldn't be able to `Claim` rewards but you should see that you have in fact received a small reward
image
11. As `leela` click `Claim`, the same numbers should be present
image

## Diffs

**New stuff** ✨

* Voter rewards get saved into the DB when they a user reveals a vote
* Users who have only voted now see their rewards

**Changes** 🏗

* Before a motion is finalized, we don't display any staking numbers, just the `Finalize` button
* Reworded `Staking overview` into `Your overview`
* The voter reward gets added into the rewards row

Resolves #2645

### CODE REVIEW

**Review by iamsamgibbs — COMMENTED** [review]
Great work on this issue! I know it ended up being a bit of a rabbit hole so nice job getting it all working so nicely.

Following all the testing steps works great, voted as Amy:

Screenshot 2024-08-12 at 10 55 35

Screenshot 2024-08-12 at 10 56 54

Finalize tab for Amy shows correctly:

Screenshot 2024-08-12 at 10 57 48

As is finalize tab for Leela:

Screenshot 2024-08-12 at 10 58 13

The only reason I'm not approving is the original issue has a requirement to show the reward under the claimable tab of the states userhub:

Screenshot 2024-08-12 at 11 52 38

That feels like opening another big can of worms to me as it isn't actually a stake and won't have the same statuses (I guess it only needs claimed / unclaimed) but would need to slot in alongside the other stakes in date order on the "All" tab.

It probably makes sense to take as a separate PR, but I'm also not sure if it would affect the implementation here, maybe it would make more sense to include rewards on the user stake model with a flag to show it is a reward to make the userhub query simpler.

Let me know how you want to handle it and I can approve the work so far if needed.

**Comment by bassgeta** [comment]
> Great work on this issue! I know it ended up being a bit of a rabbit hole so nice job getting it all working so nicely.
> 
> Following all the testing steps works great, voted as Amy:
> Screenshot 2024-08-12 at 10 55 35 Screenshot 2024-08-12 at 10 56 54
> 
> Finalize tab for Amy shows correctly:
> Screenshot 2024-08-12 at 10 57 48
> 
> As is finalize tab for Leela:
> Screenshot 2024-08-12 at 10 58 13
> 
> The only reason I'm not approving is the original issue has a requirement to show the reward under the claimable tab of the states userhub:
> Screenshot 2024-08-12 at 11 52 38
> 
> That feels like opening another big can of worms to me as it isn't actually a stake and won't have the same statuses (I guess it only needs claimed / unclaimed) but would need to slot in alongside the other stakes in date order on the "All" tab.
> 
> It probably makes sense to take as a separate PR, but I'm also not sure if it would affect the implementation here, maybe it would make more sense to include rewards on the user stake model with a flag to show it is a reward to make the userhub query simpler.
> 
> Let me know how you want to handle it and I can approve the work so far if needed.

This is absolutely my fault for not updating the issue comment today, we agreed to skip anything userhub related since it will need design work and it's not a "Claimable" stake. So this tweak, to just show the voter reward in the rewards row is all that's needed.

**Review by mmioana — DISMISSED** [review]
Nice work on this one @bassgeta it works as expected

Screenshot 2024-08-12 at 14 11 16
Screenshot 2024-08-12 at 14 11 58
Screenshot 2024-08-12 at 14 12 43
Screenshot 2024-08-12 at 14 13 20
Screenshot 2024-08-12 at 14 13 48
Screenshot 2024-08-12 at 14 14 02
Screenshot 2024-08-12 at 14 14 13
Screenshot 2024-08-12 at 14 14 33
Screenshot 2024-08-12 at 14 14 47
Screenshot 2024-08-12 at 14 15 06
Screenshot 2024-08-12 at 14 15 17
Screenshot 2024-08-12 at 14 15 31
Screenshot 2024-08-12 at 14 16 01
Screenshot 2024-08-12 at 14 16 21
Screenshot 2024-08-12 at 14 16 35
Screenshot 2024-08-12 at 14 16 49

Just the BLOCK_INGESTOR_HASH should point to commit f695646b80bc9cae327a8a6f26258cc0f773b042

**Review by iamsamgibbs — DISMISSED** [review]
Approving following @bassgeta 's comment! 🎉

**Review by mmioana — APPROVED** [review]
Approving the block ingestor hash change 🥇

**Review by jakubcolony — APPROVED** [review]
Nice work @bassgeta! 

Here's a sped up video of the test:

https://github.com/user-attachments/assets/ac35efc7-a5fe-4de3-8f89-52cf9d3a11d7

All seems to work exactly as described 👍

On a side note, do these values look correct? For `leela`, the reward just before revealing is shown as 0.08621, whereas in the finalize step it is negative:
image

image

**Comment by bassgeta** [comment]
> Nice work @bassgeta!
> 
> Here's a sped up video of the test:
> voting.reward.test.mp4
> 
> All seems to work exactly as described 👍
> 
> On a side note, do these values look correct? For `leela`, the reward just before revealing is shown as 0.08621, whereas in the finalize step it is negative: image
> image

Yeah the values there get pretty funky, I've tested it out on `master` and basically, if you stake as a single user for both sides, the reward is negative according to the calculations :shrug:

**Comment by jakubcolony** [comment]
> Yeah the values there get pretty funky, I've tested it out on master and basically, if you stake as a single user for both sides, the reward is negative according to the calculations 🤷

@bassgeta fair play, it doesn't sound like something users will want to do (staking on both sides as one user)

**Review by jakubcolony — APPROVED** [review]

**Review by mmioana — APPROVED** [review]
Nice nice nice @bassgeta can confirm the testing steps are working as expected 🥳 

Screenshot 2024-08-21 at 11 28 27
Screenshot 2024-08-21 at 11 29 05
Screenshot 2024-08-21 at 11 29 39
Screenshot 2024-08-21 at 11 31 00
Screenshot 2024-08-21 at 11 31 13
Screenshot 2024-08-21 at 11 31 35
Screenshot 2024-08-21 at 11 32 04
Screenshot 2024-08-21 at 11 32 28
Screenshot 2024-08-21 at 11 32 42
Screenshot 2024-08-21 at 11 33 03
Screenshot 2024-08-21 at 11 33 16
Screenshot 2024-08-21 at 11 33 30
Screenshot 2024-08-21 at 11 33 46

**Review by Nortsova — APPROVED** [review]
Great work @bassgeta ! 🙌 

Finalize tab for leela:
image

Finalize tab for amy:
image

**Review by iamsamgibbs — APPROVED** [review]
All looks good to me! Retested and all still working as expected.

Screenshot 2024-08-21 at 11 00 14

Screenshot 2024-08-21 at 11 00 37

**Pull request merged**
