### PR TITLE
Fix: update account avatar upload flow

### LINKED ISSUE #2872: Production: User account avatar UI fixes
## Description

On mobile in production, the upload UI for the user's avatar has broken along the way and now doesn't match Figma and isn't an overall polish UI with a good UX. This mobile variation should be updated to align the UI with the attended Figma design. 

Also, across all desktop and responsive sizes, the default state of the UI doesn't match the Figma designs. The upload form shows by default, with the original UI removed. 

### Issues to resolve: 

**Fix 1: Update the default state to match the designs across all responsive sizes.**

_Current UI default state:_

Desktop:
image

Mobile:
image

_As per Figma:_

Desktop:
image

Mobile: 
image

Figma links: https://www.figma.com/design/0Fi3AaDlr3LAXBfsOXBGyk/User-Account?node-id=6401-11214&t=ptYKBVSP41UE8AwN-4

---

**Fix 2: Mobile upload form should match Figma designs.**

_Current UI:_ 

image

_Figma designs:_
image

Figma links: 
https://www.figma.com/design/0Fi3AaDlr3LAXBfsOXBGyk/User-Account?node-id=6401-12124&t=ptYKBVSP41UE8AwN-4

### PR DESCRIPTION
**Pull request by rumzledz**
## Description

This PR will conditionally show the avatar upload functionality in the User Account page.

new

## Testing

1. Visit the User Account page http://localhost:9091/account/profile
2. You should see the following buttons by default:
- Change avatar
- Remove avatar (if an avatar has been uploaded)
image
3. Clicking "Change avatar" should reveal our file upload component
4. Clicking "Remove avatar" should remove the avatar 

Resolves #2872

### CODE REVIEW

**Review by rdig — APPROVED** [review]
Nicely done. Works as expected.

Also, thanks for updating the auth proxy back to it's correct version.

Screenshot from 2024-08-27 17-20-59
Screenshot from 2024-08-27 17-21-01
Screenshot from 2024-08-27 17-21-20

**Review by bassgeta — APPROVED** [review]
Code changes look very sensible and best of all, stuff works :sunglasses: 
image
image
Upon clicking remove:
image
Tablet view:
image

**Review by iamsamgibbs — APPROVED** [review]
Nice job! All looks as expected on desktop:

Screenshot 2024-08-29 at 08 48 58

Screenshot 2024-08-29 at 08 49 04

Screenshot 2024-08-29 at 08 49 30

And on mobile:

Screenshot 2024-08-29 at 08 52 18

Screenshot 2024-08-29 at 08 52 55

Screenshot 2024-08-29 at 08 53 02

Also tested as a user with a brand new profile without issue.

The only thing that might be worth adding (at a later point unless you really want to add it) is a confirmation modal when you click "Remove avatar". Feels a bit too easy to me to accidentally remove your avatar currently.

**Comment by rumzledz** [comment]
> The only thing that might be worth adding (at a later point unless you really want to add it) is a confirmation modal when you click "Remove avatar". Feels a bit too easy to me to accidentally remove your avatar currently

I like this idea @iamsamgibbs , I'll discuss this with product 👌

**Pull request merged**
