### PR TITLE
Fix: User header hover state and padding

### LINKED ISSUE #1630: Global: User header hover state
## Description

- **Issue one:**

Currently, the hover state & select states for the top right user header (desktop only) shown globally have two different hover state colours. The correct colour token for the outline hover state should be text-blue-400. 

Currently, the user hub hover & select state is showing as text-gray-900 and is incorrect.

image

Link to hover/active state in Figma: https://www.figma.com/file/5V8pr7iMwXsT9L3VAZsmUt/Colony-V5?type=design&node-id=1938-226813&mode=design&t=V9WB8knufbS8936p-4

- **Issue two**

The padding in the user hub pill between the username and the reputation star should be 8px as per Figma. 

As per Figma: 
image

Link to correct padding in Figma: https://www.figma.com/file/5V8pr7iMwXsT9L3VAZsmUt/Colony-V5?type=design&node-id=1938-226813&mode=design&t=V9WB8knufbS8936p-4

### PR DESCRIPTION
**Pull request by iamsamgibbs**
## Description

User header hover state has been changed from border-gray-900 to border-blue-400.

Border colour now stays blue whilst menu is visible.

Padding between username and reputation star changed from 12px to 8px.

Hamburger menu icon now stays blue whilst menu is visible.

**Changes** 🏗

* Added hover:!border-blue-400 to override existing tertiary button style on hover
* Removed 'isMobile' from className check so that border stays blue when the menu is open on desktop as well as mobile
*  Changed outer div from gap-3 to gap-2 to fix padding size
* Removed 'isMobile' from 'isOpened' check on Hamburger element
* Removed border hover state from Hamburger is menu is open to ensure it remains solid blue when open

Hover state border colour changed
Screenshot 2024-01-09 at 16 21 36

Active state border colour changed
Screenshot 2024-01-09 at 16 21 48

Hamburger icon active state border colour changed
Screenshot 2024-01-09 at 16 21 54

Resolves #1630

### CODE REVIEW

**Review by bassgeta — DISMISSED** [review]
Does it need a rebase because it's showing changes from the details button regression PR as changes? other than that GJ :muscle:

**Review by melyndav — DISMISSED** [review]
Nice work on this one @iamsamgibbs! Approved from my side! :)

**Review by melyndav — DISMISSED** [review]

**Review by rdig — DISMISSED** [review]
All good on the styling changes

Screenshot from 2024-01-10 13-48-58

However, why does this PR also include commits by @bassgeta? Does this need to be rebased by chance ?

**Review by rdig — APPROVED** [review]

**Review by melyndav — APPROVED** [review]
Approving again @iamsamgibbs! :)

**Review by arrenv — APPROVED** [review]
Looks good, nice one!

**Pull request merged**
