### PR TITLE
Feat: Implement Multi-Sig extension was uninstalled UI

### LINKED ISSUE #2712: [Multi-sig] feat: implement extension was uninstalled UI
### Story

As a user when I view a multi-sig transaction after the extension has been uninstalled, I should see a component showing the extension status and a message.

### Description

Currently there is a placeholder UI which displays when the extension has been uninstalled.

There (should) already exist a component which is displayed when the voting reputation extension has been uninstalled. We should be able to re-use this with the correct multi-sig extension name.

### Design

[Figma link to the voting reputation version](https://www.figma.com/design/5V8pr7iMwXsT9L3VAZsmUt/Colony-v5?node-id=22857-221890&t=Eq8J9IE9YnZuNQ7r-4)

How it currently looks:

Screenshot_2024-07-16_at_10 56 35

How it should look: (Replace voting reputation with the multi-sig extension name)

image

### This issue is complete when...

- [ ] The uninstalled status component shows correctly when the extension is uninstalled.

### Suggestions

Check what happens when the extension is in the deprecated state. It should be possible to complete multi-sig motions which are still in progress. (But shouldn't be possible to create new ones). (Any issues around this don't need to be resolved as part of this issue, only if it relates to this UI component).

Check this works correctly when the extension is re-installed. (I'm not actually sure what should happen here, but check it at least doesn't break things)

### PR DESCRIPTION
**Pull request by davecreaser**
## Description

- Implement the UI in the action sidebar which should be shown to users when they are accessing a multi sig action _after_ the multi sig extension has been uninstalled.
- Also implement this UI for Reputation Voting actions, since it wasn't there already.

[Link to designs here](https://www.figma.com/design/5V8pr7iMwXsT9L3VAZsmUt/Colony-v5?node-id=22857-221890&t=Eq8J9IE9YnZuNQ7r-4)

## Testing

* Install the multi sig extension
* Create a mint tokens multi sig action
* Uninstall the multi sig extension
* Go back to the mint token action, and check that you have a message in the sidebar explaining that the extension is uninstalled.
Screenshot 2024-07-18 at 16 23 05

* Repeat the above steps, but this time for Reputation Voting, not Multi Sig
Screenshot 2024-07-18 at 16 23 13

## Diffs

**New stuff** ✨

* New UninstalledMessage component, which is flexible and can be used for any extension.

**Changes** 🏗

* Ensure invalid motion statuses are displayed correctly.

Resolves #2712

### CODE REVIEW

**Comment by davecreaser** [comment]
Some updates to this PR: The statuses should now correctly be "Uninstalled" for the actions whenever the extension is uninstalled, both in the action sidebar and the activity table. Also it should handle reinstalling the extension properly.

**Review by mmioana — APPROVED** [review]
Great work on this one @davecreaser 👏 

Tested Mint tokens action for both extensions and uninstalled them after
Screenshot 2024-07-22 at 13 14 34
Screenshot 2024-07-22 at 13 15 40
Screenshot 2024-07-22 at 13 16 10
Screenshot 2024-07-22 at 13 16 36
Screenshot 2024-07-22 at 13 18 09
Screenshot 2024-07-22 at 13 18 41

**Comment by Nortsova** [comment]
Hey @davecreaser,

I have a quick question regarding the reputation feature. After re-enabling it, I noticed it works differently from MultiSig.

Both motions - _passed_ and _pending_ - become _**uninstalled**_ (even if I reinstall the extension). Is this expected?

image

**Comment by davecreaser** [comment]
Hey @Nortsova, thanks for the review! Yes it's expected. Once we uninstall the reputation extension we lose all history of that motion, so it goes into the special `uninstalled` state no matter what, even after reinstalling.

**Pull request merged**
