### PR TITLE
feat: added meatball menu in completed action

### PR DESCRIPTION
**Pull request by CzarekDryl**
## Description
Added meatball menu to completed action. For now, it is only added to these actions because adv payments are not ready yet:
- Simple Payment
- Transfer funds
- Mint tokens
- Manage Reputation
- Manage Permissions

## Testing

* Create a action listed above
* Use meatball menu options to redo action or check on explorer
image

## Diffs

**New stuff** ✨

* New stuff goes here

## TODO

- Implement this functionality in Payment Builder, Split Payment, Staged Payment, Streaming Payment.

Resolves [#2311](https://github.com/JoinColony/colonyCDapp/issues/2311)

### CODE REVIEW

**Review by melyndav — CHANGES_REQUESTED** [review]
Hey @CzarekDryl nice work on this one!

Everything looks good, I did notice one issue with the number in the metadata when I select 're-do' action as you can see in the screenshot the formatting breaks. But the number in the amount column stays the same as the completed state. 

image

**Review by iamsamgibbs — CHANGES_REQUESTED** [review]
Looks good to me other than the issue Mel already raised!

Thanks for fixing the 'uncontrolled input' error from the amount field too.

Screenshot 2024-05-09 at 15 31 26

(Same issue as Mel)

Screenshot 2024-05-09 at 15 33 18

**Comment by CzarekDryl** [comment]
@melyndav @iamsamgibbs This should work fine now.

**Review by melyndav — APPROVED** [review]
Works perfectly, thanks for the fix on this one @CzarekDryl

**Review by iamsamgibbs — APPROVED** [review]
All good now, thanks for the fix!

Screenshot 2024-05-15 at 08 38 39

**Pull request merged**
