### PR TITLE
fix: calamity banner upgrade colony version action in new ui

### PR DESCRIPTION
**Pull request by joanna-pagepro**
https://tw.auroracreation.com/app/tasks/15657574

### CODE REVIEW

**Review by ArmandoGraterol — APPROVED** [review]
It is, indeed, opening the new side panel 👍

**Review by KornelKwiatkowski — APPROVED** [review]

**Review by melyndav — APPROVED** [review]
Thanks for fixing the width. This is approved.

**Review by krawczykkatarzyna — APPROVED** [review]

**Review by rdig — DISMISSED** [review]
After your latest changes the calamity banner no longer shows up

Screenshot from 2023-11-21 14-44-42

**Review by arrenv — APPROVED** [review]
Banner is showing up correctly now, thank you!

**Pull request merged**
